### PR TITLE
[2.x] fix: Fix flaky client tests

### LINKED ISSUE #8608: client tests seem flakey
## steps

CI.

## problems

The client test seems flaky.

### PR DESCRIPTION
**Pull request by circlecrystalin**
Closes #8608

---

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=5625555

### CODE REVIEW

**Comment by circlecrystalin** [comment]
@eed3si9n Could you please review my second pr?

**Comment by eed3si9n** [comment]
Thanks for the contribution! 
1. Could you scope this PR to one of the two fixes?
2. Could you also include a test, if not automated some manual process that someone can follow along?

**Comment by circlecrystalin** [comment]
@eed3si9n Could you please review again?

**Comment by circlecrystalin** [comment]
> Thanks for the contribution!
> 
> 1. Could you scope this PR to one of the two fixes?
> 2. Could you also include a test, if not automated some manual process that someone can follow along?

1. I made this to resolve only one issue.
2. I have added manual process. So someone can follow.

@eed3si9n Could you please check my pr?

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala [hunk 1]
```diff
@@ -691,14 +705,6 @@ class NetworkClient(
...
         case (`Shutdown`, Some(_))                => Vector.empty
         case (msg, _) if msg.startsWith("build/") => Vector.empty
-        case ("sbt/exec", Some(json)) =>
-          import sbt.protocol.codec.JsonProtocol.given
-          Converter.fromJson[ExecStatusEvent](json) match {
-            case Success(event) if event.status == "Queued" =>
-              event.message.foreach(m => errorStream.println(s"[info] $m"))
-              Vector.empty
-            case _ => Vector.empty
-          }
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/client/NetworkClient.scala:701]: Was this removal intentional?

Comment (circlecrystalin) [reply main-command/src/main/scala/sbt/internal/client/NetworkClient.scala:701]: @eed3si9n No, it was unintentional—I've restored the sbt/exec notification handler for Queued status messages.

**Comment by circlecrystalin** [comment]
@eed3si9n Please check again...

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala [hunk 2]
```diff
@@ -177,7 +178,20 @@ class NetworkClient(
...
+        level match {
+          case Level.Error =>
+            errorStream.println(message)
+            errorStream.flush()
+          case _ =>
+            printStream.println(message)
+            printStream.flush()
+        }
+      }
+    }
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/client/NetworkClient.scala]: Could you explain why this is necessary? sbt doesn't output error-level logs to stderr normally.

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala [hunk 3]
```diff
@@ -677,6 +691,14 @@ class NetworkClient(
...
           batchMode.set(false)
           Vector.empty
+        case ("sbt/exec", Some(json)) =>
+          import sbt.protocol.codec.JsonProtocol.given
+          Converter.fromJson[ExecStatusEvent](json) match {
+            case Success(event) if event.status == "Queued" =>
+              event.message.foreach(m => errorStream.println(s"[info] $m"))
+              Vector.empty
+            case _ => Vector.empty
+          }
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/client/NetworkClient.scala]: Also unless there's a reason, could we put this `case` back to where it was please, to avoid unnecessary diffs.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala (hunk 2 above)
Comment (circlecrystalin) [reply main-command/src/main/scala/sbt/internal/client/NetworkClient.scala]: You're right—this was changed for forked process output in client watch mode (#7527), but I'm open to adjusting it to match sbt's normal logging behavior if you prefer.

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala (hunk 3 above)
Comment (circlecrystalin) [reply main-command/src/main/scala/sbt/internal/client/NetworkClient.scala]: Done—moved it back to its original position to minimize the diff.

**Comment by circlecrystalin** [comment]
I have updated my codebase what you wanted. Please check again...

**Comment by eed3si9n** [comment]
I'm trying to test this locally, but I can't reproduce the issue - https://github.com/sbt/sbt/issues/7527#issuecomment-3782456562

File: launcher-package/integration-test/src/test/scala/ShellScriptUtil.scala [hunk 4]
```diff
@@ -45,7 +45,13 @@ trait ShellScriptUtil extends BasicTestSuite {
...
       test(name) {
         val workingDirectory = Files.createTempDirectory("sbt-launcher-package-test").toFile
-        retry(() => IO.copyDirectory(new File("launcher-package/citest"), workingDirectory))
+        val citestDir = new File("launcher-package/citest")
+        // Clean target directory if it exists to avoid copying temporary files
+        val targetDir = new File(citestDir, "target")
+        if (targetDir.exists()) {
+          IO.delete(targetDir)
+        }
+        retry(() => IO.copyDirectory(citestDir, workingDirectory))
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/ShellScriptUtil.scala]: I created a separate issue for this https://github.com/sbt/sbt/issues/8608. Would you like to send this in a separate PR, or reuse this PR?

Comment (circlecrystalin) [reply launcher-package/integration-test/src/test/scala/ShellScriptUtil.scala]: I will reuse this PR.

**Comment by circlecrystalin** [comment]
I just updated, could you please check again?

**Comment by eed3si9n** [comment]
If you'd like to reuse this PR, could you drop all but the last two commits using `git rebase -i develop` please?

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala [hunk 5]
```diff
@@ -177,7 +177,14 @@ class NetworkClient(
...
     def success(message: => String): Unit = ()
-    def log(level: Level.Value, message: => String): Unit = console.appendLog(level, message)
+    def log(level: Level.Value, message: => String): Unit = {
+      // For forked processes in client mode, write directly to output streams
+      // to ensure stdout/stderr is captured correctly, especially during watch re-evaluation
+      synchronized {
+        printStream.println(message)
+        printStream.flush()
+      }
+    }
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/client/NetworkClient.scala]: Could you remove the diff here please, since I'm not able to reproduce https://github.com/sbt/sbt/issues/7527, at least on my machine.

**Review by eed3si9n — APPROVED** [review]
Thanks!
