### PR TITLE
Fix ANSI escape sequences.

### LINKED ISSUE #1143: ansi escape sequence stripping is broken
The ansi escape sequence stripping (`ConsoleLogger.removeEscapeSequences`) is broken, especially when stripping escapes for colouring.  An example colour escape sequence is `<ESC>[33m`, only the `<ESC>[` is being stripped, leaving the `33m` behind.

According to wikipedia:

> Escape sequences start with the character ESC (ASCII decimal 27/hex 0x1B/octal 033). For two character sequences, the second character is in the range ASCII 64 to 95 (@ to _). However, most of the sequences are more than two characters, and start with the characters ESC and [ (left bracket). This sequence is called CSI for Control Sequence Introducer (or Control Sequence Initiator). The final character of these sequences is in the range ASCII 64 to 126 (@ to ~).

The problem with the current logic is that it's missing the middle bit about the second character either being ASCII 64 to 95 or 96 (`[`), and just looks for the final character in range 64 to 126, so for > 2 character escapes, it will never strip the CSI.

### PR DESCRIPTION
**Pull request by jsuereth**
Now we handle the CSI (ESC + [).

Fixes #1143 

Review by @eed3si9n

### CODE REVIEW

File: util/log/src/main/scala/sbt/ConsoleLogger.scala [hunk 1]
```diff
@@ -35,6 +35,19 @@ object ConsoleLogger {
   def isEscapeTerminator(c: Char): Boolean =
     c >= '@' && c <= '~'
 
+  /**
+   * Test if the character AFTER an ESC is the ANSI CSI, which means more than two characters until terminatioin.
```
Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: See http://en.wikipedia.org/wiki/ANSI_escape_code#Sequence_elements

> There is a single-character CSI (`155`/`0x9B` /`0233`) as well. The `ESC[` two-character sequence is more often used than the single-character alternative ...
> Only the two-character sequence is recognized by devices that support just ASCII (7-bit bytes) or devices that support 8-bit bytes, but use the 0x80–0x9F control character range for other purposes. On terminals that use UTF-8 encoding, both forms take 2 bytes (CSI in UTF-8 is `0xC2`, `0x9B`) but the `ESC[` sequence is clearer.

File: util/log/src/main/scala/sbt/ConsoleLogger.scala [hunk 2]
```diff
@@ -35,6 +35,19 @@ object ConsoleLogger {
...
+   */
+  def isCSI(c: Char): Boolean = c == '['
+
+  /**
+   * Tests whether or not a character needs to immediately terminate the ANSI sequence.
+   */
+  def isSimpleEscapeTerminator(c: Char): Boolean = {
+    val n = c.toInt
+    (n >= 64) && (n <= 95)
```
Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Citation needed. http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes

> The final byte is technically any character in the range `64`–`126` (hex `0x40`–`0x7E`, ASCII `@` to `~`)

File: util/log/src/main/scala/sbt/ConsoleLogger.scala (hunk 1 above)
Comment (jsuereth) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Right.  We never parsed that before, at all.   I also don't think we use it.

This fixes the initial bug and invalid handling if ESC[. We need to improve this anyway for the request about filtering color escapes separately from cursor control.   So I think this PR is ok as is.

File: util/log/src/main/scala/sbt/ConsoleLogger.scala (hunk 2 above)
Comment (jsuereth) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Not for 2 character codes

Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Link?

Comment (jsuereth) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: The same.  Read further

Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: http://en.wikipedia.org/wiki/ANSI_escape_code#Sequence_elements

> Escape sequences start with the character ESC (ASCII decimal 27/hex 0x1B/octal 033). For two character sequences, the second character is in the range ASCII 64–95 (@ to _).

ok. So this is non-CSI case. Having `isEscapeTerminator` and `isSimpleEscapeTerminator` without any explanation is a bit confusing. Also these are all public functions?

Comment (jsuereth) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Also github mobile interface stinks.

Your link is just CSI escape codes.  Check above in the doc for non CSI escapes

Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Also would it make sense to write `'@'` instead of `64` to be consistent with the `isEscapeTerminator` above?

Comment (eed3si9n) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: > Check above in the doc for non CSI escapes

Yea. I now understand the code is valid. Now just nitpicking on readability.

Comment (jsuereth) [inline util/log/src/main/scala/sbt/ConsoleLogger.scala]: Yeah, all good points. I'll add the references and more description of why.

TBH - i'm really not sure what the "known escapes" are from in the tests, still.  They're definitely not ANSI, but there must be a reason we try to escape them.

**Comment by eed3si9n** [comment]
Travis is reporting failure on `dependency-management/metadata-only-resolver`.

**Comment by eed3si9n** [comment]
Notes plz

**Comment by jsuereth** [comment]
@eed3si9n notes added, cleanups made.  Need to see if travis succeeds on unrelated tests....

**Comment by jsuereth** [comment]
@eed3si9n The failure is disconcerting.  We're testing whether we find the JAR correctly to resolve the pom.  Maven-central only has a pom, but anotehr repo has the JAR, so we need to fail to resolve until the other resolver is in place.  But that repo may be gone:

```
 Server access Error: Connection timed out url=http://maven.nuxeo.org/nexus/content/groups/public/com/sun/jmx/jmxri/1.2.1/jmxri-1.2.1.jar
[info] [warn]   [
```

**Comment by jsuereth** [comment]
@eed3si9n failure is due to publishLocal.  I know you just fixed this, so am I not up-to-date with master?  I just did a rebase, but it still seems bad.  Ideas welcome.

**Comment by eed3si9n** [comment]
It seems like the test fails at some probability. Local test and #1879 show that on their own these tests are passing ok (I just checked running https://travis-ci.org/sbt/sbt/builds/52092661 now again).
