### PR TITLE
[2.x] fix: Resolve virtual file refs in scaladoc options

### LINKED ISSUE #8740: [2.x] scaladoc failure when semanticdbEnabled is enabled on scala 2.x projects
## steps

```
➜ cat project/build.properties
sbt.version=2.0.0-RC8
```
```
➜ cat build.sbt
semanticdbEnabled := true
scalaVersion := "2.12.21"
```
```
➜ cat src/main/scala/A.scala
object A
```

## problem

Scaladoc failure

```
sbt:test> doc
[error] bad option: -P:semanticdb:targetroot:/private/tmp/test/target/out/jvm/scala-2.12.21/test/meta
[error] one error found doc 0s
[error] stack trace is suppressed; run last Compile / doc for the full output
[error] (Compile / doc) Scaladoc generation failed
[error] elapsed time: 1 s, cache 7%, 1 disk cache hit, 13 onsite tasks
```
```
sbt:test> last doc
[debug] Getting org.scala-sbt:compiler-bridge_2.12:2.0.0-M11:compile for Scala 2.12.21
[debug] Calling Scaladoc with arguments:
[debug] 	-d
[debug] 	/private/tmp/test/target/out/jvm/scala-2.12.21/test/api
[debug] 	-Xplugin:${CSR_CACHE}/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.21/4.14.2/semanticdb-scalac_2.12.21-4.14.2.jar
[debug] 	-Yrangepos
[debug] 	-P:semanticdb:targetroot:/private/tmp/test/target/out/jvm/scala-2.12.21/test/meta
[debug] 	-bootclasspath
[debug] 	/Users/brice.jaglin/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.jar
[debug] 	-classpath
[debug] 	dummy_8e2dff45
[debug] 	/private/tmp/test/src/main/scala/A.scala
[error] bad option: -P:semanticdb:targetroot:/private/tmp/test/target/out/jvm/scala-2.12.21/test/meta
[error] one error found
[error] Scaladoc generation failed
[error] 	at xsbt.Runner.run(ScaladocBridge.scala:50)
[error] 	at xsbt.ScaladocBridge.run(ScaladocBridge.scala:21)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:154)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Defaults$.docTaskSettings$$anonfun$5(Defaults.scala:1997)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:295)
[error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:275)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[error] (Compile / doc) Scaladoc generation failed
```

## expectation

No errror, like in sbt 1.x

```
➜ cat project/build.properties
sbt.version=1.12.2
```

```
sbt:test> doc
[info] Main Scala API documentation to /private/tmp/test/target/scala-2.12/api...
model contains 2 documentable templates
[info] Main Scala API documentation successful.
[success] Total time: 1 s, completed 14 Feb 2026, 19:19:25
```

## notes

The error points at the `-P:semanticdb` flag but I think the real problem is that the plugin that is not properly loaded because `CSR_CACHE`  is not expanded when calling Scaladoc, and thus associated flags are rejected.

Judging by the logs,  when it works, `CSR_CACHE` does get expanded, for example with
- `doc` on sbt 1.x
- `compile` on any sbt version

### PR DESCRIPTION
**Pull request by speedcoder430**
## Problem

Fixes #8740

When `semanticdbEnabled := true` is set on Scala 2.x projects, the `doc` task fails because `${CSR_CACHE}` placeholders in `scalacOptions` (specifically the `-Xplugin:` path for the semanticdb compiler plugin JAR) are not resolved before being passed to Scaladoc. This causes:

```
[error] bad option: -P:semanticdb:targetroot:/path/to/target/meta
[error] (Compile / doc) Scaladoc generation failed
```

The root cause is that the plugin JAR path contains an unresolved `${CSR_CACHE}` variable, so the plugin fails to load, and its associated `-P:semanticdb:*` flags are rejected as unknown options.

### Reproduction (from #8740)

```scala
// build.sbt
semanticdbEnabled := true
scalaVersion := "2.12.21"
```

```
sbt> doc
[error] bad option: -P:semanticdb:targetroot:...
```

## Solution

Resolve virtual file references (containing `$`) in `scalacOptions` before passing them to the Scaladoc bridge in `docTaskSettings`. This matches the approach already used in zinc's `MixedAnalyzingCompiler.compileScala()` (see sbt/zinc#1545), which resolves `$` variables for compilation but not for doc generation.

The resolution splits each option by `:` and `,`, then converts any part containing `$` via `VirtualFileRef.of() -> converter.toPath()`.

## Tests

- New `project/semanticdb-doc` scripted test: runs `doc` on a Scala 2.12 project with `semanticdbEnabled := true`
- Ran `project/*`, `actions/*`, `compiler-project/*` scripted test suites locally — all pass

## AI Disclosure

This PR was developed with assistance from GitHub Copilot (Claude Opus 4.6). All code changes, test design, and debugging were AI-assisted.

Generated-by: GitHub Copilot (Claude Opus 4.6)

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution. lgtm pending CI.

**Comment by speedcoder430** [comment]
> Thanks for the contribution. lgtm pending CI.

Thanks for approving my PR. Seems CI passed successfully.

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -2064,6 +2064,13 @@ object Defaults extends BuildCommon {
                 if (ScalaArtifacts.isScala3(sv)) Opts.doc.externalAPIScala3(xapisFiles)
                 else Opts.doc.externalAPI(xapisFiles)
               val options = sOpts ++ externalApiOpts
+              def convertVfRef(value: String): String =
+                if !value.contains("$") then value
+                else converter.toPath(VirtualFileRef.of(value)).toString
+              val resolvedOptions = options.map { x =>
+                if !x.contains("$") then x
+                else x.split(":").map(_.split(",").map(convertVfRef).mkString(",")).mkString(":")
+              }
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala:2073]: Ideally, this should be pushed to Zinc, but I'm fine with this workaround for now.

Comment (speedcoder430) [reply main/src/main/scala/sbt/Defaults.scala:2073]: Thanks
