### PR TITLE
[2.x] fix: Fixes ActionCache tests on Windows

### LINKED ISSUE #7656: [2.x] `ActionCache` is broken on Windows
Last time I tried sbt 2.x on Windows I noticed that the `ActionCache` was broken because of symbolic links.

### LINKED ISSUE #8627: Enable scripted cache/* on windows-latest
## Expectation

Enable scripted cache/* on windows-latest:

```yaml
          - os: windows-latest
            java: 17
            distribution: zulu
            jobtype: 12
....
      - name: Build and test (12)
        if: ${{ matrix.jobtype == 12 }}
        shell: bash
        run: |
          ./sbt -v "scripted cache/*"
```

Make the tests pass.

## Note

Currently some of the tests will fail.

```
[error] 	cache/basic
[error] 	cache/optout
[error] 	cache/transitive
```

### PR DESCRIPTION
**Pull request by spider-yamet**
Fixes #8627
Fixes https://github.com/sbt/sbt/issues/7656

## Problem

Currently, `scripted cache/*` tests are not enabled on Windows CI. The issue #8627 identifies that cache/basic, cache/optout, and cache/transitive tests fail on Windows, preventing cache functionality from being validated on the Windows platform.

## Solution

This PR enables `scripted cache/*` tests on Windows CI by adding jobtype 12 to the Windows matrix, following the exact specification from issue #8627:

- Added Windows matrix entry with:
  - `os: windows-latest`
  - `java: 17`
  - `distribution: zulu`
  - `jobtype: 12`

- Added CI step to run `scripted cache/*` tests for jobtype 12

This is the first step to enable the tests. Once CI runs, we can identify the specific failures and address them in follow-up commits.

## Testing

- CI configuration follows existing patterns (matches jobtype 2 structure)
- YAML syntax validated (no linter errors)
- Changes are minimal and focused (only CI configuration)

## Notes

- This PR enables the tests but does not fix the failing tests yet
- Test failures will be visible in CI logs after this PR is merged
- Follow-up PRs will address the specific Windows-specific issues identified in CI

### CODE REVIEW

**Comment by eed3si9n** [comment]
FYI - if you go to the Actions tab on your forked repo you can enable CI workflow to run there - https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#getting-started

File: util-cache/src/main/scala/sbt/util/ActionCache.scala [hunk 1]
```diff
@@ -82,8 +82,18 @@ object ActionCache:
...
+        outputs.filter(f =>
+          f match
+            case svf: StringVirtualFile1 if svf.id.startsWith("target/out/") =>
+              false
+            case svf: StringVirtualFile1 if svf.id.endsWith(ActionCache.dirZipExt) =>
+              false
+            case _ =>
+              val outputPath = fileConverter.toPath(f).toAbsolutePath.normalize()
+              !outputPath.startsWith(normalizedOutputDir)
+        )
```
Comment (eed3si9n) [inline util-cache/src/main/scala/sbt/util/ActionCache.scala:94]: `StringVirtualFile1` is supposed to transparently replace the normal virtual file. If it requires special treatment, then I wonder if there's a bug that we should fix. For example, if we replaced `target/out` with `${OUT}` in https://github.com/sbt/sbt/blob/5789a7ef77a25330e2e5c99ec61ab3d2b1c0e1e0/sbt-app/src/sbt-test/cache/basic/build.sbt etc, would it work without this patch?

Comment (spider-yamet) [reply util-cache/src/main/scala/sbt/util/ActionCache.scala:94]: Hi, @eed3si9n I am currently replacing hard coded target/out to ${OUT}, and experiencing scalafmt on ubuntu-22.04 ci, I will let you know once I resolve this error.

Comment (spider-yamet) [reply util-cache/src/main/scala/sbt/util/ActionCache.scala:94]: @eed3si9n Seems working now, and implemented ${OUT} logic. could you please check once again?

image

File: util-cache/src/main/scala/sbt/util/ActionCache.scala [hunk 2]
```diff
@@ -82,8 +82,16 @@ object ActionCache:
             cacheEventLog.append(ActionCacheEvent.Error)
             throw e
       val json = Converter.toJsonUnsafe(result)
+      val normalizedOutputDir = outputDirectory.toAbsolutePath.normalize()
       val uncacheableOutputs =
-        outputs.filter(f => !fileConverter.toPath(f).toAbsolutePath.startsWith(outputDirectory))
+        outputs.filter(f =>
+          f match
+            case svf: StringVirtualFile1 if svf.id.endsWith(ActionCache.dirZipExt) =>
+              false
```
Comment (eed3si9n) [inline util-cache/src/main/scala/sbt/util/ActionCache.scala]: Do we need special treatment of StringVirtualFile1 here? Could we substitute svf: StringVirtualFile1 with any vf.id?

File: util-cache/src/main/scala/sbt/util/ActionCache.scala [hunk 3]
```diff
@@ -98,7 +106,20 @@ object ActionCache:
...
+                case svf: StringVirtualFile1 =>
+                  val outputPath = fileConverter.toPath(svf).toAbsolutePath.normalize()
+                  val inOutputDir = outputPath.startsWith(normalizedOutputDir)
+                  val notSynced = !syncedPaths.contains(outputPath)
+                  if inOutputDir && notSynced then
+                    Option(outputPath.getParent()).foreach(parent =>
+                      IO.createDirectory(parent.toFile())
+                    )
+                    if !Files.exists(outputPath) || Files.size(outputPath) == 0 then
+                      IO.write(outputPath.toFile(), svf.content)
```
Comment (eed3si9n) [inline util-cache/src/main/scala/sbt/util/ActionCache.scala]: Why do we still this special treatment of StringVirtualFile1 after using `${OUT}`?

Comment (spider-yamet) [reply util-cache/src/main/scala/sbt/util/ActionCache.scala]: And here I removed StringVirtualFile1 write logic after syncBlobs.

File: util-cache/src/main/scala/sbt/util/ActionCache.scala (hunk 2 above)
Comment (spider-yamet) [reply util-cache/src/main/scala/sbt/util/ActionCache.scala]: Now I changed the .dirZipExt check from case svf: StringVirtualFile1 if svf.id.endsWith(...) to a generic case vf if vf.id.endsWith(...).

**Review by eed3si9n — APPROVED** [review]
Thanks!
