### PR TITLE
Automatically run GC/finalization after each task execution.

### LINKED ISSUE #1223: Reducing PermGen usage in sbt
I tracked down a PermGen leak in sbt, which can easily be worked around (although other PermGen leaks may exist).

The full story is below, but in short object finalizers are not called frequently enough by the VM (in jdk 6 and 7), causing classloaders to survive long past their time.

The solution is adding after the parts of runTask that create a new classloader, in order to launch Scala or other utilities, the sequence:

```
{ System.gc(); java.lang.System.runFinalization(); System.gc() }
```

That must be done from an enclosing stack frame that no longer contains any reference, direct or indirect, to the generated classloader (note that escape analysis was not generally on by default in jdk 6).

The complete, albeit condensed explanation, is:
- Each time sbt invokes the Scala compiler, by creating a new classloader, the classloader is not released.
- the classloader is kept in the heap by means of a chain of links involving weak references. In particular, when the garbage collector runs and frees the referent from a weak reference, the referred instance may still being tracked if some finalization is still pending.
- if finalization is not run promptly, the classloader cannot be freed, and its permgen cannot be released.
- file descriptors, like FileInputStream or JarFile, are all finalizable, and sbt uses a lot of them.
- the jdk 6 and 7 are quite lazy when running finalizers. If there is still heap space, they will not rush to complete finalization in order to free memory. The VMs will not notice that PermGen is slowly running out.
- as a net result, I saw cases in which there are more than 47'000 file descriptors lying idle in the system, indirectly keeping classloaders from being reclaimed, and leading some code to crash despite being given 1GB of PermGen.
- adding an explicit invocation to runFinalization(), following the exact sequence described above, will solve the problem. The first gc() causes the referent of the WeakReferences to be released, and tracks the newly freed finalizable objects. The runFinalization() call forces the jvm to deal with those instances immediately. Finally, the second gc() will deallocate them. Once the file descriptors are freed, the weak references are also freed, the classloader is freed, and therefore its PermGen space is in the end also freed.

More in general,  when using together weak references, multiple classloaders, and files (even if you close them), manual invocations to runFinalization() will be needed, or you will get leaks that may show up as "Too many files" or "PermGen Error". 

Java 8 replaces the PermGen with a "Meta" space, but it is still subject to leaks. However, it calls finalizers more promptly, which avoids this issue. Java 6 and Java 7 are both affected.

### PR DESCRIPTION
**Pull request by jsuereth**
Fixes #1223.
- Add a new key to disable forcing the garbage collector to run
  after each task-executioin
- Add a new flag to disable forcing the garbage collector to run
  after each task-exeuction
- Add a hook into EvalauteTask to run System.gc/System.runFinalization
  after each task execution

Review by @eed3si9n

### CODE REVIEW

File: main/src/main/scala/sbt/EvaluateTask.scala [hunk 1]
```diff
@@ -198,6 +211,9 @@ object EvaluateTask
 		val maker: State => Keys.TaskProgress = getSetting(Keys.executeProgress, const(new Keys.TaskProgress(defaultProgress)), extracted, structure)
 		maker(state).progress
    }
+   // TODO - Should this pull from Global or from the project itself?
+   private[sbt] def forcegc(extracted: Extracted, structure: BuildStructure): Boolean =
+      getSetting(Keys.forcegc in Global, EvaluateTaskConfig.defaultForceGarbageCollection, extracted, structure)
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/EvaluateTask.scala:216]: Can it be scoped to the root task so it could be overridden at the task level? Not sure if that's useful.

File: main/src/main/scala/sbt/EvaluateTask.scala [hunk 2]
```diff
@@ -301,8 +317,21 @@ object EvaluateTask
 		val log = state.log
 		log.debug("Running task... Cancel: " + config.cancelStrategy + ", check cycles: " + config.checkCycles)
 		val tags = tagged[Task[_]](_.info get tagsKey getOrElse Map.empty, Tags.predicate(config.restrictions))
-		val (service, shutdown) = completionService[Task[_], Completed](tags, (s: String) => log.warn(s))
-
+		val (service, shutdownThreads) = completionService[Task[_], Completed](tags, (s: String) => log.warn(s))
+
+		def shutdown(): Unit = {
+		  // First ensure that all threads are stopped for task execution.
+		  shutdownThreads()
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/EvaluateTask.scala:324]: When did threads come into the picture? Is this part of the GC deal?

Comment (jsuereth) [inline main/src/main/scala/sbt/EvaluateTask.scala:324]: completionService is an Executor service.  They were always in the picture, just trying to name correctly what the "hook" returned does, so it's clear.

File: main/src/main/scala/sbt/EvaluateTask.scala (hunk 1 above)
Comment (jsuereth) [inline main/src/main/scala/sbt/EvaluateTask.scala:216]: No.  There can be multiple roots as of sbt 0.13.2 _and_ you're not guaranteed to have a key relating to the task you run.  

Also, I don't think it's particularly useful, but a good suggestion :)

**Comment by eed3si9n** [comment]
LGTM

File: main/src/main/scala/sbt/EvaluateTask.scala [hunk 3]
```diff
@@ -301,8 +317,21 @@ object EvaluateTask
...
+		  // Now we run the gc cleanup to force finalizers to clear out file handles (yay GC!)
+		  if(config.forceGarbageCollection) {
+		  	// Force the detection of finalizers for scala.reflect weakhashsets
+ 			System.gc()
+ 			// Force finalizers to run.
+ 			System.runFinalization()
+ 			// Force actually cleaning the weak hash maps.
+ 			System.gc()
```
Comment (viktorklang) [inline main/src/main/scala/sbt/EvaluateTask.scala:332]: Just FYI: All of these are advisory and are no-ops on some JVMs.
