### PR TITLE
Overhaul terminal io

### LINKED ISSUE #5047: [1.3.0] file watch is failing; java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: .sbt/swoval-jni/6351939062664717054-libswoval-files0.dylib
## steps
sbt version: *1.3.0*
macOS 10.14.6
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Running file watch (`~`) with setting relative path to `-Dsbt.global.base`

I often use this launcher and set path by using `-sbt-dir`
https://github.com/sbt/sbt-launcher-package

## problem

cannot use file watch...

## expectation

We could set relative path to `sbt.global.base`.

## notes

Works in SBT 1.2.8

repro: https://github.com/yamachu/ScalaFunctions/tree/repro-watch-fail

```
# ~/Projects/github.com/yamachu/ScalaFunctions $ [repro-watch-fail]
sbt
[info] Loading settings for project global-plugins from ensime.sbt ...
[info] Loading global plugins from /Users/yamachu/.sbt/1.0/plugins
[info] Loading settings for project scalafunctions-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to my-awesome-function (in build file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/)
[info] Welcome to sbt 1.3.0.
[info] Here are some highlights of this release:
[info]   - Coursier: new default library management using https://get-coursier.io
[info]   - Super shell: displays actively running tasks
[info]   - Turbo mode: makes `test` and `run` faster in interactive sessions. Try it by running `set ThisBuild / turbo := true`.
[info] See https://www.lightbend.com/blog/sbt-1.3.0-release for full release notes.
[info] Hide the banner for this release by running `skipBanner`.
[info] sbt server started at local:///Users/yamachu/.sbt/1.0/server/b743c6d9ff742d678d4a/sock
sbt:my-awesome-function> about
[info] This is sbt 1.3.0
[info] The current project is ProjectRef(uri("file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/"), "root") 0.1-SNAPSHOT
[info] The current project is built against Scala 2.12.8
[info] Available Plugins
[info]  - com.timushev.sbt.updates.UpdatesPlugin
[info]  - org.ensime.EnsimeCoursierPlugin
[info]  - org.ensime.EnsimeExtrasPlugin
[info]  - org.ensime.EnsimePlugin
[info]  - org.portablescala.sbtplatformdeps.PlatformDepsPlugin
[info]  - org.scalafmt.sbt.ScalafmtPlugin
[info]  - org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin
[info]  - org.scalajs.sbtplugin.ScalaJSJUnitPlugin
[info]  - org.scalajs.sbtplugin.ScalaJSPlugin
[info]  - org.scalajs.sbtplugin.internal.ScalaJSGlobalPlugin
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info]  - sbt.plugins.SemanticdbPlugin
[info]  - sbtassembly.AssemblyPlugin
[info]  - sbtcrossproject.CrossPlugin
[info]  - scalajscrossproject.ScalaJSCrossPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.8
sbt:my-awesome-function> 
```

```
# ~/Projects/github.com/yamachu/ScalaFunctions $ [repro-watch-fail]
make sample-watch
sbt "printSbtDir; ~assembly"
[info] Loading settings for project global-plugins from ensime.sbt ...
[info] Loading global plugins from /Users/yamachu/.sbt/1.0/plugins
[info] Loading settings for project scalafunctions-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to my-awesome-function (in build file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/)
sbt.global.base: null
[success] Total time: 0 s, completed 2019/09/06 16:49:40
[info] Compiling 4 Scala sources to /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/target/scala-2.12/classes ...
[info] Strategy 'discard' was applied to a file (Run the task at debug level to see details)
[info] Assembly up to date: /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/target/scala-2.12/my-awesome-function-assembly-0.1-SNAPSHOT.jar
[success] Total time: 3 s, completed 2019/09/06 16:49:43
[info] 1. Monitoring source files for root/assembly...
[info]    Press <enter> to interrupt or '?' for more options.
q%                                                                                                                                                                                                                                            # ~/Projects/github.com/yamachu/ScalaFunctions $ [repro-watch-fail]
make sample-watch/set-sbt-dir/success
sbt -Dsbt.global.base=/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/.sbt "printSbtDir; ~assembly"
[info] Loading settings for project scalafunctions-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to my-awesome-function (in build file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/)
sbt.global.base: /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/.sbt
[success] Total time: 0 s, completed 2019/09/06 16:50:03
[info] Compiling 4 Scala sources to /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/target/scala-2.12/classes ...
[info] Strategy 'discard' was applied to a file (Run the task at debug level to see details)
[info] Assembly up to date: /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/target/scala-2.12/my-awesome-function-assembly-0.1-SNAPSHOT.jar
[success] Total time: 3 s, completed 2019/09/06 16:50:06
[info] 1. Monitoring source files for root/assembly...
[info]    Press <enter> to interrupt or '?' for more options.
q%                                                                                                                                                                                                                                            # ~/Projects/github.com/yamachu/ScalaFunctions $ [repro-watch-fail]
make sample-watch/set-sbt-dir/fail
sbt -Dsbt.global.base=".sbt" "printSbtDir; ~assembly"
[info] Loading settings for project scalafunctions-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to my-awesome-function (in build file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/)
sbt.global.base: .sbt
[success] Total time: 0 s, completed 2019/09/06 16:50:20
Couldn't load native library java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: .sbt/swoval-jni/3335314329300464049-libswoval-files0.dylib
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
gmake: *** [Makefile:31: sample-watch/set-sbt-dir/fail] Error 1
# ~/Projects/github.com/yamachu/ScalaFunctions $ [repro-watch-fail]
sbt -Dsbt.global.base=".sbt"
[info] Loading settings for project scalafunctions-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to my-awesome-function (in build file:/Users/yamachu/Projects/github.com/yamachu/ScalaFunctions/)
[info] Welcome to sbt 1.3.0.
[info] Here are some highlights of this release:
[info]   - Coursier: new default library management using https://get-coursier.io
[info]   - Super shell: displays actively running tasks
[info]   - Turbo mode: makes `test` and `run` faster in interactive sessions. Try it by running `set ThisBuild / turbo := true`.
[info] See https://www.lightbend.com/blog/sbt-1.3.0-release for full release notes.
[info] Hide the banner for this release by running `skipBanner`.
[info] sbt server started at local://.sbt/server/b743c6d9ff742d678d4a/sock
sbt:my-awesome-function> ~assembly
Couldn't load native library java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: .sbt/swoval-jni/6351939062664717054-libswoval-files0.dylib
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
sbt:my-awesome-function> last
[debug] > Exec(~assembly, Some(19e4366c-6259-4485-836f-acab232598c7), Some(CommandSource(console0)))
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[error] java.lang.ExceptionInInitializerError
[error] 	at com.swoval.files.apple.FileEventMonitorImpl.<clinit>(FileEventMonitors.java:130)
[error] 	at com.swoval.files.apple.FileEventMonitors.get(FileEventMonitors.java:47)
[error] 	at com.swoval.files.ApplePathWatcher.<init>(ApplePathWatcher.java:258)
[error] 	at com.swoval.files.ApplePathWatcher.<init>(ApplePathWatcher.java:194)
[error] 	at com.swoval.files.ApplePathWatchers.get(ApplePathWatcher.java:331)
[error] 	at com.swoval.files.PathWatchers.get(PathWatchers.java:84)
[error] 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:64)
[error] 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:32)
[error] 	at sbt.internal.nio.FileTreeRepositoryImpl.<init>(FileTreeRepositoryImpl.scala:46)
[error] 	at sbt.internal.nio.FileTreeRepository$.default(FileTreeRepository.scala:40)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$1(Continuous.scala:328)
[error] 	at sbt.internal.Continuous$.withCharBufferedStdIn(Continuous.scala:312)
[error] 	at sbt.internal.Continuous$.runToTermination(Continuous.scala:321)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:108)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error] 	at sbt.Command$.process(Command.scala:187)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:185)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:218)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:142)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:133)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:36)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:132)
[error] 	at sbt.xMain$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:46)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: .sbt/swoval-jni/6351939062664717054-libswoval-files0.dylib
[error] 	at java.lang.Runtime.load0(Runtime.java:806)
[error] 	at java.lang.System.load(System.java:1086)
[error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:140)
[error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:174)
[error] 	at com.swoval.files.apple.FileEventMonitorImpl.<clinit>(FileEventMonitors.java:127)
[error] 	at com.swoval.files.apple.FileEventMonitors.get(FileEventMonitors.java:47)
[error] 	at com.swoval.files.ApplePathWatcher.<init>(ApplePathWatcher.java:258)
[error] 	at com.swoval.files.ApplePathWatcher.<init>(ApplePathWatcher.java:194)
[error] 	at com.swoval.files.ApplePathWatchers.get(ApplePathWatcher.java:331)
[error] 	at com.swoval.files.PathWatchers.get(PathWatchers.java:84)
[error] 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:64)
[error] 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:32)
[error] 	at sbt.internal.nio.FileTreeRepositoryImpl.<init>(FileTreeRepositoryImpl.scala:46)
[error] 	at sbt.internal.nio.FileTreeRepository$.default(FileTreeRepository.scala:40)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$1(Continuous.scala:328)
[error] 	at sbt.internal.Continuous$.withCharBufferedStdIn(Continuous.scala:312)
[error] 	at sbt.internal.Continuous$.runToTermination(Continuous.scala:321)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:108)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error] 	at sbt.Command$.process(Command.scala:187)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:185)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:218)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:142)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:133)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:36)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:132)
[error] 	at sbt.xMain$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:46)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
[debug] > Exec(shell, None, None)
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
sbt:my-awesome-function>
```

### LINKED ISSUE #5162: "Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?" prompt in CI environment
## steps
Throw exception in a build file, like sbt/sbt-launcher-package.

## problem

It would prompt for input, which could hang in the background.

## expectation

When there is no associated console, we should just fail.

## notes

This came up during the sbt/sbt-launcher-package testing, but I am not fully sure if this is a general case for normal builds.

### LINKED ISSUE #5246: "Multiple main classes detected" prompt uses println, leads to corrupt output with supershell
See https://github.com/sbt/sbt/blob/964f7867b31c0765af0f59951541fcf1c130edf3/run/src/main/scala/sbt/SelectMainClass.scala#L23 (it seems like println should be banned in sbt to avoid this sort of things, or its output redirected somehow)

### PR DESCRIPTION
**Pull request by eatkins**
This PR makes a number of enhancements to terminal io. Because of how the changes stacked on top of each other, it both was difficult to split this into many smaller PRs. Every individual commit in the PR compiles and should likely pass scripted.

The two main changes are:
1. Adds a new `Terminal` class which is used to do things like switch the tty mode between canonical and raw mode and also access properties like the height and width of the terminal. 
2. Changes the global `java.lang.System.out` and `scala.Console.out` to go through a proxy. This enables us to make supershell work with `println`. It also allows us to make supershell work when output has been printed without a newline by reseting the cursor back to where the previous output left off.

The impact of item 2 can be seen in some recorded terminal sessions. First I made a simple project that ran a task that depended on 8 other tasks that each just print some random lines to System.out. Here is what it looks like with 1.3.5:
[asciicast](https://asciinema.org/a/bU4QN2jYdeQG10rP67sPiy7mD)
And here is what it looks like with these changes:
[asciicast](https://asciinema.org/a/GJ3oXZYRps2B2edWsc1c0hKqb)

The run task didn't really work with supershell before (https://github.com/sbt/sbt/issues/5246):
[asciicast](https://asciinema.org/a/zGPdHdKXwsT5AQHJ42PkgITWJ)
Now the cursor correctly moves back to the right place:
[asciicast](https://asciinema.org/a/AHp7zyxIWCYD8ia7EOkOSBkr5)
I also made it so that if there are fewer than 10 main classes that the user doesn't have to enter a newline to select the class.

I also made some improvements to `ConsoleChannel` and the `CommandExchange` that makes the output more sane when a client connects and runs commands. With 1.3.5, the output could get mixed with the shell prompt and the prompt wasn't restored after the command completed:
[asciicast](https://asciinema.org/a/UQ3grChhP44mOsIJWQXMMM3W5)
Now the output is saner and sbt logs what command is being invoked by the network client:
[asciicast](https://asciinema.org/a/UCJO4yA93S6EzrTQLoDHEWTdu)

Miscellaneous fixes:
* Clear the current line and the screen to the bottom in the shell prompt. This prevents stray supershell lines from ending up stuck at the bottom.
* We no longer poll System.in in `ConsoleChannel` and block instead. As a result the cpu utilization of sbt when idle drops from about 2% to 0% on my computer. Input latency should also be slightly lower.
* In continuous, we stop trying to read from System.in if we read a -1 byte that indicates the channel has closed.

Fixes #5246  
I think should fix #5162

### CODE REVIEW

File: main-command/src/main/scala/sbt/internal/ConsoleChannel.scala [hunk 1]
```diff
@@ -23,7 +23,9 @@ private[sbt] final class ConsoleChannel(val name: String) extends CommandChannel
     val history = (s get historyPath) getOrElse (new File(s.baseDir, ".history")).some
     val prompt = (s get shellPrompt) match {
       case Some(pf) => pf(s)
-      case None     => "> "
+      case None =>
+        def ansi(s: String): String = if (ConsoleAppender.formatEnabledInEnv) s"$s" else ""
+        s"${ansi(ConsoleAppender.DeleteLine)}> ${ansi(ConsoleAppender.clearScreen(0))}"
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/ConsoleChannel.scala]: Similar to `ConsoleAppender.DeleteLine`, it might be helpful to define `ConsoleAppender.ClearAfterCursor` instead of relying on the knowledge that `0` [encodes](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-modification):

> - 0 erases from the current cursor position (inclusive) to the end of the line/display

File: internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+      terminal.setEchoEnabled(previous)
+      terminalLock.unlock()
+    }
+  }
+
+  /**
+   * Runs a thunk ensuring that the terminal is in canonical mode:
+   * [[https://www.gnu.org/software/libc/manual/html_node/Canonical-or-Not.html Canonical or Not]].
+   * Most of the time sbt should be in canonical mode except when it is explicitly set to raw mode
+   * via [[withRawSystemIn]].
```
Comment (eed3si9n) [inline internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala:154]:
```suggestion
   * sbt should go back to canonical mode before giving the controls to `run` or `sbt new`.
```

File: main/src/main/scala/sbt/internal/Continuous.scala [hunk 3]
```diff
@@ -288,10 +288,13 @@ private[sbt] object Continuous extends DeprecatedContinuous {
           override def run(): Unit = {
             try {
               if (!closed.get()) {
-                buffer.add(wrapped.read())
+                wrapped.read() match {
+                  case -1 => closed.set(true)
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/Continuous.scala:289]: :+1:

File: internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+  def systemInIsAttached: Boolean = attached.get
+
+  /**
+   * Provides a wrapper around System.in. The wrapped stream in will check if the terminal is attached
+   * in available and read. If a read returns -1, it will mark System.in as unattached so that
+   * it can be detected by [[systemInIsAttached]].
+   *
+   * @return the wrapped InputStream
+   */
+  private[sbt] def wrappedSystemIn: InputStream = WrappedSystemIn
```
Comment (eed3si9n) [inline internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala:112]: Would it make sense to hide this from the rest of sbt code as well? And provide something like `def read: Char`?

File: main/src/main/scala/sbt/Main.scala [hunk 5]
```diff
@@ -763,22 +763,24 @@ object BuiltinCommands {
...
       if (Project.isProjectLoaded(s)) "using previously loaded project" else "no project loaded"
 
-    result match {
-      case ""                     => retry
-      case _ if matches("retry")  => retry
-      case _ if matches(Quit)     => s.exit(ok = false)
-      case _ if matches("ignore") => s.log.warn(s"Ignoring load failure: $ignoreMsg."); s
-      case _ if matches("last")   => LastCommand :: loadProjectCommand(LoadFailed, loadArg) :: s
-      case _                      => println("Invalid response."); doLoadFailed(s, loadArg)
+    result.toChar match {
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala:777]: Not sure how many people have caps lock on but the original code had ` .toLowerCase(Locale.ENGLISH)`

File: main/src/main/scala/sbt/Defaults.scala [hunk 6]
```diff
@@ -1424,12 +1432,16 @@ object Defaults extends BuildCommon {
...
+      logWarning: Boolean
+  ): Option[String] = {
     classes match {
-      case multiple if multiple.size > 1 =>
-        logger.warn(
-          "Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list"
-        )
+      case multiple if multiple.size > 1 && logWarning =>
+        val msg =
+          "Multiple main classes detected. Run 'show discoveredMainClasses' to see the list."
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala]:
```suggestion
          "multiple main classes detected: run 'show discoveredMainClasses' to see the list"
```

This is purely cosmetic but I'd like to unify towards lowercase for warnings (already the case in most Scala compiler errors etc)

File: run/src/main/scala/sbt/SelectMainClass.scala [hunk 7]
```diff
@@ -19,12 +20,14 @@ object SelectMainClass {
       case Nil         => None
       case head :: Nil => Some(head)
       case multiple =>
-        promptIfMultipleChoices flatMap { prompt =>
-          println("\nMultiple main classes detected, select one to run:\n")
-          for ((className, index) <- multiple.zipWithIndex)
-            println(" [" + (index + 1) + "] " + className)
+        promptIfMultipleChoices.flatMap { prompt =>
+          val header = "\nMultiple main classes detected. Select one to run:\n"
```
Comment (eed3si9n) [inline run/src/main/scala/sbt/SelectMainClass.scala:24]:
```suggestion
          val header = "\nmultiple main classes detected: select one to run:\n"
```

File: run/src/main/scala/sbt/SelectMainClass.scala [hunk 8]
```diff
@@ -19,12 +20,14 @@ object SelectMainClass {
...
+          val classes = multiple.zipWithIndex
+            .map { case (className, index) => s" [${index + 1}] $className" }
+            .mkString("\n")
+          println(ConsoleAppender.clearScreen(0) + header + classes)
```
Comment (eed3si9n) [inline run/src/main/scala/sbt/SelectMainClass.scala]: `ConsoleAppender.ClearAfterCursor` here too.

File: main-command/src/main/scala/sbt/internal/ConsoleChannel.scala [hunk 9]
```diff
@@ -23,13 +25,19 @@ private[sbt] final class ConsoleChannel(val name: String) extends CommandChannel
...
-        case None      => append(Exec("exit", Some(Exec.newExecId), Some(CommandSource(name))))
+      try {
+        reader.readLine(prompt) match {
+          case Some(cmd) => append(Exec(cmd, Some(Exec.newExecId), Some(CommandSource(name))))
+          case None =>
+            println("") // Prevents server shutdown log lines from appearing on the prompt line
+            append(Exec("exit", Some(Exec.newExecId), Some(CommandSource(name))))
+        }
+      } catch {
+        case _: ClosedChannelException =>
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/ConsoleChannel.scala:50]: What would be a situation where the input would close itself?

File: main/src/main/scala/sbt/Main.scala [hunk 10]
```diff
@@ -898,6 +898,9 @@ object BuiltinCommands {
       .getOpt(Keys.minForcegcInterval)
       .getOrElse(GCUtil.defaultMinForcegcInterval)
     val exec: Exec = exchange.blockUntilNextExec(minGCInterval, s1.globalLogging.full)
+    if (exec.source.fold(true)(_.channelName != "console0")) {
+      s1.log.info(s"Running remote command: ${exec.commandLine}")
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala]:
```suggestion
      s1.log.info(s"received: ${exec.commandLine}")
```

File: main/src/main/scala/sbt/internal/TaskProgress.scala [hunk 11]
```diff
@@ -83,41 +84,40 @@ private[sbt] final class TaskProgress(log: ManagedLogger)
...
     }
   }
+  private[this] def appendProgress(event: ProgressEvent): Unit = {
+    import sbt.internal.util.codec.JsonProtocol._
+    log.logEvent(Level.Info, event)
+  }
   private[this] def active: Vector[Task[_]] = activeTasks.toVector.filterNot(Def.isDummy)
+  private[this] def activeExceedingThreshold: Vector[(Task[_], Long)] = active.flatMap { task =>
+    val elapsed = timings.get(task).currentElapsedMicros
+    if (elapsed.micros > threshold) Some[(Task[_], Long)](task -> elapsed) else None
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/TaskProgress.scala:104]: 👍. Initially this looked confusing until I realized that the comparison of microsecond and millisecond is done using Duration.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
some comments here and there, but overall I think looks ok?

File: main/src/main/scala/sbt/Main.scala (hunk 5 above)
Comment (eatkins) [reply main/src/main/scala/sbt/Main.scala:777]: Yeah. I should make that change.

File: main-command/src/main/scala/sbt/internal/ConsoleChannel.scala (hunk 1 above)
Comment (eatkins) [reply main-command/src/main/scala/sbt/internal/ConsoleChannel.scala]: That's a good idea.

File: internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala (hunk 4 above)
Comment (eatkins) [reply internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala:112]: Possibly. `ConsoleChannel` uses `Terminal.throwOnClosedSystemIn` rather than wrapped system in but I think generally we want wrappedSystemIn.

File: main-command/src/main/scala/sbt/internal/ConsoleChannel.scala (hunk 9 above)
Comment (eatkins) [reply main-command/src/main/scala/sbt/internal/ConsoleChannel.scala:50]: This is the purpose of `Terminal.throwOnClosedSystemIn`. The problem is that `ConsoleReader.readLine` returns null both if the user inputs EOF via <ctrl+d> and if the call to read returns -1. In that latter case, we don't want to shutdown sbt because we may be running scripted or a server session. Before the wrapped system in overrode read to poll until `System.in.available > 0`. This kept JLine from returning null when `System.in` wasn't attached.

File: main/src/main/scala/sbt/Defaults.scala (hunk 6 above)
Comment (eatkins) [reply main/src/main/scala/sbt/Defaults.scala]: Sure.

File: internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala (hunk 2 above)
Comment (eatkins) [reply internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala:154]: Not sure I agree with this suggestion. sbt should only ever _not_ be in canonical mode when in a `Terminal.withRawSystemIn` block so the onus should not actually be on the caller to go back to canonical mode.

File: main/src/main/scala/sbt/Main.scala (hunk 5 above)
Comment (eatkins) [reply main/src/main/scala/sbt/Main.scala:777]: Done via explicit character matching rather than a call `toLowerCase`.

File: main-command/src/main/scala/sbt/internal/ConsoleChannel.scala (hunk 1 above)
Comment (eatkins) [reply main-command/src/main/scala/sbt/internal/ConsoleChannel.scala]: I called it ClearScreenAfterCursor but otherwise applied this suggestion.

File: run/src/main/scala/sbt/SelectMainClass.scala (hunk 7 above)
Comment (eatkins) [reply run/src/main/scala/sbt/SelectMainClass.scala:24]: I am ok with the change above, but I disagree with this change. This is a prompt, not a warning message. The double colons are a poor way to express multiple sentences. It also is not at all inconsistent with sbt to output complete sentences or lines starting with a capital letter. For example:
```
[info] 2. Monitoring source files for sbtRoot/compile...
[info]    Press <enter> to interrupt or '?' for more options.
[info] Build triggered by /Users/ethanatkins/work/oss/sbt/sbt/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala. Running 'compile'.
[info] Formatting 1 Scala sources...
[info] Formatting 1 Scala sources...
[info] Formatting 1 Scala sources...
[info] Formatting 2 Scala sources...
[info] Compiling 2 Scala sources to /Users/ethanatkins/work/oss/sbt/sbt/main/target/scala-2.12/classes ...
[success] Total time: 7 s, completed May 1, 2020 1:02:55 PM
```

File: main/src/main/scala/sbt/Main.scala (hunk 10 above)
Comment (eatkins) [reply main/src/main/scala/sbt/Main.scala]: I don't mind changing Running to received, but I think it makes sense to emphasize that it was a remote command. I made the Running to received switch but left the 'remote command' portion.

**Comment by eatkins** [comment]
@eed3si9n I rebased this branch, made a number of the requested changes and added commentary about some wording issues where I have some different opinions.

**Comment by eed3si9n** [comment]
@eatkins Thanks for the update. I'll take a closer look.

File: main/src/main/scala/sbt/Main.scala [hunk 12]
```diff
@@ -900,7 +900,7 @@ object BuiltinCommands {
       .getOrElse(GCUtil.defaultMinForcegcInterval)
     val exec: Exec = exchange.blockUntilNextExec(minGCInterval, s1.globalLogging.full)
     if (exec.source.fold(true)(_.channelName != "console0")) {
-      s1.log.info(s"Running remote command: ${exec.commandLine}")
+      s1.log.info(s"received remote command: ${exec.commandLine}")
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala:903]: 👍

File: main/src/main/scala/sbt/Main.scala (hunk 10 above)
Comment (eed3si9n) [reply main/src/main/scala/sbt/Main.scala]: Cool. https://github.com/sbt/sbt/pull/5319/commits/73235d12e0dc4cea61996c4ff7d1ac27f75dd487

File: internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala [hunk 13]
```diff
@@ -101,6 +136,17 @@ object Terminal {
...
   }
 
+  /**
+   *
+   * @param f the thunk to run
+   * @tparam T the result type of the thunk
+   * @return the result of the thunk
+   */
+  private[sbt] def withStreams[T](f: => T): T =
+    if (System.getProperty("sbt.io.virtual", "true") == "true") {
```
Comment (eed3si9n) [inline internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala:146]: We should document this.

File: main/src/main/scala/sbt/Main.scala [hunk 14]
```diff
@@ -776,11 +776,11 @@ object BuiltinCommands {
 
     result.toChar match {
       case '\n' | '\r' => retry
-      case 'r'         => retry
-      case 'q'         => s.exit(ok = false)
-      case 'i'         => s.log.warn(s"Ignoring load failure: $ignoreMsg."); s
-      case 'l'         => LastCommand :: loadProjectCommand(LoadFailed, loadArg) :: s
-      case _           => println("Invalid response."); doLoadFailed(s, loadArg)
+      case 'r' | 'R'   => retry
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala:779]: 👍

**Review by eed3si9n — APPROVED** [review]
LGTM. Thanks for this contribution!
