### PR TITLE
 Fix unused nowarn in sbt plugins

### LINKED ISSUE #6430: `@nowarn annotation does not suppress any warnings` when compiling SBT plugins
## steps

Trying to build an SBT plugin with sbt 1.5.0, in our case [twinagle](https://github.com/soundcloud/twinagle/pull/224). 

## problem

We get `@nowarn annotation does not suppress any warnings` [errors](https://github.com/soundcloud/twinagle/pull/224/checks?check_run_id=2276625337#step:5:208) in the code that extends `AutoPlugin`.

## expectation

No warnings/errors are emitted.

## notes

Seems related to https://github.com/sbt/sbt/issues/6398

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #6430

### CODE REVIEW

File: main/src/main/scala/sbt/plugins/SbtPlugin.scala [hunk 1]
```diff
@@ -10,11 +10,14 @@ package plugins
...
+import sbt.SlashSyntax0._
+import sbt.librarymanagement.Configurations.Compile
 
 object SbtPlugin extends AutoPlugin {
   override def requires = ScriptedPlugin
 
   override lazy val projectSettings: Seq[Setting[_]] = Seq(
-    sbtPlugin := true
+    sbtPlugin := true,
+    Compile / scalacOptions += "-Wconf:cat=unused-nowarn:s"
```
Comment (mkurz) [inline main/src/main/scala/sbt/plugins/SbtPlugin.scala]: Isn't this too global? Wouldn't this silence also other "unused" warnings?

Comment (adpi2) [reply main/src/main/scala/sbt/plugins/SbtPlugin.scala]: This option does only silence the unused `@nowarn` warnings in the `SbtPlugin` projects.

```
@nowarn annotation does not suppress any warnings
```

It is not a perfect solution because it will silence your own unused `@nowarn` annotations. But it is very specific to sbt plugins and it is harmless.

A better solution would be to have scala/scala#9491 but it is only available in 2.13.

**Review by eed3si9n — COMMENTED** [review]
Thanks for the quick fix!

The fix LGTM but could you add fatal warning to some scripted plugin build as a test plz?

**Comment by adpi2** [comment]
Test added.

Also the option is only added if scalaVersion >= 2.12.13 because it was not available in 2.12.12.

So the solution in 2.12.12 is to upgrade to 2.12.13

**Review by eed3si9n — APPROVED** [review]
