### PR TITLE
[2.x] Excluding artifacts without Scala version suffix

### LINKED ISSUE #7454: Cross-versioned excludes
Does this really work with sbt 1.9.7? For me it seems not...

I have a dependency:
```sbt
val atomRenderer = ("com.gu" %% "atom-renderer" % "1.2.0")
```
Now I want to exclude a dependency and it only works when appending `_2.13` to it, everything else fails:
```sbt
.exclude("com.typesafe.play", "twirl-api_2.13") // works

.exclude("com.typesafe.play", "twirl-api") // does NOT work

.excludeAll("com.typesafe.play" %% "twirl-api") // does NOT work
```

_Originally posted by @mkurz in https://github.com/sbt/librarymanagement/issues/88#issuecomment-1851554369_

### PR DESCRIPTION
**Pull request by seroperson**
Now it's possible to use:

```
.exclude("com.typesafe.play" %% "twirl-api")
```

Instead of:

```
.exclude("com.typesafe.play", "twirl-api_2.13")
```

It didn't work because `ExclusionRule` constructed by `organization` and `name` never had `crossVersion` set. 

Also: 

- Fixed handling `.excludeAll("com.typesafe.play" %% "twirl-api")`: previously it wasn't excluding artifacts in published xmls.
- Marked `.exclude(String, String)` as deprecated in favor of new syntax `.exclude(... %% ...)`.

Closes #7454

### CODE REVIEW

File: lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala [hunk 1]
```diff
@@ -152,8 +153,25 @@ private[librarymanagement] abstract class ModuleIDExtra {
...
+
+    exclude(
+      ExclusionRule().withOrganization(org).withName(name).withCrossVersion(exclusionCrossVersion)
+    )
+  }
+
+  /** Excludes the dependency from being introduced by this dependency during resolution. */
+  def exclude(rule: ExclusionRule): ModuleID = {
+    excludeAll(rule)
+  }
```
Comment (eed3si9n) [inline lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala]: Is this safe for libraries that needs to be published to a Maven repo? https://www.scala-sbt.org/1.x/docs/Library-Management.html#Exclude+Transitive+Dependencies reads

> The `excludeAll` method is more flexible, but because it cannot be represented in a `pom.xml`, it should only be used when a pom doesn’t need to be generated.

Comment (seroperson) [reply lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala]: Oh, yea, well, it's not. I changed this signature to be `exclude(OrganizationArtifactName)` to still be able to write the usual `exclude("..." %% "...")` but not to be able to set configurations and artifact names.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Could you add scripted test that either checks makePom or publishes to a local directory and use it please?

**Comment by seroperson** [comment]
> Could you add scripted test that either checks makePom or publishes to a local directory and use it please?

Well, yes, it was tricky to find, but there was one more place which ignored `ExclusionRule.crossVersion`.

**Comment by seroperson** [comment]
@eed3si9n would you mind review one more time?

**Comment by eed3si9n** [comment]
Sure. I'll try to grab this branch locally over the weekend and test it.

**Comment by seroperson** [comment]
@eed3si9n friendly reminder 🙂

File: lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala [hunk 2]
```diff
@@ -152,8 +154,25 @@ private[librarymanagement] abstract class ModuleIDExtra {
...
+    //
+    // Otherwise, inherit the parent module's cross-version behavior.
+    val exclusionCrossVersion =
+      if (CrossVersionUtil.endsWithCrossVersion(name, crossVersion)) Disabled()
+      else crossVersion
+
+    excludeAll(
+      ExclusionRule().withOrganization(org).withName(name).withCrossVersion(exclusionCrossVersion)
+    )
+  }
```
Comment (eed3si9n) [inline lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala]: If `exclude(org, name)` is already an alias for `excludeAll(...)`, I suggest we don't change the implementation, but instead deprecate this method in favor of `excludeAll(org %% name)` or the new variant `exclude(org %% name)`.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala (hunk 2 above)
Comment (seroperson) [reply lm-core/src/main/scala/sbt/librarymanagement/ModuleIDExtra.scala]: Done. I've removed all the backward-compatibility logic then.

**Review by eed3si9n — APPROVED** [review]
Thanks! Could you update the PR description as well plz?

**Comment by seroperson** [comment]
@eed3si9n done 🎉
