### PR TITLE
Fixes linter that detects missing .value

### LINKED ISSUE #4079: warn on value discard in build code
## steps
someone declares TaskKey[Unit] and tries to define it, but doesn't know about .value or accidentally omits it
```scala
lazy val npmBuildTask = taskKey[Unit]("Execute the npm build command to build the ui")
npmBuildTask := {
  Process("npm run build", file(appPath))
}
lazy val npmInstallTask = taskKey[Unit]("Execute the npm install command to build the ui")
npmInstallTask := {
  Process("npm install", file(appPath))
}
lazy val npmTask = taskKey[Unit]("execute all npm tasks")
npmTask := {
  npmInstallTask
  npmBuildTask
}
```

## problem
nothing happens

## expectation
useful error message or warning

## notes
i suggest enabling -Ywarn-value-discard for builds by default

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #4079

#3216 introduced a linter that checks against missing `.value`, but the tree only checked for `Ident`. This doesn't work because in reality the symbols of build.sbt are transformed to `$somehash.npmInstallTask` where `somehash` is the wrapper object we create. Similarly for the built-in keys, they are presented as `sbt.Keys.compile`.

With this change unused task will fail to load the build with the following message:

```
/sbt-4079/build.sbt:26: error: The key `compile` is not being invoked inside the task definition.

Problem: Keys missing `.value` are not initialized and their dependency is not registered.

Solution: Replace `compile` by `compile.value` or remove it if unused.

  compile
  ^
/sbt-4079/build.sbt:27: error: The key `npmInstallTask` is not being invoked inside the task definition.

Problem: Keys missing `.value` are not initialized and their dependency is not registered.

Solution: Replace `npmInstallTask` by `npmInstallTask.value` or remove it if unused.

  npmInstallTask
  ^
```

### CODE REVIEW

File: main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala [hunk 1]
```diff
@@ -57,7 +58,7 @@ abstract class BaseTaskLinterDSL extends LinterDSL {
       }
 
       @inline def isKey(tpe: Type): Boolean =
-        tpe <:< taskKeyType || tpe <:< settingKeyType || tpe <:< inputKeyType
+        tpe <:< initializeType || tpe <:< taskKeyType || tpe <:< settingKeyType || tpe <:< inputKeyType
```
Comment (dwijnand) [inline main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala]: this should simplify to just `tpe <:< initializeType` because keys are initializes

File: main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala [hunk 2]
```diff
@@ -66,6 +67,13 @@ abstract class BaseTaskLinterDSL extends LinterDSL {
         } else ()
       }
 
+      def detectAndErrorOnKeyMissingValue(s: Select): Unit = {
```
Comment (dwijnand) [inline main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala:67]: instead of overloading you could just make the other one take a tree

**Review by dwijnand — APPROVED** [review]
cool.

minor comments, but this can merge as is too

**Comment by OlegYch** [comment]
does it work for something like `(Compile / compile)` ?

**Comment by dwijnand** [comment]
yes, that's an Initialize too.

File: main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala (hunk 2 above)
Comment (eed3si9n) [reply main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala:67]: This code uses `Select#name`.

Comment (eed3si9n) [reply main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala:67]: I guess I can do pattern matching.

**Comment by eed3si9n** [comment]
> does it work for something like `(Compile / compile)` ?

Actually it won't as it stands, because it's only handling Ident and Select. We need Apply for that.

File: main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala (hunk 1 above)
Comment (eed3si9n) [reply main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala]: Good point. Let me try that.

File: main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala (hunk 2 above)
Comment (dwijnand) [reply main-settings/src/main/scala/sbt/std/TaskLinterDSL.scala:67]: oh, for some reason I thought all trees had name??

**Comment by dwijnand** [comment]
Would probably be best for this to not miss the 1.2.0-RC1 train.

**Comment by eed3si9n** [comment]
Added a commit.

**Review by dwijnand — APPROVED** [review]
LGTM, pending Travis CI.
