### PR TITLE
[2.x] fix: Print server stderr on startup failure

### LINKED ISSUE #8812: [2.x] "server was not detected" (server should print error)
## steps

Use JDK 8.

```bash
$ touch build.sbt
$ sbt -Dsbt.version=2.0.0-RC9
```

## problem

```bash
$ sbt -Dsbt.version=2.0.0-RC9
[info] server was not detected. starting an instance
[error] failed to connect to server
```

This is somewhat confusing error since it hides the server error.

## expectation

When the server fails to start up, it should print out the error message on stderr, similar to what we'd get if we passed `--server` flag:

```scala
$ sbt -Dsbt.version=2.0.0-RC9 --server
java.lang.UnsupportedClassVersionError: scala/Option has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at xsbt.boot.Pre$.classMissing$1(Pre.scala:72)
	at xsbt.boot.Pre$.getMissing$$anonfun$1(Pre.scala:74)
	at scala.collection.immutable.List.filter(List.scala:516)
	at xsbt.boot.Pre$.getMissing(Pre.scala:74)
	at xsbt.boot.Launch.checkLoader(Launch.scala:258)
	at xsbt.boot.Launch.provider$1(Launch.scala:391)
	at xsbt.boot.Launch.getScalaProvider0$$anonfun$2(Launch.scala:393)
	at scala.Option.flatMap(Option.scala:283)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getScalaProvider0(Launch.scala:392)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:374)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:374)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
	at xsbt.boot.Locks$.apply0(Locks.scala:45)
	at xsbt.boot.Locks$.apply(Locks.scala:36)
	at xsbt.boot.Launch.locked(Launch.scala:365)
	at xsbt.boot.Launch.getScalaProvider(Launch.scala:374)
	at xsbt.boot.Launch.$init$$$anonfun$3(Launch.scala:208)
	at xsbt.boot.Cache.newEntry(Cache.scala:19)
	at xsbt.boot.Cache.getFromReference(Cache.scala:15)
	at xsbt.boot.Cache.apply(Cache.scala:13)
	at xsbt.boot.Launch.getScala(Launch.scala:191)
	at xsbt.boot.Launch.getScala(Launch.scala:189)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:343)
	at xsbt.boot.Launch$$anon$1.call(Launch.scala:282)
	at xsbt.boot.Launch$$anon$1.call(Launch.scala:282)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:100)
	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock.withFileLock$$anonfun$1(Locks.scala:103)
	at xsbt.boot.Using$.withResource(Using.scala:14)
	at xsbt.boot.Using$.apply(Using.scala:11)
	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:103)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:64)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:55)
	at xsbt.boot.Locks$.apply0(Locks.scala:45)
	at xsbt.boot.Locks$.apply(Locks.scala:36)
	at xsbt.boot.Launch.locked(Launch.scala:365)
	at xsbt.boot.Launch.getAppProvider(Launch.scala:282)
	at xsbt.boot.Launch.app(Launch.scala:194)
	at xsbt.boot.Launch.app(Launch.scala:192)
	at xsbt.boot.Launch$.run(Launch.scala:124)
	at xsbt.boot.Launch$.apply$$anonfun$1(Launch.scala:43)
	at xsbt.boot.Launch$.launch(Launch.scala:142)
	at xsbt.boot.Launch$.apply(Launch.scala:43)
	at xsbt.boot.Launch$.apply(Launch.scala:24)
	at xsbt.boot.Boot$.runImpl(Boot.scala:73)
	at xsbt.boot.Boot$.run(Boot.scala:69)
	at xsbt.boot.Boot$.main(Boot.scala:23)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedClassVersionError: scala/Option has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

### PR DESCRIPTION
**Pull request by eureka0928**
Fixes #8812

## Summary
When the sbt server fails to start, print the actual error instead of only showing "failed to connect to server".

## Problem
When the server process fails during auto-start (e.g. wrong JDK version producing `UnsupportedClassVersionError`), the client only prints:
```
[error] failed to connect to server
```
This hides the real cause. The `--server` flag shows the error because it uses `inheritIO()`, but the auto-start path redirects stderr to `/dev/null` (added in #8442 to prevent Linux pipe buffer deadlocks).

## Solution
Redirect server stderr to a temp file instead of `/dev/null`. If the server fails to start (portfile never appears), read and print the temp file contents before throwing `ServerFailedException`. This preserves the #8442 fix (writing to a file avoids pipe buffer deadlocks) while capturing startup errors for diagnostics.

The temp file is cleaned up eagerly on both success and failure paths, with `deleteOnExit()` as a safety net.

## Changes
- `main-command/.../NetworkClient.scala`
  - Redirect server stderr to a temp file instead of `/dev/null`
  - On startup failure, read and print the temp file before throwing `ServerFailedException`
  - Delete the temp file eagerly after use (both success and failure paths)

### CODE REVIEW

**Comment by fury0928** [comment]
@eed3si9n Could you review this when you get a chance? This is a small fix for #8812 — redirects server stderr to a temp file instead of /dev/null so startup errors are visible to the user.

File: main-command/src/main/scala/sbt/internal/client/NetworkClient.scala [hunk 1]
```diff
@@ -540,7 +545,22 @@ class NetworkClient(
...
     }
-    if (!portfile.exists()) throw new ServerFailedException
+    if (!portfile.exists()) {
+      // Print captured server stderr so users can see why the server failed to start
+      for (errFile <- serverStderrFile) {
+        try {
+          val bytes = Files.readAllBytes(errFile.toPath)
+          if (bytes.nonEmpty) {
+            errorStream.write(bytes)
+            errorStream.flush()
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/internal/client/NetworkClient.scala:555]: Nice. Do you have an example output of manual testing?

Comment (fury0928) [reply main-command/src/main/scala/sbt/internal/client/NetworkClient.scala:555]: Here's the manual test demonstrating the behavior change. Using `sbt-launch.jar` under JDK 8 to simulate the server subprocess failing:

**Before (stderr → `/dev/null`):**
```
$ java8 -jar sbt-launch.jar --server 2>/dev/null
$ echo $?
1
# User sees: nothing
```

**After (stderr → temp file, then printed on failure):**
```
$ java8 -jar sbt-launch.jar --server 2>captured.log
$ echo $?
1
$ cat captured.log
java.lang.UnsupportedClassVersionError: scala/Option has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	...
[error] [launcher] error during sbt launcher: java.lang.UnsupportedClassVersionError: scala/Option has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This is exactly what the fix does inside `NetworkClient`: redirects the server process stderr to a temp file instead of `/dev/null`, then reads and prints it when the portfile never appears.

Note: the actual end-to-end test with `sbtn` auto-starting a server requires rebuilding the native image, but the mechanism is identical — `ProcessBuilder.redirectError(tempFile)` instead of `redirectError(nullFile)`.

**Review by eed3si9n — APPROVED** [review]
