### PR TITLE
[2.x] test: Add test for sbt --client startup time

### LINKED ISSUE #6485: Test `sbt --client` startup
Ref https://github.com/sbt/sbt/issues/5980
Ref https://github.com/sbt/sbt/pull/6483

## steps

```bash
sbt -v --client compile
sbt -v --client compile
```

## expectation

To prevent regression of the startup time, we should probably measure it, and cap it at 200ms?

_Originally posted by @vegerot in https://github.com/sbt/sbt/pull/6483#discussion_r624092750_

### PR DESCRIPTION
**Pull request by calm329**
## Summary
- Add integration test to measure `sbt --client` startup time and prevent performance regressions
- Test runs 5 iterations after warmup and asserts average stays under 2000ms
- Skipped on Windows and MacOS where sbtn behavior differs

Fixes #6485

## Test plan
- [x] Run `launcherPackageIntegrationTest/test` - all tests pass
- [x] Verify startup times are printed and within threshold

### CODE REVIEW

**Comment by calm329** [comment]
@eed3si9n Could you please review my pr?

**Review by eed3si9n — APPROVED** [review]
Looks great! Thanks!

File: launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala [hunk 1]
```diff
@@ -138,4 +138,47 @@ object ExtendedRunnerTest extends BasicTestSuite:
     }
     ()
   }
+
+  // Test for issue #6485: Test `sbt --client` startup
+  // https://github.com/sbt/sbt/issues/6485
+  test("sbt --client startup time") {
+    if (isWindows || isMac) {
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala:145]: This is a commentary, not a change request, but if it takes 5s on macOS I have a feeling that sbtn is somehow not working well.

Comment (calm329) [reply launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala:145]: I think I found the root cause - `InetAddress.getLocalHost.getHostName` in `JUnitXmlTestsListener` takes ~5 seconds on macOS CI with misconfigured hostnames, and it's being called per-instance rather than cached.

  Would you be okay with caching the hostname at the companion object level so it's only resolved once per JVM?

Comment (eed3si9n) [reply launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala:145]: Let me file this as a separate bug.

Comment (eed3si9n) [reply launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala:145]: https://github.com/sbt/sbt/issues/8601
