### PR TITLE
[2.x] fix: Fixes the handling of special characters in dot files

### LINKED ISSUE #7289: loadConfigFile() does not properly evaluate properties with characters subject to shell expansion
## steps
Using sbt 1.9.0 installed via Coursier 
Tested on MacOS 13.2.1 using zsh 5.8.1 and bash 5.2.15 :
```bash
$ echo "-Dhttp.nonProxyHosts=this.property|contains.pipes|and.other.elements|subject.to.shell.expansion" > .jvmopts
$ sbt -d sbtVersion                                                                                       
.Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt: line 703: subject.to.shell.expansion: command not found
.Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt: line 703: and.other.elements: command not found
./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt: line 703: contains.pipes: command not found
[addSbt] arg = '-debug'
[residual] arg = 'sbtVersion'
[residual] arg = 'sbtVersion'
[sbt_options] declare -a sbt_options='()'
[process_args] java_version = '20'
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
[addJava] arg = '-Dsbt.script=./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt'
[copyRt] java9_rt = '.sbt/1.0/java9-rt-ext-homebrew_20/rt.jar'
[addJava] arg = '-Dscala.ext.dirs=.sbt/1.0/java9-rt-ext-homebrew_20'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt
-Dscala.ext.dirs=.sbt/1.0/java9-rt-ext-homebrew_20
-jar
./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt-launch.jar
-debug
sbtVersion
```

## problem

Some Java properties, such as `http.nonProxyHosts`, use the pipe character to separate items in a list (see https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html ). When loadConfigFiles() calls `eval` on such a property, the pipe characters are interpreted by the shell as commands, which results in error messages and the property not being included when invoking Java.

## expectation

sbt should properly handle lines in config files that contain characters subject to shell expansion (|, *, etc.)

## notes
If the offending characters are single-quoted, the property is interpreted correctly:

```bash
$ echo "-Dhttp.nonProxyHosts=this.property'|'contains.pipes'|'and.other.elements'|'subject.to.shell.expansion" > .jvmopts
$ [addSbt] arg = '-debug'
[residual] arg = 'sbtVersion'
[residual] arg = 'sbtVersion'
[sbt_options] declare -a sbt_options='()'
[process_args] java_version = '20'
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
addJava] arg = '-Dsbt.script=./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt'
[copyRt] java9_rt = '.sbt/1.0/java9-rt-ext-homebrew_20/rt.jar'
[addJava] arg = '-Dscala.ext.dirs=.sbt/1.0/java9-rt-ext-homebrew_20'

# Executing command line:
java
-Dhttp.nonProxyHosts=this.property|contains.pipes|and.other.elements|subject.to.shell.expansion
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt
-Dscala.ext.dirs=.sbt/1.0/java9-rt-ext-homebrew_20
-jar
./Coursier/arc/https/github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.zip/sbt/bin/sbt-launch.jar
-debug
sbtVersion
```

### PR DESCRIPTION
**Pull request by circlecrystalin**
### Handle special characters in config files safely

Replaces `eval echo $line` with `printf '%s\n' "$line"` in `loadConfigFile()` to prevent shell expansion of special characters like `|`, `*`, `&` in `.jvmopts` and `.sbtopts` files.

**Problem:**
Properties with pipes (e.g., `-Dhttp.nonProxyHosts=host1|host2`) caused "command not found" errors due to shell expansion.

**Solution:**
Use `printf` with quoted variable to output lines literally without shell interpretation.

**Testing:**
✅ Verified with pipes, wildcards, ampersands - all handled correctly

Fixes #7289

---

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=5625555

### CODE REVIEW

**Comment by circlecrystalin** [comment]
@eed3si9n Could you please review my first pr?

**Comment by eed3si9n** [comment]
Could you add a test in https://github.com/sbt/sbt/blob/develop/launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala please?

**Comment by circlecrystalin** [comment]
@eed3si9n I have added test. Please review again...

**Comment by circlecrystalin** [comment]
> Could you add a test in https://github.com/sbt/sbt/blob/develop/launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala please?


@eed3si9n I have added test. Please review again...

**Comment by circlecrystalin** [comment]
@eed3si9n Could you please give me tip to fix this issue?
image

I used this command to test.
```
./sbt -Dsbt.build.version=1.12.0 launcherPackageIntegrationTest/test
```

File: launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala [hunk 1]
```diff
@@ -194,4 +194,35 @@ object RunnerScriptTest extends verify.BasicTestSuite with ShellScriptUtil:
         s"Machine config should appear before project config. machineIndex=$machineIndex, projectIndex=$projectIndex"
       )
 
+  // Test for issue #7289: Special characters in .jvmopts should not cause shell expansion
+  testOutput(
+    "sbt with special characters in .jvmopts (pipes, wildcards, ampersands)",
+    jvmoptsFileContents =
+      "-Dhttp.nonProxyHosts=host1|host2|host3\n-Dtest.wildcards=path/*/pattern\n-Dtest.ampersand=value&other"
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: I wonder if `http.nonProxyHost` is interpreted, and crashing on Windows? Maybe try something like `test.abc`?

Comment (circlecrystalin) [reply launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: I just changed, could you please approve?

**Comment by circlecrystalin** [comment]
@eed3si9n why did this test fail? I think, maybe we should restart testing..
https://github.com/sbt/sbt/actions/runs/21077982060/job/60626757698?pr=8558

**Comment by circlecrystalin** [comment]
@eed3si9n I have fixed, could you please test again?

File: launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala [hunk 2]
```diff
@@ -194,4 +194,36 @@ object RunnerScriptTest extends verify.BasicTestSuite with ShellScriptUtil:
         s"Machine config should appear before project config. machineIndex=$machineIndex, projectIndex=$projectIndex"
       )
 
+  // Test for issue #7289: Special characters in .jvmopts should not cause shell expansion
+  testOutput(
+    "sbt with special characters in .jvmopts (pipes, wildcards, ampersands)",
+    jvmoptsFileContents =
+      "-Dtest.pipes=host1|host2|host3\n-Dtest.wildcards=path/*/pattern\n-Dtest.ampersand=value&other"
+  )("-v"): (out: List[String]) =>
+    if (isWindows) cancel("Test not supported on Windows without sbt.bat fix")
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: `else` is missing here. See the above test for example, line 178 etc is indented.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala (hunk 2 above)
Comment (circlecrystalin) [reply launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: @eed3si9n I have added `else`. Please take a look.

**Comment by circlecrystalin** [comment]
@eed3si9n Could you please take a look again?

File: launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala [hunk 3]
```diff
@@ -194,4 +194,37 @@ object RunnerScriptTest extends verify.BasicTestSuite with ShellScriptUtil:
...
+    // Verify no shell errors occurred (no "command not found" messages or "unexpected" errors)
+    val errorMessages = out.filter(line =>
+      line.contains("command not found") ||
+        line.contains("was unexpected at this time") ||
+        line.contains("syntax error")
+    )
+    assert(
+      errorMessages.isEmpty,
+      s"Should not have shell expansion errors, but found: ${errorMessages.mkString(", ")}"
+    )
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: These lines still need indentation.

Comment (circlecrystalin) [reply launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: Fixed — indentation corrected, thanks for the review.
