### PR TITLE
Fixes new command leaving behind target directory

### LINKED ISSUE #2835: sbt new leaves behind target litter
## steps

1. sbt new scala/scala-seed.g8

## problem

As pointed out by @dwijnand (https://github.com/sbt/sbt/pull/2780#discussion_r83523717) and @djspiewak (https://twitter.com/djspiewak/status/798976727095635968), new command leaves behind unwanted `target/` directory. 

## expectation

No mess.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #2835

This fixes `new` command creating `target` directory by moving the `target` to a staging directory in the command itself.

### CODE REVIEW

File: main/src/main/scala/sbt/TemplateCommand.scala [hunk 1]
```diff
@@ -26,12 +26,22 @@ private[sbt] object TemplateCommandUtil {
...
+    val extracted0 = (Project extract s0)
+    val globalBase = getGlobalBase(s0)
+    val stagingDirectory = getStagingDirectory(s0, globalBase).getCanonicalFile
+    val templateStage = stagingDirectory / "new"
+    // This moves the target directory to a staging directory
+    // https://github.com/sbt/sbt/issues/2835
+    val state = extracted0.appendWithSession(Seq(
+                                               Keys.target := templateStage
+                                             ),
+                                             s0)
```
Comment (dwijnand) [inline main/src/main/scala/sbt/TemplateCommand.scala:40]: that formatting.. 🙄

**Review by dwijnand — APPROVED** [review]
