### PR TITLE
[sbt 1.0] Fix logging + clean concurrency issue

### LINKED ISSUE #2156: Nondeterministic "No such file or directory" failure when cleaning project
I'm not sure if this is the right place to report this - I'd rather put this first on some forum, but since SBT does not have any mailing list for users, I'm forced to put it here.

I'm randomly getting this error when trying to build my project:

```
[default-tests-sbt] $ /usr/lib/jvm/java-8-oracle/bin/java -Dsbt.log.noformat=true -Xmx2G -jar /var/lib/jenkins/tools/org.jvnet.hudson.plugins.SbtPluginBuilder_SbtInstallation/SBT_default_launcher/bin/sbt-launch.jar clean test:clean buildUmp test
[info] Loading project definition from /var/lib/jenkins/workspace/default-tests-sbt/project
[info] Set current project to ump (in build file:/var/lib/jenkins/workspace/default-tests-sbt/)
Could not create file /var/lib/jenkins/workspace/default-tests-sbt/launcher/target/streams/$global/ivyConfiguration/$global/streams/outjava.io.IOException: No such file or directory
    at sbt.ErrorHandling$.translate(ErrorHandling.scala:10)
    at sbt.IO$.touch(IO.scala:143)
    at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:129)
    at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:113)
    at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:124)
    at sbt.std.TaskStreams$class.log(Streams.scala:56)
    at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:102)
    at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:102)
    at sbt.Classpaths$$anonfun$mkIvyConfiguration$1.apply(Defaults.scala:1533)
    at sbt.Classpaths$$anonfun$mkIvyConfiguration$1.apply(Defaults.scala:1532)
    at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
    at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1012)
    at sbt.IO$$anonfun$1.apply$mcZ$sp(IO.scala:143)
    at sbt.IO$$anonfun$1.apply(IO.scala:143)
    at sbt.IO$$anonfun$1.apply(IO.scala:143)
    at sbt.ErrorHandling$.translate(ErrorHandling.scala:10)
    at sbt.IO$.touch(IO.scala:143)
    at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:129)
    at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:113)
    at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:124)
    at sbt.std.TaskStreams$class.log(Streams.scala:56)
    at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:102)
    at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:102)
    at sbt.Classpaths$$anonfun$mkIvyConfiguration$1.apply(Defaults.scala:1533)
    at sbt.Classpaths$$anonfun$mkIvyConfiguration$1.apply(Defaults.scala:1532)
    at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
    at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (launcher/*:ivyConfiguration) Could not create file /var/lib/jenkins/workspace/default-tests-sbt/launcher/target/streams/$global/ivyConfiguration/$global/streams/outjava.io.IOException: No such file or directory
[error] Total time: 76 s, completed 2015-08-14 13:05:08
```

Can anyone direct me how do I even troubleshoot/debug this?

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #2156
Ref https://github.com/sbt/sbt/issues/2863

This is a workaround for `clean` and logging clashing when run concurrently on the same subproject. 

1. Assuming that removing a directory completes in 3s, this retries to call `IO.touch` 30 times with 100ms wait in between.
2. `clean` task is now tagged to `Tags.Clean`. There's now a concurrency rule that says tasks with the tags run as an exclusive group. (`a/clean` and `b/clean` can run together, but no other tasks)

### CODE REVIEW

File: tasks-standard/src/main/scala/sbt/std/Streams.scala [hunk 1]
```diff
@@ -155,13 +157,30 @@ object Streams {
...
+          catching(classOf[IOException]).either(run) match {
+            case Right(x) => x
+            case Left(e) =>
+              if (n <= 0) throw e
+              else {
+                Thread.sleep(100)
+                retry(n - 1)(run)
+              }
+          }
+        retry(30) { doMake }
```
Comment (eed3si9n) [inline tasks-standard/src/main/scala/sbt/std/Streams.scala]: https://travis-ci.org/sbt/sbt/jobs/221170415
```
[info] [error] Expected ID character (out-3) (out-1)
[info] [error] Not a valid command: macro-client (similar: client) (out-3) (out-1)
[info] [error] Expected project ID (out-3) (out-1)
[info] [error] Expected configuration (out-3) (out-1)
[info] [error] Expected ':' (if selecting a configuration) (out-3) (out-1)
[info] [error] Expected key (out-3) (out-1)
[info] [error] Not a valid key: macro-client (out-3) (out-1)
[info] [error] macro-client/compile (out-3) (out-1)
[info] [error]             ^ (out-3) (out-1)
[info] [error] (macroClient/*:projectDescriptors) Could not create file /tmp/sbt_bb6aa6bc/macro-arg-dep/macro-client/target/streams/$global/projectDescriptors/$global/streams/outjava.io.IOException: No such file or directory (out-88) (out-1)
[info] [error] Total time: 0 s, completed Apr 12, 2017 12:55:09 AM (out-3) (out-1)
[error] x source-dependencies / macro-arg-dep (out-1)
[error]    {line 10}  Command failed: clean failed (out-1)
```

It seems like retrying alone is not enough.

**Comment by jvican** [comment]
I really like the solution introduced in https://github.com/sbt/sbt/pull/3093/commits/be2265151339ee74d12c9289c353d13dc88bdc2f.

File: main/src/main/scala/sbt/Defaults.scala [hunk 2]
```diff
@@ -831,14 +836,22 @@ object Defaults extends BuildCommon {
...
-      val (dirs, files) = preserve.filter(_.exists).flatMap(_.allPaths.get).partition(_.isDirectory)
-      val mappings = files.zipWithIndex map { case (f, i) => (f, new File(temp, i.toHexString)) }
-      IO.move(mappings)
-      IO.delete(clean)
-      IO.createDirectories(dirs) // recreate empty directories
-      IO.move(mappings.map(_.swap))
+  /** Implements `cleanFiles` task. */
+  def cleanFilesTask: Initialize[Task[Vector[File]]] =
+    Def.task {
+      // performance reasons, only the direct items under `filesAndDirsToClean` are allowed to be preserved.
```
Comment (dwijnand) [inline main/src/main/scala/sbt/Defaults.scala]: (minor) I think this is now called "filesAndDirs"

File: tasks-standard/src/main/scala/sbt/std/Streams.scala (hunk 1 above)
Comment (dwijnand) [reply tasks-standard/src/main/scala/sbt/std/Streams.scala]: Now that we have the tag limiting can we drop some of the retry logic?

File: main/src/main/scala/sbt/Keys.scala [hunk 3]
```diff
@@ -162,8 +162,8 @@ object Keys {
 
   // Output paths
   val classDirectory = SettingKey[File]("class-directory", "Directory for compiled classes and copied resources.", AMinusSetting)
-  val cleanFiles = SettingKey[Seq[File]]("clean-files", "The files to recursively delete during a clean.", BSetting)
-  val cleanKeepFiles = SettingKey[Seq[File]]("clean-keep-files", "Files to keep during a clean.", CSetting)
+  val cleanFiles = TaskKey[Seq[File]]("clean-files", "The files to recursively delete during a clean.", BSetting)
```
Comment (dwijnand) [inline main/src/main/scala/sbt/Keys.scala:165]: We now have a criteria for setting vs task: make it a task makes it un-queryable in server mode. Ideally this would be a `SettingKey[PathFinder]` that we evaluate during clean. Should we change to that?

**Review by dwijnand — CHANGES_REQUESTED** [review]
Generally LGTM. 2 questions and 1 minor.

File: main/src/main/scala/sbt/Keys.scala (hunk 3 above)
Comment (jvican) [reply main/src/main/scala/sbt/Keys.scala:165]: That sounds like a good idea.

File: tasks-standard/src/main/scala/sbt/std/Streams.scala (hunk 1 above)
Comment (jvican) [reply tasks-standard/src/main/scala/sbt/std/Streams.scala]: Is it possible to remove all the retry logic and make clean run exclusively?

Comment (eed3si9n) [reply tasks-standard/src/main/scala/sbt/std/Streams.scala]: Basically I wasn't sure if `clean` is the only culprit of concurrency issue. But we can introduce one parameter at a time, and take this commit out and see how it goes.

File: main/src/main/scala/sbt/Keys.scala (hunk 3 above)
Comment (eed3si9n) [reply main/src/main/scala/sbt/Keys.scala:165]: In general setting should be mostly simple values, and behaviors and things that's based on disk and network should be tasks.
The list of exact thing that we are going to clean I think should be a task for both reasons:
1. Thing that needs deleting depends on the state of the disk.
2. If we try to let the `"streams"` directory survive, or do something like https://github.com/sbt/sbt/issues/106 (let the directory for classpath survive), it's really complicated to describe it in terms of a setting.

It's true that benefit of the setting is that becomes queryable, but I don't think there's a String encoding for it, and effectively it's a Function1 wrapper that's not useful from the IDE side. Task that can tell you exactly what needs to be deleted I think provides us opportunity to fine tune the semantics of `clean` down the line, and makes the implementation of `clean` really simple.

**Comment by eed3si9n** [comment]
Moved out the retry commit to a topic branch here (https://github.com/eed3si9n/sbt/tree/topic/retry_touch) for backup.

File: main/src/main/scala/sbt/Keys.scala (hunk 3 above)
Comment (dwijnand) [reply main/src/main/scala/sbt/Keys.scala:165]: Ah.. PathFinder is based on using FileFilter which is an unsealed trait. So it could be anything - "effectively it's a Function1 wrapper". Shame. 😞

**Review by dwijnand — APPROVED** [review]

**Comment by ktham** [comment]
Would it be possible to back-port this PR into `0.13.16`?

**Comment by eed3si9n** [comment]
@ktham Not all parts, but concurrency restriction change can.

**Comment by eed3si9n** [comment]
Actually 0.13.16 is already in RC-1, so we'd have to wait till 0.13.17.
In the mean time you might be able to implement a plugin yourself to backport the fix.
