### PR TITLE
[1.0.x] Add support for cross building commands

### LINKED ISSUE #2776: Cross-build ("+") command doesn't take aliases
While I was looking #1074, I realized that 1.0.x's `+` command doesn't work with aliases, unlike 0.13.x.
## steps

Start sbt 1.0.x and run `+` with an alias like below.

```
> show sbtVersion
[info] 1.0.0-SNAPSHOT
> alias foo = compile
> + foo
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: foo (similar: fork, doc, onLoad)
[error] ++  2.11.8 sbt-1074/foo
[error]                        ^
>
```
## problem

`+` command doesn't work with aliases.
## expectation

It was working on 0.13.x.

```
> show sbtVersion
[info] 0.13.11
> alias foo = compile
> + foo
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to sbt-1074 (in build file:/Users/kazuyoshi/sbt-1074/)
[info] Updating {file:/Users/kazuyoshi/sbt-1074/}sbt-1074...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 0 s, completed Oct 10, 2016 8:45:31 PM
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to sbt-1074 (in build file:/Users/kazuyoshi/sbt-1074/)
>
```

### PR DESCRIPTION
**Pull request by jroper**
Fixes #2776

This allows cross building commands. When issuing a command, it detects whether there is likely to be any Scala version incompatibilities, by checking whether all projects have the same Scala cross version configuration, if not, it outputs a big fat warning.

Note that there are still a few gotchas. If you have a command that overrides a task, the task will generally be executed by the cross building (this actually depends on whether there's a space in the command issued or not, eg if it's an input task).

But for the case that most people are concerned about, this should work.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3446/head&deploy_to_bintray=false">this link.</A>

**Review by dwijnand — APPROVED** [review]

**Review by eed3si9n — APPROVED** [review]

File: main/src/main/scala/sbt/Cross.scala [hunk 1]
```diff
@@ -125,30 +126,65 @@ object Cross {
...
+        case Right(_) =>
+          // We have a key, we're likely to be able to cross build this using the per project behaviour.
+
+          // Group all the projects by scala version
+          projVersions.groupBy(_._2).mapValues(_.map(_._1)).toSeq.flatMap {
+            case (version, Seq(project)) =>
+              // If only one project for a version, issue it directly
+              Seq(s"$SwitchCommand $verbose $version $project/$aggCommand")
+            case (version, projects) if aggCommand.contains(" ") =>
+              // If the command contains a space, then the all command won't work because it doesn't support issuing
```
Comment (mr-git) [inline main/src/main/scala/sbt/Cross.scala]: just my 2 cents...
does `all` references command, like in `all compile test`? if so, it would be nice to separate it from rest of text by using ticks or quotes, like:
> .. then the \`all\` command ..

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?sbt=pull/3446/head&deploy_to_bintray=false">this link.</A>

File: main/src/main/scala/sbt/Cross.scala [hunk 2]
```diff
@@ -125,30 +126,65 @@ object Cross {
       case Left(cmd) => (resolveAggregates(x), cmd)
     }
 
+    val projCrossVersions = aggs map { proj =>
+      proj -> crossVersions(x, proj)
+    }
     // if we support scalaVersion, projVersions should be cached somewhere since
     // running ++2.11.1 is at the root level is going to mess with the scalaVersion for the aggregated subproj
```
Comment (mr-git) [inline main/src/main/scala/sbt/Cross.scala:133]: > running ++2.11.1 **is** at the root ..
doesn't sound good

File: main/src/main/scala/sbt/Cross.scala [hunk 3]
```diff
@@ -125,30 +126,65 @@ object Cross {
...
+            case (version, Seq(project)) =>
+              // If only one project for a version, issue it directly
+              Seq(s"$SwitchCommand $verbose $version $project/$aggCommand")
+            case (version, projects) if aggCommand.contains(" ") =>
+              // If the command contains a space, then the all command won't work because it doesn't support issuing
+              // commands with spaces, so revert to running the command on each project one at a time
+              s"$SwitchCommand $verbose $version" :: projects.map(project =>
+                s"$project/$aggCommand")
+            case (version, projects) =>
+              // First switch scala version, then use the all command to run the command on each project concurrently
```
Comment (mr-git) [inline main/src/main/scala/sbt/Cross.scala:184]: > .. then use the **\`all\`** command..

File: main/src/main/scala/sbt/Cross.scala (hunk 2 above)
Comment (eed3si9n) [reply main/src/main/scala/sbt/Cross.scala:133]: The comment probably can be removed now since we recover the state using `State` instead of issuing `++` at the end.

**Comment by eed3si9n** [comment]
Looks like https://travis-ci.org/sbt/sbt/builds/264630941 and https://travis-ci.org/sbt/sbt/builds/264844665 are failing on some tests:

```
[error] x project / scripted13 
[error]  Cause of test exception: {line 7}  Command failed

[error] x source-dependencies / remove-test-a 
sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.

[error] x tests / fork-test-group-parallel 
[error]  Cause of test exception: {line 1}  Command failed
```

**Comment by eed3si9n** [comment]
Will just sent me a typo correcting PR and it's also failing, so it seems like our HEAD is broken.
https://travis-ci.org/sbt/sbt/builds/264907233

**Comment by jroper** [comment]
Yep, the `project/scripted13` one I can reproduce, but none of the code paths it uses have been modified by me (it does use `++`, but I've only modified `+`). The other two I can't reproduce. The error I get for `project/scripted13` is different though to what's in the build.

**Comment by eed3si9n** [comment]
It works for me fine locally either on this branch or 1.x:

```
Running project / scripted13
[info] [error] (*:scripted) Failed tests:
[info] [error] 	a / b
[info] [error] Total time: 15 s, completed Aug 16, 2017 12:41:15 AM
[success] Total time: 107 s, completed Aug 16, 2017 12:41:17 AM
```

The error output I think part of the negative test `(-> scripted)`

**Comment by eed3si9n** [comment]
Merging to 1.0.x.
