### PR TITLE
Fix cross command (+) for input tasks in subprojects with provided input

### LINKED ISSUE #4715: Failure running +project/testOnly
## steps

In a multi-project build for a library that cross-compiles, run a single test across multiple Scala versions:

```
> +foo/testOnly foo.BarTest
```

I'll try to send a scripted test in a PR to prove this is not working.

## problem

This used to work in sbt 0.13.  In sbt 1.2.8, there's a runtime exception:

```
[error] java.util.NoSuchElementException: key not found: ProjectRef(file:project/,root)
[error] 	at scala.collection.immutable.Map$Map1.apply(Map.scala:111)
[error] 	at sbt.Cross$.crossBuildCommandImpl(Cross.scala:167)
[error] 	at sbt.Cross$.$anonfun$crossBuild$2(Cross.scala:123)
[error] 	at sbt.Cross$$$Lambda$386/2095970915.apply(Unknown Source)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$$$Lambda$330/509806761.apply(Unknown Source)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$$$Lambda$356/756637412.apply(Unknown Source)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.MainLoop$$$Lambda$311/1800932232.apply(Unknown Source)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.MainLoop$$$Lambda$310/2000410491.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.MainLoop$$$Lambda$303/1226298219.apply(Unknown Source)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.NoSuchElementException: key not found: ProjectRef(file:project/,root)
```

## expectation

Run the test across multiple versions of Scala, and not throw an exception.

## notes

sbt version: 1.2.8

Thanks for sbt,
Aaron

### PR DESCRIPTION
**Pull request by eatkins**
Fixes https://github.com/sbt/sbt/issues/4715

Currently if you have a root project that aggregates a subproject, foo, and run
```
+ foo / testOnly FooSpec
```
sbt will throw an exception during parsing. This PR fixes that.

### CODE REVIEW

**Comment by eatkins** [comment]
I just remembered https://github.com/sbt/sbt/issues/4715. This should fix that.

**Review by eed3si9n — APPROVED** [review]

File: main/src/main/scala/sbt/Cross.scala [hunk 1]
```diff
@@ -127,76 +128,76 @@ object Cross {
...
+          .mapValues(_.map(_._2).toSet)
+        val commandsByVersion = keysByVersion.toSeq
+          .flatMap {
+            case (v, keys) =>
+              val projects = keys.flatMap(project)
+              keys.toSeq.flatMap { k =>
+                project(k).filter(projects.contains).flatMap { p =>
+                  if (p == extracted.currentRef || !projects.contains(extracted.currentRef)) {
+                    val parts = project(k).map(_.project) ++ k.scope.config.toOption.map {
+                      case ConfigKey(n) => n.head.toUpper + n.tail
```
Comment (dwijnand) [inline main/src/main/scala/sbt/Cross.scala:184]: Is this correct?  I'm not sure what the string `n` can be, but will this do the right thing with a configuration defined as `val AppTest = config("app-test")`?

Either way, this logic should exist in some more central location than buried in here.

File: main/src/main/scala/sbt/Cross.scala [hunk 2]
```diff
@@ -127,76 +128,76 @@ object Cross {
...
-                projects.map(_ + "/" + aggCommand).mkString("all ", " ", "")
-              )
+          .groupBy(_._1)
+          .mapValues(_.map(_._2).toSet)
+        val commandsByVersion = keysByVersion.toSeq
+          .flatMap {
+            case (v, keys) =>
+              val projects = keys.flatMap(project)
+              keys.toSeq.flatMap { k =>
+                project(k).filter(projects.contains).flatMap { p =>
```
Comment (dwijnand) [inline main/src/main/scala/sbt/Cross.scala:181]: The `projects.contains` seems redundant seeing as it's defined in terms of the projects in `keys` already.

File: main/src/main/scala/sbt/Cross.scala (hunk 1 above)
Comment (eed3si9n) [reply main/src/main/scala/sbt/Cross.scala:184]: That doesn't look right, and I missed it during the review.
The logic for slash displaying is around here - https://github.com/sbt/sbt/blob/develop/main-settings/src/main/scala/sbt/Def.scala

Comment (eatkins) [reply main/src/main/scala/sbt/Cross.scala:184]: I could not figure out how to get the config to display correctly with any of the Def apis. I had this problem with Continuous as well. Here is an attempt at a more central solution to this problem: https://github.com/sbt/sbt/pull/5332.
