### PR TITLE
[1.x] Stop background jobs when pressing `ctrl-c`

### LINKED ISSUE #2251: Sbt main process cancelation seems broken with timers
#2250 illustrates a bit of an issue with the process cancelation in sbt when `fork := false`. For whatever reason, the fibers *don't* seem to be canceled entirely and the thread pools are not cleaned up. Needs verification and minimization.

### LINKED ISSUE #6242: Run task cancelation doesn't seem to work in the shell
`fork := false`

Within the shell, invoking `run`, waiting a moment for the `main` to get rolling, and then hitting `ctrl-c` appears to not work at all. It *used* to `Thread#interrupt`, but no longer. To be clear, the `main` in question is sitting on a `CountDownLatch#await()`, and I've wrapped a `try/catch` around it to ensure I handle anything. What actually ends up happening is the following exception is printed to stderr (but *not* raised within my `try`/`catch`!):

```
java.util.concurrent.RejectedExecutionException
	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
	at sbt.Execute.submit(Execute.scala:282)
	at sbt.Execute.ready(Execute.scala:262)
	at sbt.Execute.notifyDone(Execute.scala:201)
	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:171)
	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
	at sbt.Execute$$anon$1.process(Execute.scala:27)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:476)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:475)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:188)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:553)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:543)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:543)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
	at sbt.xMain$.run(Main.scala:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

Sbt then returns to the shell and acts as if the process has been canceled, but if you do a thread dump, you'll see the `main` still stuck in `await()`. This also happens with `fork := true`, incidentally.

As far as I can tell, this appears to be sbt *itself* hitting a failure condition within the scheduling of the interrupts within `Execute`. Since the task is already canceled, subsequent executions hit the rejection exception shown above, including the step which would have interrupted the constituent threads from the `main`.

### LINKED ISSUE #6346: Cancelling the run task doesn't interrupt the thread
## steps

Reproduction here: https://github.com/steinybot/bug-reports/tree/sbt/sigint

sbt version: 1.4.7

```scala
object Main extends App {

  while (!Thread.currentThread().isInterrupted) {
    println("Kill me!")
    Thread.sleep(1000)
  }
}
```

1. `sbt run`
1. Press CTRL+C

## problem

The task stops waiting but the thread continues.

## expectation

The thread should be interrupted.

### PR DESCRIPTION
**Pull request by Friendseeker**
Implements https://github.com/sbt/sbt/pull/7914#discussion_r1859286435

> In case of `run` we should forward cancellation to cancelling the `bgRun` job.

Tested via a local `sbt` build, using reproduction from https://github.com/sbt/sbt/issues/6346.

Supersedes #7914

Closes https://github.com/sbt/sbt/issues/6346
Closes https://github.com/sbt/sbt/issues/6242
Closes https://github.com/typelevel/cats-effect/issues/2251

### CODE REVIEW

File: main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala [hunk 1]
```diff
@@ -508,6 +508,15 @@ private[sbt] object DefaultBackgroundJobService {
     backgroundJobServices.values.forEach(_.shutdown())
     backgroundJobServices.clear()
   }
+
+  private[sbt] def stop(): Unit = {
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: I think it's better to interpret Ctrl-C to be stop the foreground jobs. So instead of stopping everything, it should stop only the jobs started via `run`, or something like it?

Comment (Friendseeker) [reply main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: Currently only `run` and `runMain` use `BackgroundJobService` (through `BackgroundJobService.runInBackgroundWithLoader`), so it effectively stops only the jobs started via `run` or `runMain`.

`JobHandle` has a `spawningTask` attribute though. Shall investigate if we can use `spawningTask.key` to do filtering there to specifically filter for `run` and `runMain`.

Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: What about `bgRun`?

Comment (Friendseeker) [reply main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: Btw just brainstorming but wonder if we should add a new boolean flag `isForeground` to 
https://github.com/sbt/sbt/blob/1ee3c4b142c3bb26c4091fbacaee8ca5999ed19a/main/src/main/scala/sbt/BackgroundJobService.scala#L99-L103

So we can just filter by `isForeground` to tell if the background job should be stopped when `ctrl+c` is pressed.

Or maybe like `object RunningProcesses`, we can make `object RunningForegroundJobs` with identical API as   `RunningProcesses` to store the `ctrl-c` cancellable jobs.

Comment (Friendseeker) [reply main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: > bgRun

Oh nice catch, I completely forgot about it...

Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala:514]: Yea. I like the idea. `isAutoCancel` maybe, since the job itself is background.

File: main/src/main/scala/sbt/BackgroundJobService.scala [hunk 2]
```diff
@@ -100,4 +100,5 @@ abstract class JobHandle {
   def id: Long
   def humanReadableName: String
   def spawningTask: ScopedKey[_]
+  @volatile var isAutoCancel: Boolean
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/BackgroundJobService.scala]: This looks out of place to the otherwise nice interface. Could we make this a `def` like others, and then we can pattern match on `JobHandle` to see if it's a `ThreadJobHandle`, and then access the var?

**Review by eed3si9n — APPROVED** [review]
Thanks!
