### PR TITLE
Use custom classloader for scripted tests

### LINKED ISSUE #4514: scripted within scripted do not work with latest util version
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
publish "1.3.0-SNAPSHOT" in https://github.com/sbt/util
change utilVersion to "1.3.0-SNAPSHOT" in project/Dependencies.scala

## problem
scripted tests fail hard with java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil

## expectation
scripted works

## notes

sbt version: unreleased

### PR DESCRIPTION
**Pull request by eatkins**
We had previously used reflection to load the bridge class, but
continued using sbt's default classloader. This was problematic because
the metabuild could have a different classpath from that required by the
scripted tests.

Bonus: scalafmt

Fixes: #4514

- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

### CODE REVIEW

File: project/Scripted.scala [hunk 1]
```diff
@@ -102,38 +104,43 @@ object Scripted {
...
-      bridge.runInParallel(
-        sourcePath,
-        bufferLog,
-        args.toArray,
-        launcher,
-        launchOpts.toArray,
-        callback,
-      )
-    } catch { case ite: InvocationTargetException => throw ite.getCause }
+      Thread.currentThread.setContextClassLoader(loader)
```
Comment (eed3si9n) [inline project/Scripted.scala:124]: Thanks for figuring this out.

**Comment by eed3si9n** [comment]
Could you revert 67a0962b183628c962084e24e5fe8cc789bda9cf please?

File: project/Scripted.scala (hunk 1 above)
Comment (eatkins) [reply project/Scripted.scala:124]: Necessity is the mother of invention :)

**Comment by eatkins** [comment]
reverted

**Comment by eatkins** [comment]
Evidently this doesn't actually fix the disabled tests. It does, however, allow me to run scripted tests on my machine using older versions of sbt.

**Review by eed3si9n — APPROVED** [review]
