### PR TITLE
[2.x] fix: Skips interactive prompt in batch mode when project loading

### LINKED ISSUE #8344: "-batch" mode should remove "Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)" prompt
## steps

- write a type error in build.sbt
- test it with "sbt -batch test"
- the last line always contains "Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)" 

## problem

In batch mode this prompt should be omitted, as batch mode has no user interaction.

this prompt also caused IntelliJ Scala plugin to hang indefinitely, unable to proceed:

Image

## expectation

remove this line in batch mode

### PR DESCRIPTION
**Pull request by Francluob**
… fails

When project loading fails in batch mode, sbt was showing an interactive prompt asking the user to choose between retry, quit, last, or ignore. However, in batch mode there is no interactive terminal, causing the process to hang waiting for input that will never come.

This fix checks if we're in batch mode (Prompt.Batch) and automatically retries the project load (the default behavior) without prompting the user. This allows batch mode scripts to continue execution even when project loading encounters transient errors.

The interactive behavior remains unchanged for non-batch mode.

Closes #8344

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=11581451

### CODE REVIEW

**Comment by Francluob** [comment]
hello @eed3si9n
could you please review my pr?
thanks

File: main/src/main/scala/sbt/Main.scala [hunk 1]
```diff
@@ -869,6 +869,11 @@ object BuiltinCommands {
 
   @tailrec
   private def doLoadFailed(s: State, loadArg: String): State = {
+    // In batch mode, automatically retry (default behavior) without prompting
+    if (ITerminal.console.prompt == Prompt.Batch) {
+      val retry: State = loadProjectCommand(LoadProject, loadArg) :: s.clearGlobalLog
+      return retry
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala]: If there's an error, then this could likely keep looping, so we should maybe use `q` or `l` here.

Comment (eed3si9n) [reply main/src/main/scala/sbt/Main.scala]: Also generally we avoid using `return` statement in Scala.

Comment (Francluob) [reply main/src/main/scala/sbt/Main.scala]: oh, makes sense. I feel like `q` should be better.

Comment (Francluob) [reply main/src/main/scala/sbt/Main.scala]: > If there's an error, then this could likely keep looping, so we should maybe use `q` or `l` here.

pushed a fix, if you can check again, thanks

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by Francluob** [comment]
> Thanks!

great! all of the tests passed 🥳
