### PR TITLE
Close classloader in fgRun/fgRunMain

### LINKED ISSUE #5124: [1.3.2] fgRun performance regression
## steps
sbt version: 1.3.2
build.sbt
```
scalaVersion := "2.13.1"
turbo := true
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value
```

main.scala
```
object Main {
  def main(args: Array[String]): Unit = {
    val start = System.currentTimeMillis()
    println(implicitly[scala.reflect.runtime.universe.TypeTag[Int]])
    println(System.currentTimeMillis() - start)
  }
}
```

## problem
running this with `fgRun` takes around 1 second

## expectation
~1ms run (like with 1.3.0)

## notes
plain `run` now runs faster than `fgRun`, even though `bgRun` is as slow as it was before

### PR DESCRIPTION
**Pull request by eatkins**
It is necessary to close the run classloader in order to reuse the
dependency layer in the next run.

Fixes #5124.

### CODE REVIEW

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -1510,7 +1510,15 @@ object Defaults extends BuildCommon {
       loadForParser(discoveredMainClasses)((s, names) => runMainParser(s, names getOrElse Nil))
     Def.inputTask {
       val (mainClass, args) = parser.parsed
-      scalaRun.value.run(mainClass, data(classpath.value), args, streams.value.log).get
+      val cp = data(classpath.value)
+      val logger = streams.value.log
+      scalaRun.value match {
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala]: Could we push this logic into Run?

Comment (eatkins) [reply main/src/main/scala/sbt/Defaults.scala]: Yes. That's a better solution.

**Review by eed3si9n — APPROVED** [review]
