### PR TITLE
[2.x] fix: Preserve user-specified scope axes in  command instead of silently discarding them

### LINKED ISSUE #1124: The semantics of "set every" may be surprising to users
The command "set every" redefines the tasks/settings that match the supplied key in all the scopes. Now, consider the following:

```
set every sources in (Compile,doc) := Seq.empty
```

The result is that the scope supplied in the command is silently ignored, and all the sources in every scope are emptied, leading to empty executable jars.

This semantics may be quite surprising where users assume that "set every" just iterates over all the projects; the fact that the supplied scope is silently discarded may be cause for considerable confusion.

Possible approaches: "set every" should either stop if a scope is supplied in the command line, or at least issue a warning. As a more complete solution, "set every" could be changed in order to take some scope filtering into account. If a change in semantics is not viable, an alternate command "set-in-all-projects" could be added in order to supply the alternate semantics that users may expect.

### PR DESCRIPTION
**Pull request by Crystora**
### Problem

`set every` silently discards scope axes the user provides. Running:

```
set every Test / sources := Nil
```

empties `sources` in **all** scopes including `Compile`, not just `Test`. This happens because `rescope` in `SettingCompletions.setAll` strips the scope and forces `Global`.

Fixes #1124

### Solution

Changed `rescope` to keep the user's config/task/extra axes and only wildcard the project axis. When no scope is given, behavior is unchanged - all axes match everything as before.

### Test

- `scripted tests/set-every` (existing) - passed, backward compatible
- `scripted tests/set-every-scoped` (new) - runs `set every Test / sources := Nil` on a multi-project build, checks `Compile / sources` stays intact while `Test / sources` is emptied

Generated-by: Claude Opus 4.6

### CODE REVIEW

**Comment by Crystora** [comment]
@eed3si9n Could you please review this PR? thanks

**Comment by Crystora** [comment]
@eed3si9n please review my PR. I'd appreciate any feedbacks.
thank you

File: main/src/main/scala/sbt/internal/SettingCompletions.scala [hunk 1]
```diff
@@ -55,12 +55,33 @@ private[sbt] object SettingCompletions {
     def resolve(s: Setting[?]): Seq[Setting[?]] =
       Load.transformSettings(projectScope, currentRef.build, rootProject, s :: Nil)
 
+    def thisToZero[T](axis: ScopeAxis[T]): ScopeAxis[T] =
+      axis match
+        case This => Zero
+        case a    => a
```
Comment (anatoliykmetyuk) [inline main/src/main/scala/sbt/internal/SettingCompletions.scala]: Can we use `Scope.subThis` in place of this function? It does the same thing and reusing it would minimise the diff.

**Review by anatoliykmetyuk — APPROVED** [review]
LGTM, thanks @bittoby

**Comment by Crystora** [comment]
@anatoliykmetyuk Thanks for your feedback. I have fixed!

**Comment by Crystora** [comment]
@eed3si9n Could you please review this PR and merge if it has no problem? Thanks

**Review by eed3si9n — APPROVED** [review]
I concur with Toli's review. Thanks for the contribution!

**Comment by Crystora** [comment]
Thanks!
