### PR TITLE
[1.5.0-M1] Improve error report for scala3doc missing

### LINKED ISSUE #6264: [1.5.0-M1] ClassNotFoundException on doc task on Scala 3.0.0-M3
## steps

Given a hello world project:

```
> ++3.0.0-M3!
> doc
```

## problem

```
sbt:root> doc
[info] Main Scala API documentation to /private/tmp/hello/target/scala-3.0.0-M3/api...
[error] stack trace is suppressed; run last Compile / doc for the full output
[error] (Compile / doc) java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
```

## expectation

it works.

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #6264 

The error message appears only when running doc task if `scala3doc` is missing.

Failure
```shell
sbt:root> doc
[info] compiling 13 Scala sources to /foo/target/scala-3.0.0-M3/classes ...
[error] Unresolved scala3doc artifact
[error] Add 'resolvers += Resolver.JCenterRepository'
[info] Main Scala API documentation to /foo/target/scala-3.0.0-M3/api...
[error] stack trace is suppressed; run last foo / Compile / doc for the full output
[error] (foo / Compile / doc) java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
[error] Total time: 1 s, completed Jan 18, 2021, 8:20:48 PM
```

Success:
```shell
sbt:root> doc
[info] Main Scala API documentation to /foo/target/scala-3.0.0-M3/api...
[warn] Setting -bootclasspath is currently not supported.
[warn] one warning found
[info] Main Scala API documentation successful.
[success] Total time: 2 s, completed Jan 18, 2021, 8:20:56 PM
```

Now I realize that `[warn] Setting -bootclasspath is currently not supported.`. I don't think its a blocker but I'll create an issue and try to fix it.

### CODE REVIEW

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -2055,13 +2055,25 @@ object Defaults extends BuildCommon {
...
-              val docSrcs = if (ScalaArtifacts.isScala3(sv)) tFiles else srcs
+              val isScala3 = ScalaArtifacts.isScala3(sv)
+              def isScala3Doc(module: ModuleID): Boolean = {
+                module.configurations.exists(_.startsWith(Configurations.ScalaDocTool.name)) &&
+                module.name == ScalaArtifacts.Scala3DocID
+              }
+              if (isScala3 && !allDeps.exists(isScala3Doc)) {
+                Array(
+                  "Unresolved scala3doc artifact",
+                  "Add 'resolvers += Resolver.JCenterRepository'"
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala]:
```suggestion
                  "add 'ThisBuild / resolvers += Resolver.JCenterRepository'"
```

Comment (eed3si9n) [reply main/src/main/scala/sbt/Defaults.scala]: If you have a bunch of subprojects scoping it to `ThisBuild` may be better?
