### PR TITLE
[2.x] fix: Display HTTP response body when bundle upload fails

### LINKED ISSUE #8264: Display more info when bundle upload fails
## Steps

Example: https://github.com/japgolly/scalajs-react/actions/runs/17478739359/job/49645392315#step:4:1131

```bash
cd library && sbt -v -J-Xmx6g ci-release
```

## Problem

Currently when a bundle upload fails, only the HTTP status is shown.

```scala
[info] set current project to scalajs-react (in build file:/home/runner/work/scalajs-react/scalajs-react/library/)
[info] uploading bundle to the Central Portal (attempt: 1)
[info] uploading bundle to the Central Portal (attempt: 2)
[info] uploading bundle to the Central Portal (attempt: 3)
gigahorse.StatusError: Unexpected status: 401
	at gigahorse.StatusError$.apply(StatusError.scala:30)
	at gigahorse.support.apachehttp.OkHandler.onStatusReceived(OkHandler.scala:23)
	at gigahorse.support.apachehttp.OkHandler.onStatusReceived$(OkHandler.scala:21)
	at gigahorse.support.apachehttp.OkHandler$FullOkHandler.onStatusReceived(OkHandler.scala:28)
	at gigahorse.support.apachehttp.ApacheHttpClient$$anon$2.$anonfun$completed$1(ApacheHttpClient.scala:203)
	at gigahorse.support.apachehttp.ApacheHttpClient.gigahorse$support$apachehttp$ApacheHttpClient$$attempt(ApacheHttpClient.scala:217)
	at gigahorse.support.apachehttp.ApacheHttpClient$$anon$2.completed(ApacheHttpClient.scala:202)
	at gigahorse.support.apachehttp.ApacheHttpClient$$anon$2.completed(ApacheHttpClient.scala:200)
	at gigahorse.shaded.apache.org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:148)
	at gigahorse.shaded.apache.org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:72)
	at gigahorse.shaded.apache.org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2$1.completed(InternalAbstractHttpAsyncClient.java:318)
	at gigahorse.shaded.apache.org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer$1.completed(AbstractAsyncResponseConsumer.java:101)
	at gigahorse.shaded.apache.org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:87)
	at gigahorse.shaded.apache.org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:83)
	at gigahorse.shaded.apache.org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142)
	at gigahorse.shaded.apache.org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:283)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.ClientH2StreamHandler.consumeData(ClientH2StreamHandler.java:242)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer$H2Stream.consumeData(AbstractH2StreamMultiplexer.java:1645)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.consumeDataFrame(AbstractH2StreamMultiplexer.java:1049)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.consumeFrame(AbstractH2StreamMultiplexer.java:738)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.onInput(AbstractH2StreamMultiplexer.java:447)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.AbstractH2IOEventHandler.inputReady(AbstractH2IOEventHandler.java:65)
	at gigahorse.shaded.apache.org.apache.hc.core5.http2.impl.nio.ClientH2IOEventHandler.inputReady(ClientH2IOEventHandler.java:39)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:618)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.ssl.SSLIOSession.access$200(SSLIOSession.java:74)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:204)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:143)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:176)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:125)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:92)
	at gigahorse.shaded.apache.org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.lang.Thread.run(Thread.java:748)
[error] gigahorse.StatusError: Unexpected status: 401
```

## Expectations

 Better would be to show the entire HTTP response body because it will contain an error msg.

### PR DESCRIPTION
**Pull request by DeborahOlaboye**
## Summary

Fixes #8264

When a bundle upload to Central Portal fails, the error now displays the HTTP response body instead of just the status code. This provides more useful debugging information, as the response body typically contains detailed error messages from the server.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution! The change looks great.
Could you sign the CLA, and let me know please?

**Comment by DeborahOlaboye** [comment]
> Thanks for the contribution! The change looks great. Could you sign the CLA, and let me know please?

I've been unable to sign the CLA, I keep getting 500 error.

**Comment by eed3si9n** [comment]
Despite the 500, it seems like the CLA checker is now passing.

File: main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala [hunk 1]
```diff
@@ -8,20 +8,39 @@
...
 import sbt.internal.util.BasicLogger
 import sbt.util.*
 import sjsonnew.support.scalajson.unsafe.Parser
 
 import scala.collection.immutable
 
-object SonaClientTest extends BasicTestSuite:
+class SonaClientTest extends AnyFlatSpec {
+
+  "SonaStatusError" should "include both status and body in message" in {
```
Comment (eed3si9n) [inline main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala]: Actually could you merge develop, or rebase on top of it? SonaClientTest has migrated recently to use Verify - https://github.com/sbt/sbt/blob/develop/main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala

Comment (DeborahOlaboye) [reply main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala]: Alright, done.

Comment (eed3si9n) [reply main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala]:
```suggestion
  test("SonaStatusError should include both status and body in message") {
```

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala (hunk 1 above)
Comment (eed3si9n) [reply main-actions/src/test/scala/sbt/internal/sona/SonaClientTest.scala]: And other tests too.

**Review by eed3si9n — APPROVED** [review]
