### PR TITLE
[2.x] fix: Suppress "Multiple main classes" warning for runMain commands

### LINKED ISSUE #3739: Useless "Multiple main classes" detected when running runMain
When using `runMain` a useless warning is printed to the console multiple times per run:

```
akka-http-tests > ~ test:runMain foobar.ReproduceAkkaBug
[info] Formatting 1 Scala source {file:/home/johannes/git/opensource/akka-http/}akka-http-tests(test) ...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Compiling 1 Scala source to /home/johannes/git/opensource/akka-http/akka-http-tests/target/scala-2.11/test-classes ...
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
```

If you use `runMain` you are obviously aware of that fact.

sbt 1.0.3

### PR DESCRIPTION
**Pull request by calm329**
## Summary
- Fix warning appearing for scoped runMain commands using colon syntax (`test:runMain`)
- Extend warning suppression to all run command variants (`bgRunMain`, `fgRunMain`)

## Problem
When running `runMain` (especially scoped like `test:runMain`), the "Multiple main classes detected" warning was printed even though the user explicitly specified which main class to run.

## Solution
Changed the scope separator parsing from `/` only to `[/:]` to handle both new slash syntax (`Test/runMain`) and old colon syntax (`test:runMain`).

## Test
Added scripted test `run/run-main-warning` covering `runMain`, `bgRunMain`, `fgRunMain`, and scoped variants.

Fixes #3739

### CODE REVIEW

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -1066,14 +1066,19 @@ object Defaults extends BuildCommon {
       selectMainClass := mainClass.value orElse askForMainClass(discoveredMainClasses.value),
       run / mainClass := (run / selectMainClass).value,
       mainClass := Def.uncached {
+        // Suppress warning for run commands (user is actively running, warning is noise)
+        def isRunCommand(s: String): Boolean = s match
+          case "run" | "runMain" | "bgRun" | "bgRunMain" | "fgRun" | "fgRunMain" => true
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala:1071]: Are we no longer showing warnings for `run` because the user would be prompted for the main class?

Comment (calm329) [reply main/src/main/scala/sbt/Defaults.scala:1071]: The original code already suppressed for both `run` and `runMain` - I kept that behavior and extended it to the `bg*/fg*` variants.
If you'd prefer to only suppress for the explicit `*Main` variants, I can change it to:
```scala
case "runMain" | "bgRunMain" | "fgRunMain" => true
```

Let me know which behavior you'd prefer.

Comment (eed3si9n) [reply main/src/main/scala/sbt/Defaults.scala:1071]: > The original code already suppressed for both `run` and `runMain`

Doh, you're right. The change looks good to me then.

**Review by eed3si9n — APPROVED** [review]
