### PR TITLE
cached resolution: Fixes #1711, #1716, #1719

### LINKED ISSUE #1711: [0.13.7-RC2] cached resolution pulls in % "test" dependencies from other subproj
From: https://groups.google.com/forum/#!folder/Scala/sbt-dev/k4XZiKQjVHA

There seems to be one issue: it generates a different dependency tree for (at least) one of my modules. Noticeable because I now see deprecation warnings from the new version of the library which isn't supposed to be on my classpath and isn't with 0.13.6. Here is some data for said module, let's call it module A.
https://gist.github.com/japgolly/149ad9a9491a3515abca

Three problems are evident here.
1. I'm explicitly declaring 1.11.3 of ScalaCheck in my build but 1.11.4 is used.
2. This module dependsOn module B. Module B uses utest as a test dependency. I'm now see utest.jar on module A's test classpath.
3. Way more specs2 jars on the classpath. I'm explicitly only depending on -core and -scalacheck.

(By the way, I can't run dependencyTree for comparison because it doesn't work on 0.13.6 for some reason. Keeps harping on about blah-compile.xml not found.)

### PR DESCRIPTION
**Pull request by eed3si9n**
To fix #1711, cached resolution started creating artificial `DependencyDescriptor`s recently (like 4 days ago) af9e520e2817f7bf38cbc3bb474bce4a310a04af, and went out as RC-3.
There are some issues with the implementation, which are reported as #1716 and #1719.
This PR adds scripted test that reproduces those issues and fixes for them, hopefully fixing all three issues.

### CODE REVIEW

File: ivy/src/main/scala/sbt/ivyint/CachedResolutionResolveEngine.scala [hunk 1]
```diff
@@ -88,32 +93,44 @@ private[sbt] class CachedResolutionResolveCache() {
...
         {
+          log.debug(s""":::: remapping configuration of ${dd0} with ${confMap.toList map { case (k, v) => (k, v.toList) }}""")
           val dd = new DefaultDependencyDescriptor(md0, dd0.getDependencyRevisionId, dd0.getDynamicConstraintDependencyRevisionId,
             dd0.isForce, dd0.isChanging, dd0.isTransitive)
+          val moduleConfigurations = dd0.getModuleConfigurations.toVector
           for {
-            moduleConf <- dd0.getModuleConfigurations
-            (rootModuleConf, vs) <- confMap
+            moduleConf <- moduleConfigurations
+            (rootModuleConf, vs) <- confMap.toSeq
```
Comment (jsuereth) [inline ivy/src/main/scala/sbt/ivyint/CachedResolutionResolveEngine.scala:104]: Does this handle transitive `test->compile->runtime` style mappings?

File: sbt/src/sbt-test/dependency-management/cached-resolution-classifier/multi.sbt [hunk 2]
```diff
@@ -8,31 +8,45 @@ def commonSettings: Seq[Def.Setting[_]] =
...
       "net.databinder" %% "unfiltered-uploads" % "0.8.0",
       "commons-io" % "commons-io" % "1.3",
-      "com.typesafe" % "config" % "0.4.9-SNAPSHOT",
-      "junit" % "junit" % "4.11" % "test"
+      "com.typesafe" % "config" % "0.4.9-SNAPSHOT"
     )
   )
 
 lazy val b = project.
+  dependsOn(classifierTest, transitiveTest % "test->test").
```
Comment (jsuereth) [inline sbt/src/sbt-test/dependency-management/cached-resolution-classifier/multi.sbt:42]: For giggles, why not do `*->*` here (to denote that all your configs depend on all his configs).

**Comment by jsuereth** [comment]
You may need to walk me through this one.

**Comment by jsuereth** [comment]
LGTM
