### PR TITLE
[2.x] fix: Note that dynamic usage isn't going to be linted

### LINKED ISSUE #5647: Dynamic task or .all(<filter>) show up as "not used" keys lint
## steps

Using a 1.4.0-SNAPSHOT build off of Ethan's sbtc PR (#5620), in the Zinc repo, with sbtc.bash sourced, `sbtc <TAB>` (i.e. start the build)

## problem

```
[warn] there are 2 keys that are not used by any other settings/tasks:
[warn]
[warn] * Global / shellPrompt
[warn]   +- /Users/dnw/.sbt/1.0/global.sbt:13
[warn] * ThisBuild / whitesourceIgnoredScopes
[warn]   +- /d/zinc/build.sbt:768
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
```

## expectation

sbt-whitesource defines a default for `whitesourceIgnoredScopes` in Global scope:

https://github.com/lightbend/sbt-whitesource/blob/513b71b9ac4d96f7ef9510ee957752996098103d/src/main/scala/sbtwhitesource/WhiteSourcePlugin.scala#L110-L122

and then consumes it in project scope:

https://github.com/lightbend/sbt-whitesource/blob/513b71b9ac4d96f7ef9510ee957752996098103d/src/main/scala/sbtwhitesource/WhiteSourcePlugin.scala#L193

so defining it in build scope shouldn't be "not used".

### PR DESCRIPTION
**Pull request by bitloi**
Fixes #5647

## Summary

Keys that are only used through `key.all(ScopeFilter).value` were not seen by the unused-settings lint, so they could be reported as unused even when they were in use.

This PR makes those “dynamic” usages visible to the lint by:

- Recording dynamic dependencies when `SettingKey.all(filter)` / `TaskKey.all(filter)` are used (via `Def.withDynamicDependencies` and a small extension to `Initialize`).
- In the lint pass, collecting those dynamic deps from all settings, expanding them to concrete `ScopedKey`s with the build structure, and adding those to the set of used keys.

So any key that is only referenced via `.all(scopeFilter).value` is now treated as used and no longer flagged as unused.

### CODE REVIEW

**Comment by bitloi** [comment]
@eed3si9n Ready for review! Please give me your feedback when you are available.

File: util-collection/src/main/scala/sbt/internal/util/Settings.scala [hunk 1]
```diff
@@ -630,6 +630,10 @@ trait Init:
    */
   sealed trait Initialize[A1]:
     def dependencies: Seq[ScopedKey[?]]
+
+    /** Dynamic dependencies (e.g. from .all(ScopeFilter)) not visible in the static graph. */
+    private[sbt] def dynamicDependencies: Seq[Any] = Nil
```
Comment (eed3si9n) [inline util-collection/src/main/scala/sbt/internal/util/Settings.scala]: While I appreciate the effort adding a whole new mechanism at the Initialized level just for dynamic tasks doesn't seem worth it.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: util-collection/src/main/scala/sbt/internal/util/Settings.scala (hunk 1 above)
Comment (bitloi) [reply util-collection/src/main/scala/sbt/internal/util/Settings.scala]: Thanks for the review. I get that this adds more than we want for this case.
I’m open to simplifying. Do you’d rather we (a) try a lighter fix that only touches the lint (e.g. some heuristic so keys used via `.all(scopeFilter).value` aren’t reported unused), or (b) leave the current behavior and just document that keys only used that way can be flagged as unused?

Comment (eed3si9n) [reply util-collection/src/main/scala/sbt/internal/util/Settings.scala]: > (b) leave the current behavior and just document that keys only used that way can be flagged as unused.

b, I think.

Comment (bitloi) [reply util-collection/src/main/scala/sbt/internal/util/Settings.scala]: Just fixed it.

File: main/src/main/scala/sbt/ScopeFilter.scala [hunk 2]
```diff
@@ -218,6 +218,25 @@ object ScopeFilter {
...
+      .mapValues: byProj =>
+        byProj
+          .groupBy(_.config)
+          .view
+          .mapValues: byConfig =>
+            byConfig.groupBy(_.task).view.mapValues(_.toSet).toMap
+          .toMap
+      .toMap
+    new Data(units, resolve, new AllScopes(scopes, grouped))
+
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/ScopeFilter.scala]: This is no longer used, correct?

File: main/src/main/scala/sbt/Keys.scala [hunk 3]
```diff
@@ -701,7 +701,9 @@ object Keys {
   @deprecated("No longer used", "1.3.0")
   private[sbt] val executeProgress = settingKey[State => TaskProgress]("Experimental task execution listener.").withRank(DTask)
   val commandProgress = settingKey[Seq[ExecuteProgress2]]("Command progress listeners receive events when commands start and end, in addition to task progress events.")
-  val lintUnused = inputKey[Unit]("Check for keys unused by other settings and tasks.")
+  val lintUnused = inputKey[Unit](
+    "Check for keys unused by other settings and tasks. Keys that are only used via key.all(ScopeFilter).value may still be reported as unused."
+  )
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Keys.scala]: This change is fine, but could we revert all other changes, if they are code format/style changes?

File: main/src/main/scala/sbt/ScopeFilter.scala (hunk 2 above)
Comment (bitloi) [reply main/src/main/scala/sbt/ScopeFilter.scala]: Correct — it was dead after the revert. Removed `dataFromStructure` and the unused `BuildStructure` import

File: main/src/main/scala/sbt/Keys.scala (hunk 3 above)
Comment (bitloi) [reply main/src/main/scala/sbt/Keys.scala]: Reverted the style/format changes in ScopeFilter, `LintUnused`, and `Settings`, and kept the `lintUnused` description on one line. Only the doc text change remains.

**Review by eed3si9n — APPROVED** [review]

**Comment by bitloi** [comment]
@eed3si9n Can we merge now?
