### PR TITLE
[2.x] feat: Add scriptedKeepTempDirectory setting

### LINKED ISSUE #3214: Scripted option to not remove temporary directory
## steps

I run scripted to debug my sbt plugin.

## problem

After the scripted tests complete, the temporary directories `/private/var/folder/adsfasda` are removed. Because the directory is removed, I can't `cd /private/var/...` to manually check what went wrong. To my best knowledge, there is no way to configure scripted to not delete the temporary directory.

## expectation

It would be nice if there was an option I could pass to scripted via `scriptedLaunchOpts` to tell it not to remove the tmp directory.

## notes

I work around this by issue adding `$ pause` in the scripted `test` and the `cp -r /private/var`. However, this is cumbersome and slow.

### PR DESCRIPTION
**Pull request by bitloi**
## feat: Add scriptedKeepTempDirectory setting to preserve temp directories

Fixes #3214

### Problem

When running scripted tests to debug sbt plugins, the temporary directories (`/private/var/folder/...`) are automatically deleted after tests complete. This makes it difficult to inspect the test state for debugging purposes, requiring workarounds like adding `$ pause` commands and manually copying directories.

### Solution

Added a new `scriptedKeepTempDirectory` setting that allows users to preserve temporary directories after scripted tests complete. When enabled, the temporary directory path is logged so users can inspect it.

Usage:
```scala
scriptedKeepTempDirectory := true
```

### Changes

- **ScriptedPlugin.scala**: Added `scriptedKeepTempDirectory` setting key (defaults to `false`)
- **ScriptedRun.scala**: Added `keepTempDirectory` parameter to `run()` method with backward-compatible versioning (V3 methods)
- **ScriptedTests.scala**: 
  - Added `keepTempDirectory` parameter to `run()`, `runInParallel()`, and `batchScriptedRunner()` methods
  - Modified `createTestRunners()` to conditionally use `IO.createTemporaryDirectory` instead of `IO.withTemporaryDirectory` when `keepTempDirectory` is true
  - Logs the temporary directory path when preserved

### Testing

- Compiles successfully
- Binary compatible (new methods added, no existing signatures changed)
- Backward compatible (defaults to `false`, existing behavior unchanged)

### Checklist

- [x] Compiles successfully
- [x] `scalafmtAll` applied
- [x] Binary compatible (maintains backward compatibility)
- [x] Follows coding style guidelines

### CODE REVIEW

**Comment by bitloi** [comment]
@eed3si9n Could you please review my PR?

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution! Overall the changes look good.
I probably need to grab this branch and test it manually.

**Comment by bitloi** [comment]
@eed3si9n Can we merge this pr?

**Review by eed3si9n — CHANGES_REQUESTED** [review]
I couldn't test this using sbt/sbt. For sbt/sbt's scripted test this funnels the call from sbt 1.x into sbt 2.x via reflection. Could you surface your new setting in project/Scripted.scala's `ScriptedKeys`, and fold that in to the `scriptedTask`. See also:

```scala
ThisBuild / scriptedBufferLog := true
ThisBuild / scriptedPrescripted := { _ => }
```

Thanks!

**Comment by bitloi** [comment]
> I couldn't test this using sbt/sbt. For sbt/sbt's scripted test this funnels the call from sbt 1.x into sbt 2.x via reflection. Could you surface your new setting in project/Scripted.scala's `ScriptedKeys`, and fold that in to the `scriptedTask`. See also:
> 
> ```scala
> ThisBuild / scriptedBufferLog := true
> ThisBuild / scriptedPrescripted := { _ => }
> ```
> 
> Thanks!

@eed3si9n Fixed. Could you please review again?

**Review by eed3si9n — CHANGES_REQUESTED** [review]
If I add `ThisBuild / scriptedKeepTempDirectory := true` to build.sbt, and run `scripted actions/compile` I see

```
[info] Running 1 / 1 (100.00%) scripted tests with LauncherBased(/Users/xxxx/sbt-launch.jar)
[info] Temporary directory for scripted tests: /var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_6446e5ca
[info] Running actions/compile
```

but the directory only contains global cache. Does it work for you locally?

**Comment by bitloi** [comment]
I found the issue - the test files were being deleted after each test run regardless of the `keepTempDirectory` setting. 

I've pushed a fix that:
1. Passes `keepTempDirectory` through to `runBatchedTests`
2. Conditionally skips the cleanup logic (lines 252-264) when `keepTempDirectory` is true

The cleanup code was deleting all files except `global` and `global-logging` directories after each test, which is why you only saw the global cache.

With this fix, when `scriptedKeepTempDirectory := true`, the test files should now remain in the temporary directory for debugging. Could you test it again?

File: scripted-sbt/src/main/scala/sbt/scriptedtest/ScriptedTests.scala [hunk 1]
```diff
@@ -241,16 +249,18 @@ final class ScriptedTests(
...
+          val base = tempTestDir.getCanonicalFile.toGlob
+          val global = base / "global"
+          val globalLogging = base / ** / "global-logging"
+          def recursiveFilter(glob: Glob): PathFilter = (glob: PathFilter) || glob / **
+          val keep: PathFilter = recursiveFilter(global) || recursiveFilter(globalLogging)
+          val toDelete = view.list(base / **, !keep).map(_._1).sorted.reverse
+          toDelete.foreach { p =>
+            try Files.deleteIfExists(p)
+            catch { case _: IOException => }
+          }
```
Comment (eed3si9n) [inline scripted-sbt/src/main/scala/sbt/scriptedtest/ScriptedTests.scala:269]: While this fixes the situation for a single test, wouldn't this mess up the batch test? Could you add a check such that when keepTempDirectory is passed only one scripted test is requested?

**Comment by bitloi** [comment]
Fixed, please review it again.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/issues/8748

**Comment by mkurz** [comment]
Very useful feature, thanks!
