### PR TITLE
[2.x] fix: Skip eviction warning when winner satisfies version range

### LINKED ISSUE #3978: Eviction warning when version falls within version range
## steps
1. Create an empty Scala.js project
2. Add the following to `build.sbt`:

    ```scala
    jsDependencies += "org.webjars.npm" % "aws-sdk" % "2.200.0" / "aws-sdk.js" minified "aws-sdk.min.js" commonJSName "AWS"
    ```
3. Run the `compile` task

## problem
The following warning is printed:

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.webjars.npm:xmlbuilder:4.2.1 is selected over [4.1.0,5)
[warn] 	    +- org.webjars.npm:aws-sdk:2.200.0                    (depends on 4.2.1)
[warn] 	    +- org.webjars.npm:xml2js:0.4.17                      (depends on [4.1.0,5))
```

## expectation
`4.2.1` is within the range `[4.1.0,5)`, so no warning should be printed for this dependency

## notes
sbt version: `1.1.1`

There was some discussion about this in the sbt/sbt Gitter channel: https://gitter.im/sbt/sbt?at=5a987351458cbde557e4567a

### PR DESCRIPTION
**Pull request by calm329**
## Summary

Fixes #3978

When a transitive dependency specifies a version range (e.g., `[4.1.0,5)` or `[1.3.0,)`), sbt incorrectly shows an eviction warning even when the selected version falls within that range.

**Before:** `angular:1.4.7 is selected over [1.3.0,)` triggers a warning
**After:** No warning, since `1.4.7` satisfies `[1.3.0,)` (1.4.7 >= 1.3.0)

## Changes

- Add `versionSatisfiesRange()` function to `VersionRange.scala` supporting Maven-style ranges (`[x,y)`, `(x,y]`, `[x,)`, etc.) and plus ranges (`1.0+`)
- Check if winner version satisfies evicted module's version range in `guessCompatible()`

## Test plan

- [x] Added unit tests for `versionSatisfiesRange` covering the exact issue scenario (`4.2.1` in `[4.1.0,5)`)
- [x] Added test for reproduction case (`1.4.7` in `[1.3.0,)`)
- [x] All existing eviction tests pass
- [x] All `lmCore` tests pass (539 tests)

### CODE REVIEW

**Comment by calm329** [comment]
@eed3si9n Could you please review my pr?

**Comment by eed3si9n** [comment]
Not sure if you can write a scripted test to capture the output, but you can reproduce the original issue using the following build:

```scala
scalaVersion := "3.7.4"

libraryDependencies ++= Seq(
  "org.webjars.bower" % "angular" % "1.4.7",
  "org.webjars.bower" % "angular-bootstrap" % "0.14.2"
)
```

File: lm-core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala [hunk 1]
```diff
@@ -337,28 +337,45 @@ object EvictionWarning {
...
+        // This handles cases like [4.1.0,5) where 4.2.1 would be within range
+        val winnerSatisfiesRequestedRange: Boolean = winnerOpt match {
+          case Some(winner) =>
+            r.callers.exists { caller =>
+              caller.requestedRevision match {
+                case Some(reqRev) if VersionRange.isVersionRange(reqRev) =>
+                  VersionRange.versionSatisfiesRange(winner.revision, reqRev)
+                case _ => false
+              }
+            }
```
Comment (eed3si9n) [inline lm-core/src/main/scala/sbt/librarymanagement/EvictionWarning.scala]: `r.module.revision` is already the version number reported by Coursier, which should have the version range, I think. I'm not sure if we need caller.requestedRevision, which won't be available for Coursier anyway?

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by calm329** [comment]
@eed3si9n I think the current CI check got stuck. Could you re-run it please?

**Comment by eed3si9n** [comment]
Rerunning now.
