### PR TITLE
Monitor project build sources

### LINKED ISSUE #5061: Build source monitoring is does not track sub/build.sbt files
The new feature in sbt 1.3.0 that build sources are monitored and sbt can optionally reload the build when sources change doesn't work with nested projects.

### PR DESCRIPTION
**Pull request by eatkins**
In sbt 1.3.0, we only monitor build sources in the root project
directory and the root project meta build directory. This commit adds
these inputs for each project.

Fixes https://github.com/sbt/sbt/issues/5061.

### CODE REVIEW

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -371,13 +370,14 @@ object Defaults extends BuildCommon {
       }).value
   )
 
-  def paths = Seq(
+  def paths: Seq[Setting[_]] = Seq(
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala:375]:
```suggestion
  // included into JvmPlugin.projectSettings
  def paths: Seq[Setting[_]] = Seq(
```

File: main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala [hunk 2]
```diff
@@ -59,7 +58,7 @@ private[sbt] object CheckBuildSources {
   }
   private[sbt] def buildSourceFileInputs: Def.Initialize[Seq[Glob]] = Def.setting {
     if (onChangedBuildSource.value != IgnoreSourceChanges) {
-      val baseDir = (LocalRootProject / baseDirectory).value
+      val baseDir = baseDirectory.value
       val sourceFilter = "*.{sbt,scala,java}"
       val projectDir = baseDir / "project"
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: Wouldn't this end up tracking `sub/project/*.scala`? Maybe metabuild source inputs needs to be split up, and added back at global level.

File: main/src/main/scala/sbt/Defaults.scala [hunk 3]
```diff
@@ -371,13 +370,14 @@ object Defaults extends BuildCommon {
...
     baseDirectory := thisProject.value.base,
     target := baseDirectory.value / "target",
     historyPath := (historyPath or target(t => Option(t / ".history"))).value,
     sourceDirectory := baseDirectory.value / "src",
     sourceManaged := crossTarget.value / "src_managed",
-    resourceManaged := crossTarget.value / "resource_managed"
+    resourceManaged := crossTarget.value / "resource_managed",
+    Scope.Global / checkBuildSources / fileInputs ++= CheckBuildSources.buildSourceFileInputs.value,
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala]:
```suggestion
    // lhs generates *.sbt files that needs to be tracked per subprojects
    Scope.Global / checkBuildSources / fileInputs ++= CheckBuildSources.buildSourceFileInputs.value,
```

**Review by eed3si9n — CHANGES_REQUESTED** [review]
some comments.

File: main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala (hunk 2 above)
Comment (eatkins) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: Yeah, that's intentional. In the project directory, top level scala files are allowed in compile.

Comment (eatkins) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: It's common for builds to have something like project/Dependencies.scala and then refer to object Dependencies in the top level build.sbt.

Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: I understand you need to track `project/*.scala`. There are two axes to traverse. One is subprojects, the other is metabuild. Currently those two concerns are mixed, so you end up with `sub/project/*.scala`.

Comment (eatkins) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: Right, but why can't my subproject also have a metabuild?

Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: A metabuild can have subprojects (, which I believe this code still doesn't track), but a metabuild of a subproject doesn't make sense since "subprojects" are members of the proper build, and only a build can have its meta-build.

Comment (eatkins) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: I don't know the answer, but that appears to be true. I guess I misunderstood how recursion works with builds.

Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: To put it into examples:

```
project/D.scala                // track
project/plugins.sbt            // track
project/foo/A.scala            // track (bonus points)
project/src/main/scala/B.scala // track
project/project/C.scala        // track
project/project/plugins.sbt    // track
build.sbt                      // track
sub/build.sbt                  // track
sub/project/E.scala            // do not track
```

Comment (eatkins) [reply main/src/main/scala/sbt/internal/nio/CheckBuildSources.scala:66]: I can't get the bonus points without degrading performance because searching for all of the scala files would require listing the target directory which can be extremely slow. Otherwise, I think that this PR now handles the other cases.

File: main/src/main/scala/sbt/Defaults.scala (hunk 1 above)
Comment (eatkins) [reply main/src/main/scala/sbt/Defaults.scala:375]: Applied with slight rewording.

File: main/src/main/scala/sbt/Defaults.scala [hunk 4]
```diff
@@ -371,13 +371,16 @@ object Defaults extends BuildCommon {
...
+  def paths: Seq[Setting[_]] = Seq(
     baseDirectory := thisProject.value.base,
     target := baseDirectory.value / "target",
     historyPath := (historyPath or target(t => Option(t / ".history"))).value,
     sourceDirectory := baseDirectory.value / "src",
     sourceManaged := crossTarget.value / "src_managed",
-    resourceManaged := crossTarget.value / "resource_managed"
+    resourceManaged := crossTarget.value / "resource_managed",
+    // Adds subproject build.sbt files to the global list of build files to monitor
+    Scope.Global / checkBuildSources / fileInputs += baseDirectory.value.toGlob / "*.sbt"
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala:383]: 👍

**Review by eed3si9n — DISMISSED** [review]
LGTM. thanks @eatkins

**Review by eed3si9n — APPROVED** [review]
