### PR TITLE
[2.x] Fix error with "-language:postfixOps"

### LINKED ISSUE #9149: [2.x] `-language:postfixOps` in project/plugins.sbt does not work
### project/plugin.sbt 

```scala
scalacOptions += "-language:postfixOps"
```

### build.sbt 

```scala
TaskKey[Int]("foo") := (Seq(1) head)
```

### project/build.properties 

```properties
sbt.version=2.0.0-RC12
```

## problem

```
[error] [${BASE}/build.sbt]:1: ',' or ')' expected, but identifier found
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

## notes

- https://github.com/sbt/sbt/blob/0f2c97345256a63873691429554864f038b2fa9b/build.sbt#L1236
- https://github.com/sbt/sbt/issues/9010

### PR DESCRIPTION
**Pull request by xuwei-k**
- fix https://github.com/sbt/sbt/issues/9149

### CODE REVIEW

File: buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala [hunk 1]
```diff
@@ -135,10 +139,21 @@ private[sbt] object SbtParser:
...
-  private[sbt] final class ParseDriver extends Driver:
+
+  private val parseDriverCache: TrieMap[Seq[String], ParseDriver] =
+    TrieMap.empty
+
+  private[sbt] def defaultGlobalForParserWithOption(options: Seq[String]): ParseDriver =
+    parseDriverCache.getOrElseUpdate(
+      options,
+      Retry(ParseDriver(options.toList))
+    )
```
Comment (xuwei-k) [inline buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala:150]: I'm not sure we should cache `ParseDriver` instances.

Comment (eed3si9n) [reply buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala:150]: Maybe add a test to parse something random 1000 times via HedgeHog, and compare how fast it runs?

**Comment by xuwei-k** [comment]
Can't run early initialization thread if there are options 🤔 

- https://github.com/sbt/sbt/pull/7938

**Review by eed3si9n — APPROVED** [review]
Thanks!
