### PR TITLE
[sbt 0.13] Fix logging + clean concurrency issue

### LINKED ISSUE #3811: Backport fix for "No such file or directory" on clean to 0.13
This is a backport request via the Lightbend subscription.

- https://github.com/sbt/sbt/issues/2156
- https://github.com/sbt/sbt/pull/3093

### PR DESCRIPTION
**Pull request by dwijnand**
_This is a backport request via the Lightbend subscription._

Backport of #3093

Fixes #3811

### CODE REVIEW

File: main/src/main/scala/sbt/Keys.scala [hunk 1]
```diff
@@ -107,8 +107,8 @@ object Keys {
   val classDirectory = SettingKey[File]("class-directory", "Directory for compiled classes and copied resources.", AMinusSetting)
   @deprecated("Use the cacheDirectory provided by streams.", "0.13.0")
   val cacheDirectory = SettingKey[File]("cache-directory", "Directory used for caching task data.", BMinusSetting)
-  val cleanFiles = SettingKey[Seq[File]]("clean-files", "The files to recursively delete during a clean.", BSetting)
-  val cleanKeepFiles = SettingKey[Seq[File]]("clean-keep-files", "Files to keep during a clean.", CSetting)
+  val cleanFiles = TaskKey[Seq[File]]("clean-files", "The files to recursively delete during a clean.", BSetting)
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Keys.scala]: bincompat?
I think we need to introduce a new key.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

**Review by eed3si9n — APPROVED** [review]

File: main/src/main/scala/sbt/Keys.scala [hunk 2]
```diff
@@ -108,7 +108,8 @@ object Keys {
   @deprecated("Use the cacheDirectory provided by streams.", "0.13.0")
   val cacheDirectory = SettingKey[File]("cache-directory", "Directory used for caching task data.", BMinusSetting)
   val cleanFiles = SettingKey[Seq[File]]("clean-files", "The files to recursively delete during a clean.", BSetting)
```
Comment (retronym) [inline main/src/main/scala/sbt/Keys.scala:110]: Should this be deprecated? The Scala build customized this setting but since upgrading to 0.13.17 it seems to be ignored and `clean` doesn't clean our custom target directories of `build/quick/classes/<subproject>`

Comment (eed3si9n) [reply main/src/main/scala/sbt/Keys.scala:110]: Yes. The setting is no longer used.
