### PR TITLE
[2.x] fix: Fix consoleProject for Scala 3

### LINKED ISSUE #7722: [2.x] `consoleProject` does not work
## steps

`build.sbt`

```scala
scalaVersion := "3.5.1"
```

`project/build.properties`

```
sbt.version=2.0.0-M2
```

run `sbt consoleProject`

https://github.com/xuwei-k/sbt-2-console-project-bug/commit/ae1f012d46b0d7108ad6955c4fe57cba33ec2e79

## problem

https://github.com/xuwei-k/sbt-2-console-project-bug/actions/runs/11188570599/job/31107559844#step:4:31
https://github.com/xuwei-k/sbt-2-console-project-bug/commit/b481dbc4730787d2a9eccd162593662cd6d1dbb0

<details>
<summary>click expand</summary>

```
[info] Non-compiled module 'scala3-sbt-bridge' for Scala 3.3.3. Compiling...
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Action.java:5:37 -
5 |final public class Action implements xsbti.Action {
  |                                     ^^^^^
  |                                     Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/WorkspaceEdit.java:7:44 
7 |final public class WorkspaceEdit implements xsbti.WorkspaceEdit {
  |                                            ^^^^^
  |                                            Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:8:13 
8 |import xsbti.AnalysisCallback;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:9:13 
9 |import xsbti.Logger;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:10:13 
10 |import xsbti.Reporter;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:11:13 
11 |import xsbti.VirtualFile;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:12:21 
12 |import xsbti.compile.CompileProgress;
   |                     ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:13:21 
13 |import xsbti.compile.CompilerInterface2;
   |                     ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:14:21 
14 |import xsbti.compile.DependencyChanges;
   |                     ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridge.java:15:21 
15 |import xsbti.compile.Output;
   |                     ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridgeDriver.java:21:13 
21 |import xsbti.Problem;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridgeDriver.java:22:13 
22 |import xsbti.*;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/CompilerBridgeDriver.java:23:21 
23 |import xsbti.compile.Output;
   |                     ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/DelegatingReporter.java:19:13 
19 |import xsbti.Position;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/DelegatingReporter.java:20:13 
20 |import xsbti.Severity;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/DelegatingReporter.java:33:28 
33 |  public DelegatingReporter(xsbti.Reporter delegate, Function<SourceFile, String> lookupVirtualFileId) {
   |                            ^^^^^
   |                            Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/DelegatingReporter.java:26:10 
26 |  private xsbti.Reporter delegate;
   |          ^^^^^
   |          Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/DiagnosticCode.java:5:45 
5 |final public class DiagnosticCode implements xsbti.DiagnosticCode {
  |                                             ^^^^^
  |                                             Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/FallbackVirtualFile.java:14:41 
14 |public class FallbackVirtualFile extends xsbti.BasicVirtualFileRef implements xsbti.VirtualFile {
   |                                         ^^^^^
   |                                         Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/FallbackVirtualFile.java:14:78 
14 |public class FallbackVirtualFile extends xsbti.BasicVirtualFileRef implements xsbti.VirtualFile {
   |                                                                              ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/FallbackPathBasedFile.java:10:74 
10 |public class FallbackPathBasedFile extends FallbackVirtualFile implements xsbti.PathBasedFile {
   |                                                                          ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:11:29 
11 |  public IncrementalCallback(xsbti.AnalysisCallback delegate, Function<SourceFile, xsbti.VirtualFile> asVirtualFile) {
   |                             ^^^^^
   |                             Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:11:83 
11 |  public IncrementalCallback(xsbti.AnalysisCallback delegate, Function<SourceFile, xsbti.VirtualFile> asVirtualFile) {
   |                                                                                   ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:8:16 
8 |  private final xsbti.AnalysisCallback delegate;
  |                ^^^^^
  |                Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:9:37 
9 |  private final Function<SourceFile, xsbti.VirtualFile> asVirtualFile;
  |                                     ^^^^^
  |                                     Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:17:41 
17 |  public void api(SourceFile sourceFile, xsbti.api.ClassLike classApi) {
   |                                         ^^^^^
   |                                         Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:37:72 
37 |  public void usedName(String className, String name, java.util.EnumSet<xsbti.UseScope> useScopes) {
   |                                                                        ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:42:140 
42 |  public void binaryDependency(java.nio.file.Path onBinaryEntry, String onBinaryClassName, String fromClassName, SourceFile fromSourceFile, xsbti.api.DependencyContext context) {
   |                                                                                                                                            ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/IncrementalCallback.java:47:74 
47 |  public void classDependency(String onClassName, String sourceClassName, xsbti.api.DependencyContext context) {
   |                                                                          ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/InterfaceCompileFailed.java:6:13 
6 |import xsbti.Problem;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/InterfaceCompileFailed.java:8:44 
8 |public class InterfaceCompileFailed extends xsbti.CompileFailed {
  |                                            ^^^^^
  |                                            Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:14:[32](https://github.com/xuwei-k/sbt-2-console-project-bug/actions/runs/11188570599/job/31107559844#step:4:33) 
14 |  public OldIncrementalCallback(xsbti.AnalysisCallback delegate) {
   |                                ^^^^^
   |                                Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:12:16 
12 |  private final xsbti.AnalysisCallback delegate;
   |                ^^^^^
   |                Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:26:41 
26 |  public void api(SourceFile sourceFile, xsbti.api.ClassLike classApi) {
   |                                         ^^^^^
   |                                         Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:48:72 
48 |  public void usedName(String className, String name, java.util.EnumSet<xsbti.UseScope> useScopes) {
   |                                                                        ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:54:140 
54 |  public void binaryDependency(java.nio.file.Path onBinaryEntry, String onBinaryClassName, String fromClassName, SourceFile fromSourceFile, xsbti.api.DependencyContext context) {
   |                                                                                                                                            ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/OldIncrementalCallback.java:59:74 
59 |  public void classDependency(String onClassName, String sourceClassName, xsbti.api.DependencyContext context) {
   |                                                                          ^^^^^
   |                                                        Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/PositionBridge.java:11:13 
11 |import xsbti.Position;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:17:13 
17 |import xsbti.Position;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:18:13 
18 |import xsbti.Severity;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:19:13 
19 |import xsbti.VirtualFile;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:22:[38](https://github.com/xuwei-k/sbt-2-console-project-bug/actions/runs/11188570599/job/31107559844#step:4:39) 
22 |final public class Problem implements xsbti.Problem {
   |                                      ^^^^^
   |                                      Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:67:18 
67 |  public Optional<xsbti.DiagnosticCode> diagnosticCode() {
   |                  ^^^^^
   |                  Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/Problem.java:83:14 
83 |  public List<xsbti.Action> actions() {
   |              ^^^^^
   |              Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/TextEdit.java:3:13 
3 |import xsbti.Position;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/TextEdit.java:5:[39](https://github.com/xuwei-k/sbt-2-console-project-bug/actions/runs/11188570599/job/31107559844#step:4:40) 
5 |final public class TextEdit implements xsbti.TextEdit {
  |                                       ^^^^^
  |                                       Not found: xsbti
  |
  | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/dotty/tools/xsbt/WorkspaceEdit.java:5:13 
5 |import xsbti.TextEdit;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CachedCompilerImpl.java:6:13 -
6 |import xsbti.*;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CachedCompilerImpl.java:7:21 -
7 |import xsbti.compile.*;
  |                     ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CompilerInterface.java:6:13 --
6 |import xsbti.AnalysisCallback;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CompilerInterface.java:7:13 --
7 |import xsbti.Logger;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CompilerInterface.java:8:13 --
8 |import xsbti.Reporter;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/CompilerInterface.java:9:21 --
9 |import xsbti.compile.*;
  |                     ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/ConsoleInterface.java:10:13 --
10 |import xsbti.Logger;
   |             ^
   |       value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/DottydocRunner.java:6:13 -----
6 |import xsbti.Logger;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/DottydocRunner.java:7:13 -----
7 |import xsbti.Severity;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/DottydocRunner.java:28:52 ----
28 |  public DottydocRunner(String[] args0, Logger log, xsbti.Reporter delegate) {
   |                                                    ^^^^^
   |                                                    Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/DottydocRunner.java:26:16 ----
26 |  private final xsbti.Reporter delegate;
   |                ^^^^^
   |                Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/ScaladocInterface.java:6:13 --
6 |import xsbti.Logger;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E008] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/ScaladocInterface.java:7:13 --
7 |import xsbti.Reporter;
  |             ^
  |         value xsbti is not a member of <root> - did you mean _root_.xsbt?
-- [E006] Not Found Error: /tmp/sbt_8a7f4aac/xsbt/ScaladocInterface.java:10:[45](https://github.com/xuwei-k/sbt-2-console-project-bug/actions/runs/11188570599/job/31107559844#step:4:46) -
10 |  public void run(String[] args, Logger log, xsbti.Reporter delegate) {
   |                                             ^^^^^
   |                                             Not found: xsbti
   |
   | longer explanation available when compiling with `-explain`
61 errors found
[info] Attempting to fetch org.scala-lang:scala3-sbt-bridge:3.3.3.
[error] (consoleProject) Error compiling the sbt component 'scala3-sbt-bridge'
```

</details>

### PR DESCRIPTION
**Pull request by eureka0928**
## Summary
- Work around Scala 3 compiler bridge not implementing REPL binding injection ([scala/scala3#5069](https://github.com/scala/scala3/issues/5069))
- Store `currentState`, `extracted`, and `cpHelpers` in a static holder (`ConsoleProjectBindings`) and inject them via `initialCommands` as `val` definitions
- Original `bindings` are still passed to `Console` to preserve Scala 2 backward compatibility
- Clean up holder references after REPL session exits

Fixes #7722

## Test plan
- [x] Un-pend and enhance `project/scala3-console-project` scripted test — asserts all three bindings are non-null in the Scala 3 REPL
- [ ] `sbt scripted project/scala3-console-project`
- [ ] Manual `sbt consoleProject` in a Scala 3 project — verify `currentState`, `extracted`, `cpHelpers` are accessible

### CODE REVIEW

**Comment by fury0928** [comment]
@eed3si9n I already made a branch 2 weeks ago and here is my PR
Thank you for your time and review

**Comment by eed3si9n** [comment]
scripted test is failing with `java.lang.NoClassDefFoundError: dotty/tools/repl/ReplDriver`:

```
2026-04-12T07:19:49.8969895Z [info] [0m[[0m[31merror[0m] [0m[0mjava.lang.NoClassDefFoundError: dotty/tools/repl/ReplDriver[0m
2026-04-12T07:19:49.8971125Z [info] [0m[[0m[31merror[0m] [0m[0m	at xsbt.ConsoleInterface.run(ConsoleInterface.java:43)[0m
2026-04-12T07:19:49.8972747Z [info] [0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)[0m
```

This might be related to be fact that Scala 3.8 onwards repl needs additional artifacts.

**Comment by fury0928** [comment]
Hi @eed3si9n this is ready to go 😉

**Review by eed3si9n — CHANGES_REQUESTED** [review]
I locally built sbt and tested it and the binding seems to be `null`:

```scala
sbt:run> consoleProject
val currentState: State = null
val extracted: Extracted = null
val cpHelpers: internal.ConsoleProject.Imports = null
Welcome to Scala 3.8.3 (17.0.12, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> currentState.toString
java.lang.NullPointerException: Cannot invoke "sbt.State.toString()" because the return value of "rs$line$2$.currentState()" is null
  ... 72 elided
```

**Comment by fury0928** [comment]
Pushed `385c5c757` to fix the null bindings.

**Root cause.** The Scala 3 REPL's `dotty.tools.repl.AbstractFileClassLoader` ends up defining its own copy of `sbt.internal.ConsoleProjectBindings` (and `sbt.State` / `sbt.Extracted`) from the sbt module jars on `unit.classpath`, instead of delegating to sbt's class loader via parent-first. Two distinct `Class` objects, so the static fields that `ConsoleProjectBindings.set` writes to are invisible to the REPL — hence the `null`s in your session. A strongly typed cast also hits `LinkageError: loader constraint violation` on `sbt.State`.

I traced this by dumping `getClass.getClassLoader` and `ProtectionDomain.getCodeSource` from both sides:

- `set()` runs in `SbtMetaBuildClassLoader` → one `ConsoleProjectBindings$` instance.
- `state()` runs in `dotty.tools.repl.AbstractFileClassLoader` → a different `ConsoleProjectBindings$`, with identity hash and null fields.

**Fix.** In `ConsoleProject.apply`, strip every jar shipping sbt core code from the runtime `ClassLoader` passed to the REPL. The jars are identified by content — any jar containing `sbt/State.class`, `sbt/Extracted.class`, `sbt/internal/ConsoleProjectBindings$.class`, or `sbt/internal/Load$.class` is excluded. The full classpath is still passed to `Console` below, so the REPL's `-classpath` (compile-time) is unchanged and the DSL types typecheck as before; only the runtime `URLClassLoader` is filtered, which forces every `sbt.*` reference inside the REPL to resolve via parent delegation and land on sbt's singleton copies.

**Test update.** `project/scala3-console-project` now sets `initialCommands` to write a marker file via `Files.writeString(path, currentState.toString.length.toString + "/" + ...)`. If any binding is null, the `toString` NPE makes the marker write abort, the REPL swallows the exception, and the subsequent `$ exists` check fails the scripted test. So the test actually verifies non-null bindings rather than just that `consoleProject` starts.

Local session on current branch — all three bindings now resolve:

```
scala> currentState
val currentState: State = State(
  configuration = sbt.internal.XMainConfiguration$ModifiedConfiguration@...,
  definedCommands = List(SimpleCommand(...), ...),
  ...)

scala> extracted
val extracted: Extracted = Extracted(
  structure = sbt.internal.BuildStructure@...,
  session = SessionSettings(currentBuild = file:/tmp/sbt_.../, ...),
  ...)

scala> cpHelpers
val cpHelpers: sbt.internal.ConsoleProject.Imports = sbt.internal.ConsoleProject$Imports@...
```

PTAL.

**Comment by fury0928** [comment]
@eed3si9n follow up on this
Thank you

**Review by eed3si9n — CHANGES_REQUESTED** [review]
`currentState` is hooked up, but `compile` doesn't seem to work:

```scala
scala> compile
java.lang.LinkageError: loader constraint violation: when resolving method 'sbt.TaskKey sbt.Keys$.compile()' the class loader dotty.tools.repl.AbstractFileClassLoader @5e313452 of the current class, rs$line$4$, and the class loader sbt.internal.MetaBuildLoader @366647c2 for the method's defining class, sbt/Keys$, have different Class objects for the type sbt/TaskKey used in the signature (rs$line$4$ is in unnamed module of loader dotty.tools.repl.AbstractFileClassLoader @5e313452, parent loader sbt.internal.inc.classpath.ClasspathFilter @44bd2ad9; sbt.Keys$ is in unnamed module of loader sbt.internal.MetaBuildLoader @366647c2, parent loader sbt.internal.FullScalaLoader @482bce4f)
  ... 72 elided
```

**Comment by fury0928** [comment]
Fixed in 9cfdfb4dc.

**Root cause of the `compile` failure**

My previous fix filtered jars containing a small set of marker classes (`sbt/State.class`, `sbt/Extracted.class`, `sbt/internal/Load$.class`, `sbt/internal/ConsoleProjectBindings$.class`). That removed `main_3.jar` and `command_3.jar` from the REPL's runtime classloader so the bindings worked, but `sbt.TaskKey` lives in `main-settings_3.jar`, which had none of those markers. The REPL's `AbstractFileClassLoader` happily defined its own copy of `sbt.TaskKey`, and any reference from REPL code to a method whose signature mentions `TaskKey` (like `sbt.Keys.compile`) hit the loader constraint violation you saw.

**Fix**

Switch the filter to use `META-INF/MANIFEST.MF`'s `Implementation-Vendor-Id`, which every `org.scala-sbt` artifact sets to `org.scala-sbt`. That uniformly catches `main`, `main-settings`, `command`, `io`, `util-*`, `protocol`, `tasks*`, etc., without enumerating individual classes, and is robust against future modules.

**Test update**

The `project/scala3-console-project` scripted test now also references `sbt.Keys.compile` from `Global / initialCommands`, so any future regression that re-introduces the loader-constraint failure aborts the REPL initial commands, the marker file never gets written, and `$ exists` fails.

Locally:

\`\`\`
scala> _compileKey
val res0: sbt.TaskKey[xsbti.compile.CompileAnalysis] = TaskKey(This / This / This / compile)
\`\`\`

and `sbt scripted project/scala3-console-project` is green.

**Comment by fury0928** [comment]
@eed3si9n would you review once more?
Thanks!

**Comment by fury0928** [comment]
@xuwei-k would you review this please?
Thank you

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Still getting LinkageError on some things:

```scala
scala> (Compile / compile).eval
val res5: xsbti.compile.CompileAnalysis = Analysis: 2 Scala sources, 3 classes, 1 binary dependency

scala> (Compile / run).toTask(" ")
java.lang.LinkageError: loader constraint violation: when resolving method 'sbt.internal.util.Init$Initialize sbt.TaskKey.zipWith(sbt.internal.util.Init$Initialize, scala.Function2)' the class loader dotty.tools.repl.AbstractFileClassLoader @4bdb873d of the current class, rs$line$9$, and the class loader sbt.internal.MetaBuildLoader @2e222612 for the method's defining class, sbt/TaskKey, have different Class objects for the type scala/Function2 used in the signature (rs$line$9$ is in unnamed module of loader dotty.tools.repl.AbstractFileClassLoader @4bdb873d, parent loader sbt.internal.inc.classpath.ClasspathFilter @64fc9078; sbt.TaskKey is in unnamed module of loader sbt.internal.MetaBuildLoader @2e222612, parent loader sbt.internal.FullScalaLoader @3246fb96)
  ... 72 elided
```

**Comment by fury0928** [comment]
@eed3si9n thanks for the repro — that one was the actual root cause for the `(Compile / run).toTask(" ")` failure. Pushed `6304d738f`.

**Root cause:** Scala 3.8 introduced bytecode interrupt instrumentation in `dotty.tools.repl.AbstractFileClassLoader`, on by default. Its `loadClass` reads each class's bytes from the parent loader via `getResourceAsStream` and `defineClass`-es them a *second* time inside the REPL loader — duplicating every `sbt.*` and `scala.*` class touched from the REPL. Filtering `unit.classpath` couldn't help because the duplicate copy is read straight from the parent.

**Fix:** Pass `-Xrepl-interrupt-instrumentation:local` to the consoleProject REPL on Scala 3.8+. In `local` mode the loader skips re-defining classpath classes and falls through to standard parent-first delegation, so REPL code sees the same singleton `sbt.TaskKey` / `scala.Function2` as the surrounding sbt process. I picked `local` over `false` so Ctrl+C still works on long-running REPL expressions like `(Compile / compile).eval`. The flag is gated on a version check (it doesn't exist on 3.7 and earlier).

**Test:** Upgraded `project/scala3-console-project` to scala 3.8.3 (which is where the failure reproduces — 3.7.4 uses the older AFClassLoader without instrumentation, so the previous version of the test never actually exercised this path) and made the REPL initial commands run `_compileKey.zipWith(_compileKey)((_, _) => 0)` — the exact `TaskKey.zipWith(_, scala.Function2)` call from your stack trace. The scripted test now fails fast on this class of regression instead of relying on manual REPL inspection.

Verified locally: `./sbt 'scripted project/scala3-console-project'`, `scalafmtCheckAll`, `mainProj/mimaReportBinaryIssues` all clean.

File: main/src/main/scala/sbt/internal/ConsoleProject.scala [hunk 1]
```diff
@@ -86,22 +88,120 @@ object ConsoleProject:
...
+    //      "bad option" warning.
+    //
+    // The full classpath is still passed to `Console` below so the REPL's
+    // compile-time classpath is unchanged.
+    val runtimeClasspath = unit.classpath.filterNot(isSbtModuleJar)
+    val loader = ClasspathUtil.makeLoader(runtimeClasspath, si, tempDir)
+    val replOptions =
+      if needsInterruptInstrumentationOptOut(si.version) then
+        "-Xrepl-interrupt-instrumentation:local" +: options
+      else options
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/ConsoleProject.scala:139]: Thanks for the detective work on this.

**Review by eed3si9n — APPROVED** [review]
