### PR TITLE
Fixes -error not suppressing startup logs

### LINKED ISSUE #3849: "early(error)" and "-error" do not suppress startup logs
## steps

1. Use sbt 1.1.0-RC4
2. Run `sbt -error` or `sbt "early(error)"`

## problem

```
[info] Loading project definition from ....
```

## expectation

I do not see info level logs.

## notes

Originally #840

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #3849

This brings back the 0.13 logic:

```scala
  def setGlobalLogLevel(s: State, level: Level.Value): State = {
    s.globalLogging.full match {
      case a: AbstractLogger => a.setLevel(level)
      case _                 => ()
    }
    s.put(BasicKeys.explicitGlobalLogLevels, true).put(Keys.logLevel.key, level)
  }
```

### CODE REVIEW

File: main/src/main/scala/sbt/internal/LogManager.scala [hunk 1]
```diff
@@ -229,8 +229,13 @@ object LogManager {
   //     s
   //   }
```
Comment (dwijnand) [inline main/src/main/scala/sbt/internal/LogManager.scala:230]: is this commented block relevant to this?

**Review by dwijnand — COMMENTED** [review]
is this just an idea, or was it manually tested to fixed the issue?

File: main/src/main/scala/sbt/internal/LogManager.scala (hunk 1 above)
Comment (mrveera) [reply main/src/main/scala/sbt/internal/LogManager.scala:230]: I think so.It is useful when you use abstract logger type but now those are managed loggers.

**Comment by eed3si9n** [comment]
> is this just an idea, or was it manually tested to fixed the issue?

Manually tested and confirmed.

File: main/src/main/scala/sbt/internal/LogManager.scala (hunk 1 above)
Comment (eed3si9n) [reply main/src/main/scala/sbt/internal/LogManager.scala:230]: Not particularly to this bug. The commented out code provides fallback to the project scoping when global settings are NOT available.

```scala
   // if global logging levels are not explicitly set, set them from project settings
```

**Review by dwijnand — APPROVED** [review]
let's go!
