### PR TITLE
Re-fix console and JLine bug

### LINKED ISSUE #3482: 1.0.{0,1,2} Opening console multiple times breaks escaping
## steps
1. Start an sbt shell
2. Type `console<enter>`
3. Type `ctrl-d` or `:q<enter>`
4. Type `console<enter>`
5. Type an arrow key or `ctrl-n`, `ctrl-p`, `ctrl-r`, etc.

## problem
Escapes are not interpreted correctly and sbt prints out garbage characters.

## expectation
Escapes are interpreted correctly and sbt does not print out garbage characters.

## notes
* I'm on a Mac using iterm 2.
* Bug doesn't exist on sbt 0.13.16

sbt version: *1.0.0*, *1.0.1*

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #3482 take 3

There are two bugs related REPL and JLine.
1. JLine getting disabled (up arrow not working) on the second run of `console` task.
2. Typed characters not showing up even on the `console` task.

The first issue was fixed by #4054 which added `t.init`. When I noticed the second problem, I fixed it in #4082 (adds `t.restore`) but undid the first fix. This attempts to fix both the issues.

### notes

I confirmed using Scala 2.12.3, 2.12.4, and 2.12.5.

### CODE REVIEW

File: main-actions/src/main/scala/sbt/Console.scala [hunk 1]
```diff
@@ -41,7 +41,8 @@ final class Console(compiler: AnalyzingCompiler) {
       implicit log: Logger): Try[Unit] = {
     def console0() =
       compiler.console(classpath, options, initialCommands, cleanupCommands, log)(loader, bindings)
-    JLine.usingTerminal { _ =>
+    JLine.usingTerminal { t =>
+      t.init
```
Comment (dwijnand) [inline main-actions/src/main/scala/sbt/Console.scala:45]: `usingTerminal` is (from https://github.com/sbt/sbt/blob/v1.1.4/internal/util-complete/src/main/scala/sbt/internal/util/LineReader.scala):

```scala
  def usingTerminal[T](f: jline.Terminal => T): T =
    withTerminal { t =>
      t.restore
      val result = f(t)
      t.restore
      result
    }
```

(`withTerminal` ensures synchronised access to the terminal)

So this does `t.restore`, `t.init`, run console, `t.restore`.

Is that right?

Comment (eed3si9n) [reply main-actions/src/main/scala/sbt/Console.scala:45]: Yea. We need both `t.restore` *and* `t.init`, it seems.

Comment (cunei) [reply main-actions/src/main/scala/sbt/Console.scala:45]: I know nothing about jline, so a cursory search led me to the canonical https://github.com/jline/jline2/issues/210 and the jruby thread. If calling both restore and init works around the problem, that looks ok to me I suppose. The API docs offer no help regarding those calls. However, nosing around the jline source I found:
```
    public void reset() throws Exception {
        restore();
        init();
    }
```
which suggests the combination is indeed the right one.
https://github.com/jline/jline2/blob/master/src/main/java/jline/TerminalSupport.java#L65

**Review by cunei — APPROVED** [review]

**Review by dwijnand — APPROVED** [review]
3rd times the charm. ☘️
