### PR TITLE
[1.2.x] Ignore files in scripted group dirs

### LINKED ISSUE #4457: Scripted test runners should not consider non-folder elements
Placing a plain file (e.g. `README.md`) on `src/sbt-test/test-group` causes the execution of the `scripted` task to fail:

```

Running test-group / some-valid-test-folder
Running test-group / README.md
[trace] Stack trace suppressed: run last SBT-Plugin/*:scripted for the full output.
[error] (SBT-Plugin/*:scripted) sbt.internal.io.ResourcesException: Resource directory 'README.md' in group 'shutdown' not found.
[error] Total time: 100 s, completed Nov 21, 2018 1:15:21 PM
```

See https://github.com/sbt/sbt/blob/develop/scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala#L56-L76

### PR DESCRIPTION
**Pull request by dwijnand**
Scripted tests, in src/sbt-test/<group>/<name> blow up if <name> is a
plain file.  Filter them out.

Fixes #4457

### CODE REVIEW

**Comment by dwijnand** [comment]
@eed3si9n WDYT?

**Review by eed3si9n — APPROVED** [review]
LGTM

File: scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala [hunk 1]
```diff
@@ -53,7 +53,11 @@ final class ScriptedTests(
   ): Seq[TestRunner] = {
 
     // Test group and names may be file filters (like '*')
-    for (groupDir <- (resourceBaseDirectory * group).get; nme <- (groupDir * name).get) yield {
+    for {
+      groupDir <- (resourceBaseDirectory * group).get
+      nme <- (groupDir * name).get
+      if !(nme.isFile)
```
Comment (eed3si9n) [inline scripted-sbt-redux/src/main/scala/sbt/scriptedtest/ScriptedTests.scala:59]: This is great. Nice and simple fix.

**Comment by ignasi35** [comment]
Thanks @dwijnand !

**Comment by dwijnand** [comment]
np
