### PR TITLE
[2.x] Fix duplicate compiler bridge jar in ZincComponentManager

### LINKED ISSUE #7975: [1.x] Flaky CI: ` sbt.internal.inc.InvalidComponent`
https://github.com/sbt/sbt/actions/runs/12509225049/job/34898406822

```
[info] welcome to sbt 1.10.6 (Eclipse Adoptium Java 21.0.5)
[info] loading settings for project sbt-build from plugins.sbt...
[info] loading project definition from /home/runner/work/sbt/sbt/project
[info] compiling 10 Scala sources to /home/runner/work/sbt/sbt/project/target/scala-2.12/sbt-1.0/classes ...
[error] ## Exception when compiling 10 sources to /home/runner/work/sbt/sbt/project/target/scala-2.12/sbt-1.0/classes
[error] sbt.internal.inc.InvalidComponent: Expected single file for component 'org.scala-sbt-compiler-bridge_2.12-1.10.5-bin_2.12.20__65.0', found: /home/runner/.sbt/boot/scala-2.12.20/org.scala-sbt/sbt/1.10.6/org.scala-sbt-compiler-bridge_2.12-1.10.5-bin_2.12.20__65.0/org.scala-sbt-compiler-bridge_2.12-1.10.5-bin_2.12.20__65.0-1.10.5_20241130T035052.jar, /home/runner/.sbt/boot/scala-2.12.20/org.scala-sbt/sbt/1.10.6/org.scala-sbt-compiler-bridge_2.12-1.10.5-bin_2.12.20__65.0/org.scala-sbt-compiler-bridge_2.12-1.10.5-bin_2.12.20__65.0.jar
[error] sbt.internal.inc.ZincComponentManager.invalid(ZincComponentManager.scala:94)
[error] sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:75)
[error] sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:227)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:68)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:75)
[error] sbt.internal.inc.AnalyzingCompiler.getDualLoader(AnalyzingCompiler.scala:354)
[error] sbt.internal.inc.AnalyzingCompiler.getCompilerLoader(AnalyzingCompiler.scala:343)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:87)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:196)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:252)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:214)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:5[42](https://github.com/sbt/sbt/actions/runs/12509225049/job/34898406822#step:15:43))
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3(Incremental.scala:178)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3$adapted(Incremental.scala:176)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:454)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:117)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:265)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:409)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:496)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:396)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:496)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:[43](https://github.com/sbt/sbt/actions/runs/12509225049/job/34898406822#step:15:44)3)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2[44](https://github.com/sbt/sbt/actions/runs/12509225049/job/34898406822#step:15:45)2)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2392)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:41)
[error] sbt.internal.io.Retry$.apply(Retry.scala:47)
[error] sbt.internal.io.Retry$.apply(Retry.scala:29)
[error] sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:41)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2390)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] java.base/java.lang.Thread.run(Thread.java:1583)
```

Above failure rarely happens, but does happen sometimes.

### PR DESCRIPTION
**Pull request by since-2017-hub**
### **Summary**

Fixes an intermittent InvalidComponent error in `ZincComponentManager#file()` caused by duplicate compiler bridge JARs in the component directory.
The issue occurs due to a race condition:

1. update() restores a file from the secondary cache using the stamped filename (e.g. `compiler-bridge-1.10.5_20241130T035052.jar`) and registers it via `defineComponent`, which copies that file name into the component directory.
2. Meanwhile, primary compilation calls `define()` with the canonical name (`compiler-bridge.jar`).
This leaves two JARs for the same component, causing `file() `to call `invalid()` and throw.

### **Changes**
`ZincComponentManager#update()`
Before writing to the component directory, clear any existing files in it, then copy the secondary cache file using the canonical name ($id.jar). This prevents stale stamped-name files from accumulating.
`ZincComponentManager#file()`
When multiple files are found for a component, select the canonical one ($id.jar), delete the extras, and emit a warning rather than throwing. This makes the method self-healing if duplicates already exist.

### **Verification**

- [x]  Reproduced the problem by inspecting the race condition code path
- [x]  Confirmed the fix compiles: sbt compile
- [x]  Ran formatting: sbt scalafmtAll
- [x]  Ran unit tests: sbt zincLmIntegration/test
- [x]  Checked binary compatibility: sbt mimaReportBinaryIssues

Closes #7975

I just signed to Scala CLA.

### CODE REVIEW

File: zinc-lm-integration/src/main/scala/sbt/internal/inc/ZincComponentManager.scala [hunk 1]
```diff
@@ -100,9 +108,13 @@ class ZincComponentManager(
...
-      if (file.exists) {
-        define(id, Seq(file))
+      val secondary = secondaryCacheFile(id, dir)
+      if (secondary.exists) {
+        IO.withTemporaryDirectory { tmp =>
+          val bridgeJar = new File(tmp, s"$id.jar")
+          IO.copyFile(secondary, bridgeJar)
+          define(id, Seq(bridgeJar))
+        }
       }
```
Comment (eed3si9n) [inline zinc-lm-integration/src/main/scala/sbt/internal/inc/ZincComponentManager.scala:130]: Do we know the root cause of the error? I don't know if it's a good idea to introduce a temp directory copying for an error that rarely happens, and mostly on CI.

Comment (since-2017-hub) [reply zinc-lm-integration/src/main/scala/sbt/internal/inc/ZincComponentManager.scala:130]: Yes, the root cause is in `DefaultComponentProvider.defineComponent:`

```
override def defineComponent(componentID: String, files: Array[File]): Unit =
  files.foreach(f => IO.copyFile(f, targetDir / componentID / f.getName))
```

It preserves the source file's name. The secondary cache stores jars with a stamped name like id-1.10.5_20241130T035052.jar, so when update() called define(id, Seq(file)), the stamped name was carried into the component directory. When the timestamp changes (e.g. across CI builds sharing a global Ivy cache), a second jar with a different stamped name gets added alongside the old one, and file() fails with `InvalidComponent`.

You're right that the temp directory copy was not a good approach. I've replaced it in the latest commit — now update() directly cleans stale files in the component directory and copies the secondary cache jar with a canonical name ($id.jar), no temp directory involved:

```
private def update(id: String): Unit = {
  secondaryCacheDir.foreach { dir =>
    val secondary = secondaryCacheFile(id, dir)
    if (secondary.exists) {
      val componentDir = provider.componentLocation(id)
      if (componentDir.isDirectory) {
        IO.listFiles(componentDir).foreach(IO.delete)
      }
      val canonicalJar = new File(componentDir, s"$id.jar")
      IO.copyFile(secondary, canonicalJar)
    }
  }
}
```

This makes repeated updates idempotent and prevents the duplicate jar issue at the source.

**Comment by since-2017-hub** [comment]
HI @eed3si9n 
I want to contribute to this repo. Please review again.
Thanks

File: zinc-lm-integration/src/test/scala/sbt/internal/inc/ZincComponentManagerSpec.scala [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+import java.util.concurrent.Callable
+
+import org.scalatest.flatspec.AnyFlatSpec
+import org.scalatest.matchers.should.Matchers
+import sbt.internal.util.ConsoleLogger
+import sbt.io.IO
+import sbt.io.syntax.*
+import xsbti.*
+
+class ZincComponentManagerSpec extends AnyFlatSpec with Matchers {
```
Comment (eed3si9n) [inline zinc-lm-integration/src/test/scala/sbt/internal/inc/ZincComponentManagerSpec.scala]: Could you add test using HedgeHog or Verify please? - https://github.com/sbt/sbt/blob/develop/contributing-docs/04_unit_tests.md

**Comment by since-2017-hub** [comment]
Could you please review again?

**Comment by since-2017-hub** [comment]
@eed3si9n 
image
Passed all CI test, I will update branch again. 
Could you review again asap?

**Comment by since-2017-hub** [comment]
@eed3si9n 
Could you please review again?

File: zinc-lm-integration/src/test/scala/sbt/internal/inc/ZincComponentManagerSpec.scala (hunk 2 above)
Comment (eed3si9n) [reply zinc-lm-integration/src/test/scala/sbt/internal/inc/ZincComponentManagerSpec.scala]: Sorry I wasn't clear, I meant instead of AnyFlatSpec. So could you remove this one?

**Comment by since-2017-hub** [comment]
@eed3si9n 
Please review this PR! Please

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Could you remove class ZincComponentManagerSpec?

**Comment by since-2017-hub** [comment]
@eed3si9n 
Deleted ZincComponentManagerSpec !

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution. I'm a volunteer maintainer of this repo. I monitor all notifications, so stop pinging me for review please. If this continues, I'll block you from making further contributions to this repo.

Please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Follow our AI assisted contributions guideline (please disclose AI usages in the PR description, if any)
