### PR TITLE
[2.x] fix: Skip Conflict when dependency relocations form a cycle

### LINKED ISSUE #8924: stuck trying to resolve sbt-site 1.4.1
This is the develop branch counterpart for https://github.com/sbt/sbt/issues/8917

### PR DESCRIPTION
**Pull request by bitloi**
Fixes https://github.com/sbt/sbt/issues/8924

## Problem

sbt 1.12.6+ (and sbt 2.x with Coursier 2.1.25-M24) hangs indefinitely on `update` for projects using `addSbtPlugin("com.typesafe.sbt" % "sbt-site" % "1.4.1")`. The JVM stays in a tight loop; Ctrl+C often does not stop it (see [#8917](https://github.com/sbt/sbt/issues/8917)).

## Root Cause

After resolution succeeds, `SbtUpdateReport` calls `coursier.graph.Conflict(resolution)`, which builds `DependencyTree` nodes. Each node’s `relocation` helper follows Maven/Gradle relocation metadata with tail recursion but **no cycle detection**. For sbt-site’s graph, relocation chains revisit the same coordinates, so `relocation` never terminates ([coursier#3578](https://github.com/coursier/coursier/issues/3578)).

## Solution

Add `RelocationCycleDetector`, which performs **the same single relocation step** as Coursier’s `DependencyTree.Node.relocation` and walks the implied graph. If any relocation chain would revisit a node, we **skip** `coursier.graph.Conflict` for affected configurations (resolution and artifacts are unchanged). One warning per update lists affected configuration names.

Alternatives considered: (1) bump Coursier to an unreleased fixed version — not available on Maven Central; (2) timeout around `Conflict` — nondeterministic and hides real errors; (3) vendor patched `DependencyTree` — would not affect `Conflict` in the coursier JAR (same-artifact linkage).

## Testing

- `RelocationCycleDetectorSpec`: incomplete resolution is not flagged as cyclic.
- `ResolutionSpec` property **resolve sbt-site 1.4.1 (sbt #8917)**: same resolution path as the reported bug; completes in bounded time with a non-empty classpath.

Verify:

```bash
./sbt "lmCoursier/testOnly lmcoursier.ResolutionSpec -- -z \"sbt-site\""
./sbt lmCoursier/test
```

## Before / After

- **Before**: `update` on sbt-site never finishes (infinite relocation expansion inside `Conflict`).
- **After**: Update completes; classpath is correct; users may see one warning and slightly less eviction detail for configs with cyclic relocations.

## Edge Cases Handled

- **Gradle + Maven relocation**: same branches as Coursier’s `relocation`.
- **Only when resolution is done and clean**: same guard as Coursier before applying relocations in `DependencyTree`.
- **Per-configuration**: only configs whose graph contains a relocation cycle skip conflict extraction.
- **`missingOk`**: existing `try`/`catch` unchanged.

### CODE REVIEW

**Comment by bitloi** [comment]
@eed3si9n Ready for review!

**Comment by eed3si9n** [comment]
Thanks for identifying the root cause. Could you share your findings on https://github.com/coursier/coursier/issues/3578 to help Coursier folks fix the issue as well?

**Comment by bitloi** [comment]
> Thanks for identifying the root cause. Could you share your findings on [coursier/coursier#3578](https://github.com/coursier/coursier/issues/3578) to help Coursier folks fix the issue as well?

Posted a summary on [coursier/coursier#3578](https://github.com/coursier/coursier/issues/3578) for upstream fix (cycle detection in `DependencyTree.Node.relocation`).

File: lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import scala.annotation.tailrec
+
+/**
+ * Detects cyclic Maven / Gradle relocation chains that make
+ * `coursier.graph.DependencyTree` loop forever (see sbt#8917, coursier#3578).
+ *
+ * Mirrors one step of `coursier.graph.DependencyTree.Node.relocation` so we
+ * only skip `Conflict` when Coursier would spin on the same graph.
+ */
+private[internal] object RelocationCycleDetector {
```
Comment (eed3si9n) [inline lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: Thanks for working on this! Plz follow the coding style - https://github.com/sbt/sbt/blob/develop/contributing-docs/03_coding_style.md, and use fewer braces syntax for fresh code.

File: lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+  type Mvc = CoreResolution.ModuleVersionConstraint
+
+  private def oneRelocationStep(resolution: Resolution, dep: Dependency): Option[Mvc] = {
+    val reconciledVersion =
+      resolution.reconciledVersions.get(dep.module) match {
+        case Some(v) => v
+        case None    => return None
```
Comment (eed3si9n) [inline lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: Please avoid return statements - https://github.com/sbt/sbt/blob/develop/contributing-docs/03_coding_style.md#returns

Comment (xuwei-k) [reply lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: - https://github.com/sbt/sbt/pull/8922

File: lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala (hunk 1 above)
Comment (bitloi) [reply lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: Done.

File: lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala (hunk 2 above)
Comment (bitloi) [reply lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: Fixed.

Comment (eed3si9n) [reply lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: @bitloi I still see returns

Comment (bitloi) [reply lm-coursier/src/main/scala/lmcoursier/internal/RelocationCycleDetector.scala]: Sorry, I didn't push the fix. Just pushed.

**Comment by eed3si9n** [comment]
FYI - I already closed https://github.com/sbt/sbt/issues/8917 by rolling back the Coursier version, so I've created a fresh issue https://github.com/sbt/sbt/issues/8924 for this PR.

**Comment by bitloi** [comment]
Thank you.

**Review by eed3si9n — APPROVED** [review]
Thanks @bitloi!
