### PR TITLE
[2.x] Error "Exception in thread "sbt-socket-server" java.lang.NullPointerException" on exit

### LINKED ISSUE #8538: [2.x] Error "Exception in thread "sbt-socket-server" java.lang.NullPointerException" on exit
## steps

```
exit
```

## problem

```scala
$ sbt --server
> exit
[info] shutting down sbt server
Exception in thread "sbt-socket-server" java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.io.IOException.getMessage()" is null
	at sbt.internal.server.Server$$anon$2.run(Server.scala:117)
```

## expectation

No thread errors.

## note

e.getMessage should check for `null` before calling `contains`.

https://github.com/sbt/sbt/blob/fb53925fb69e576ffc21546ae8e289bcfd309cb9/main-command/src/main/scala/sbt/internal/server/Server.scala#L113-L117

### PR DESCRIPTION
**Pull request by James-4u**
Fix NullPointerException in Server.scala when IOException.getMessage() returns null

Fixes #8538

The code was calling e.getMessage.contains() without checking if getMessage()
returns null. Changed to use Option(e.getMessage).exists() to safely handle
null values.

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=102175066

### CODE REVIEW

**Comment by SmartDever02** [comment]
requesting your review @eed3si9n 
thanks

**Comment by eed3si9n** [comment]
@SmartDever02 Thanks for the contribution. There are several permutations of `run` that can happen server-run, client-run, fork vs non-fork, so I'll try to grab this code and test it later.

**Comment by eed3si9n** [comment]
Looks like I'm seeing duplicated success logs.

## server-side run, in-process

```bash
$ sbt --server
....
sbt:aaa> run
[info] compiling 2 Scala sources to /private/tmp/aaa/target/out/jvm/scala-3.7.3/aaa/classes ...
[info] running example.main
hello
[success] elapsed time: 0 s
[success] elapsed time: 6 s, cache 26%, 7 disk cache hits, 19 onsite tasks
sbt:aaa> run
[info] running example.main
hello
[success] elapsed time: 0 s
[success] elapsed time: 0 s, cache 100%, 26 disk cache hits
```

## server-side run, `Compile / run / fork := true`

```bash
$ sbt --server
....
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 0 s
[success] elapsed time: 1 s, cache 100%, 26 disk cache hits
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 0 s
[success] elapsed time: 0 s, cache 100%, 26 disk cache hits
```

## client-side run

```bash
$ sbt --client
[info] terminate the server with `shutdown`
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 1 s, cache 100%, 26 disk cache hits
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 0 s, cache 100%, 26 disk cache hits
```

## client-side run, `Compile / run / fork := true`

```bash
$ sbt --client
[info] terminate the server with `shutdown`
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 0 s, cache 100%, 26 disk cache hits
sbt:aaa> run
[info] running (fork) example.main
hello
[success] elapsed time: 0 s, cache 100%, 26 disk cache hits
```

**Comment by James-4u** [comment]
> Looks like I'm seeing duplicated success logs.
> 
> ## server-side run, in-process
> ```shell
> $ sbt --server
> ....
> sbt:aaa> run
> [info] compiling 2 Scala sources to /private/tmp/aaa/target/out/jvm/scala-3.7.3/aaa/classes ...
> [info] running example.main
> hello
> [success] elapsed time: 0 s
> [success] elapsed time: 6 s, cache 26%, 7 disk cache hits, 19 onsite tasks
> sbt:aaa> run
> [info] running example.main
> hello
> [success] elapsed time: 0 s
> [success] elapsed time: 0 s, cache 100%, 26 disk cache hits
> ```
> 
> ## server-side run, `Compile / run / fork := true`
> ```shell
> $ sbt --server
> ....
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 0 s
> [success] elapsed time: 1 s, cache 100%, 26 disk cache hits
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 0 s
> [success] elapsed time: 0 s, cache 100%, 26 disk cache hits
> ```
> 
> ## client-side run
> ```shell
> $ sbt --client
> [info] terminate the server with `shutdown`
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 1 s, cache 100%, 26 disk cache hits
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 0 s, cache 100%, 26 disk cache hits
> ```
> 
> ## client-side run, `Compile / run / fork := true`
> ```shell
> $ sbt --client
> [info] terminate the server with `shutdown`
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 0 s, cache 100%, 26 disk cache hits
> sbt:aaa> run
> [info] running (fork) example.main
> hello
> [success] elapsed time: 0 s, cache 100%, 26 disk cache hits
> ```

let me double check

**Comment by James-4u** [comment]
@eed3si9n as I double check again, task framework has printing success message internally.
the issue was because the channel was paused which resulted in showing no success message.
I am thinking of unpausing the channel in RunUtil.scala
Does it sound okay to you? or is it sort of a hack?

[EDITED] - I think I found a better approach

**Comment by James-4u** [comment]
I pushed a fix, would you please try again

**Comment by eed3si9n** [comment]
I have a blog post I wrote about sbt 2.x's client-side run, might or might not be helpful to debug this situation - https://eed3si9n.com/sudori-part7-client-side-run-with-sbt/.

Basically sbt server creates RunInfo and sends to sbtn (native client), which shell out a Java process to run the compiled program. If unpausing channel fixes this issue we can try it, but we also want to make sure that we don't print "success" before the actual program runs client-side.

File: main/src/main/scala/sbt/internal/RunUtil.scala [hunk 1]
```diff
@@ -160,7 +187,7 @@ object RunUtil:
                 )
               case sr =>
                 (None, wrapper(() => sr.run(mainClass, cp.files, args, logger).get))
-        service.waitForTry(handle).get
+        waitForJobAndShowSuccess(handle, service, state, streams.value)
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/internal/RunUtil.scala]: Assuming that this problem happens on client-side run, the fix would have to be on the `true` side of the enclosing if expression, around line 128.

**Comment by James-4u** [comment]
I see the issue is closed, can I revert all the commits and work on different issue in this pr?
@eed3si9n

**Comment by eed3si9n** [comment]
@SmartDever02 Yea, fine by me.

**Comment by James-4u** [comment]
can you check this again? @eed3si9n 
now this pr is for fixing https://github.com/sbt/sbt/issues/8538

**Review by eed3si9n — APPROVED** [review]
lgtm

**Comment by eed3si9n** [comment]
CI failing with `[error] scalafmt: 1 files must be formatted (/home/runner/work/sbt/sbt/main-command)`
