### PR TITLE
Fixes merged ModuleID dropping configuration specification. 

### LINKED ISSUE #2002: makePom omits scope
The makePom omits `<scope>test</scope>` when there are multiple libraryDependencies with the same group + artifactId + version, but different classifiers.
## Steps
1. `git clone https://github.com/htmldoug/sbt-bug-pom-missing-scope.git`
2. `sbt makePom`
3. Open the generated pom.xml
4. Observe that the dependency entry for `"guava-tests" % "18.0" % "test" classifier "tests"` is missing a `<scope>test</scope>` element.
## Problems

The following library dependencies... 

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0"
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

... produce a pom dependency with a missing `<scope>test</scope>`.

``` xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-tests</artifactId>
    <version>18.0</version>
    <classifier>tests</classifier>
</dependency>
```
## Expectations

The dependency with configuration "test" should produce a pom entry with `<scope>test</scope>`. 
### Interaction issue?

On its own, the following produces the correct result.

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

``` xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-tests</artifactId>
    <version>18.0</version>
    <classifier>tests</classifier>
    <scope>test</scope>
</dependency>
```

It's only when you add a libraryDependency with the same group + artifactId + version in compile configuration _in addition_ to the test configuration with the classifier, that the problem occurs. 
### pom generation vs dependencyClasspath

dependencyClasspath and test:dependencyClasspath appear okay. This may be isolated to the pom generation.

```
> export dependencyClasspath
/Users/doug/.sbt/boot/scala-2.10.4/lib/scala-library.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0.jar:
/Users/doug/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar

> export test:dependencyClasspath
/code/sbt-bug-classifier-pom/target/scala-2.10/classes:
/Users/doug/.sbt/boot/scala-2.10.4/lib/scala-library.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0-tests.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0.jar:
/Users/doug/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #2002/#1500

Given a dependency graph such as:

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0"
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

previous releases of sbt would drop the Test configuration from the
classifier "tests" artifacts, and end up including the test JARs into
the Compile configuration instead of the Test configuration, which
would result in runtime error.

This fix configures the explicit artifacts into the configuration
during merge even when it says `"*"`.

/review @dwijnand, @jsuereth

### CODE REVIEW

**Comment by eed3si9n** [comment]
Codacy is complaining about `deps.head` on unit tests, but [Travis CI](https://travis-ci.org/sbt/sbt/builds/137015873) has green checkbox.

**Comment by dwijnand** [comment]
LGTM.

File: ivy/src/main/scala/sbt/ivyint/MergeDescriptors.scala [hunk 1]
```diff
@@ -87,11 +87,14 @@ private final class MergedDescriptors(a: DependencyDescriptor, b: DependencyDesc
...
-      if (aConfs == null || aConfs.isEmpty)
-        copyWithConfigurations(art, base.getModuleConfigurations)
-      else
-        art
+      val aConfs = Option(art.getConfigurations) map { _.toList }
+      // In case configuration list is "*", we should still specify the module configuration of the DependencyDescriptor
+      // otherwise the explicit specified artifacts from one dd can leak over to the other.
+      // See gh-1500, gh-2002
+      aConfs match {
+        case None | Some(Nil) | Some(List("*")) => copyWithConfigurations(art, base.getModuleConfigurations)
```
Comment (jsuereth) [inline ivy/src/main/scala/sbt/ivyint/MergeDescriptors.scala:95]: Wow, subtle....

**Comment by jsuereth** [comment]
LGTM
