### PR TITLE
[2.x] fix: Detect alias/task key name conflicts

### LINKED ISSUE #2883: Aliases should be ambiguous with keys, instead of silent win
## steps

In '~/.sbtrc', define alias c = compile.

In 'build.sbt', define a task 'c'.

## problem

Invoking 'c' will invoke the alias (compile).

## expectation

I believe this invocation should result in a failure due to ambiguity.

In a POSIX shell (eg. bash) aliases or shell functions will win over binaries, so one could argue that this behaviour is correct.

On my personal Twitter, 20/28 people (71%) agree with me that it should be ambiguous: https://twitter.com/dwijnand/status/811667915229499392

## notes

I hit this issue because sbt/sbt's actions/depends-on scripted test defines a 'c' task, but my 'c = compile' alias was being used. So expectations weren't meant.

### PR DESCRIPTION
**Pull request by bitloi**
## Problem
When a user defines an alias with a name that matches an existing task or setting key (e.g., `alias c = compile` when a custom task `c` exists), the alias silently wins and shadows the task.

## Solution
Detect conflicts at alias creation time and fail with an error message:
```
Alias 'c' conflicts with a task or setting key of the same name. Use a different alias name to avoid ambiguity.
```

## Changes
- `BasicKeys.scala` - Add `definedTaskNames` AttributeKey to store all key names
- `BasicCommands.scala` - Add `hasConflictingKey` function, modify `addAlias` to check conflicts
- `ProjectExtra.scala` - Add `collectAllKeyNames` helper, populate `definedTaskNames` in `setProject`

## Test
- `sbt-app/src/sbt-test/actions/alias-key-conflict/` - Scripted test verifying conflict detection

Fixes #2883

### CODE REVIEW

**Comment by bitloi** [comment]
@eed3si9n Please check the pr and give me your feedback

File: main-command/src/main/scala/sbt/BasicKeys.scala [hunk 1]
```diff
@@ -172,6 +172,12 @@ object BasicKeys {
     "Toggles whether or not to close system in, out and error when the server starts.",
     1000
   )
+
+  private[sbt] val definedTaskNames = AttributeKey[Set[String]](
+    "defined-task-names",
+    "Set of all defined task and setting key names in the build.",
+    10
+  )
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/BasicKeys.scala]: Thanks for the contribution.

Given the existence of structure.index.keyIndex, I don't think it's worth creating a separate thing just for alias purpose. Could we extract the definedTaskNames on the fly in from State inside of `addAlias` where you'd have access to a State?

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: sbt-app/src/sbt-test/actions/alias-key-conflict/test [hunk 2]
```diff
@@ -0,0 +1,6 @@
+# Test that alias creation fails when it conflicts with a task key name
+# The task 'c' is defined in build.sbt, so 'alias c = compile' should fail
+-> alias c = compile
```
Comment (eed3si9n) [inline sbt-app/src/sbt-test/actions/alias-key-conflict/test:3]: The test looks great.

File: main-command/src/main/scala/sbt/BasicKeys.scala (hunk 1 above)
Comment (bitloi) [reply main-command/src/main/scala/sbt/BasicKeys.scala]: Done - updated to extract key names on-the-fly from `keyIndex` instead of storing them separately.

File: main/src/main/scala/sbt/ProjectExtra.scala [hunk 3]
```diff
@@ -276,19 +276,30 @@ trait ProjectExtra extends Scoped.Syntax:
...
     }
 
+    private def collectAllKeyNames(keyIndex: sbt.internal.KeyIndex): Set[String] =
+      val globalKeys = keyIndex.keys(None)
+      val projectKeys = for
+        uri <- keyIndex.buildURIs
+        project <- keyIndex.projects(uri)
+        key <- keyIndex.keys(Some(ProjectRef(uri, project)))
+      yield key
+      globalKeys ++ projectKeys
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/ProjectExtra.scala]: Could we move this to BasicCommands?

**Review by eed3si9n — CHANGES_REQUESTED** [review]

File: launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala:1]: Not sure if there's any changes on this file is needed.

File: main-command/src/main/scala/sbt/BasicKeys.scala [hunk 4]
```diff
@@ -172,6 +172,12 @@ object BasicKeys {
     "Toggles whether or not to close system in, out and error when the server starts.",
     1000
   )
+
+  private[sbt] val keyNameExtractor = AttributeKey[() => Set[String]](
+    "key-name-extractor",
+    "Function to extract all defined task and setting key names from the build.",
+    10
+  )
```
Comment (eed3si9n) [inline main-command/src/main/scala/sbt/BasicKeys.scala]: Hopefully we don't need this key any more?

**Review by eed3si9n — APPROVED** [review]
Thanks!
