### PR TITLE
[2.x] fix: skip writing sbt.version in scripted test directories

### LINKED ISSUE #4536: Writing sbt.version vs scripted filtering
## steps

1. Write a scripted test
1. Run sbt in that scripted test

## problem

sbt will write out `sbt.version` under `project/build.properties` which acts as a test filter.

## expectation

The, possibly discouraged, practice of running sbt in a scripted test shouldn't implicitly alter the test setup.

## notes
sbt version: 1.2.8

Possible solutions:
One possible solution is just before writing the file sbt can detect it's running a scripted test and skip writing.  Maybe a stupid "Am I inside ../../sbt-test?" 😕

Or maybe the filtering shouldn't be based on `sbt.version` in `project/build.properties` but on something else (let's say, temporarily, `sbt.filter.version`).  In addition, the filter version could be a bit more flexible than a flat version, like maybe `^1.1`, `~1.2`, or `>=1.0.0, <1.1.0`.  See:

* https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
* https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1
* https://docs.npmjs.com/misc/semver#ranges

This solution I'd say should include giving a deprecation warning about the old use of sbt.version for filtering, and maybe that warning could also educate the sbt user that you can temporarily change the sbt version with the system property sbt.version: `sbt -Dsbt.version=1.2.1`.

### PR DESCRIPTION
**Pull request by bitloi**
## Summary

When sbt runs inside a scripted test, it no longer writes `sbt.version` to `project/build.properties`. That file is used to filter which scripted tests run; writing it during a test would change the test setup for future runs.

## Problem

1. Write a scripted test that runs sbt in that test.
2. sbt writes `sbt.version` under `project/build.properties`, which acts as a test filter.
3. The test setup is implicitly altered.

## Solution

Before writing `build.properties`, sbt checks whether the base directory is inside a scripted test directory (path contains `sbt-test`). If so, it skips writing so the test setup is not altered.

## Changes

- **Main.scala:** Add `isScriptedTestDirectory(baseDir)` (path contains `/sbt-test/` or `\sbt-test\`). In `writeSbtVersionUnconditionally`, return early when inside a scripted test directory.

## References

- Fixes https://github.com/sbt/sbt/issues/4536

### CODE REVIEW

**Comment by eed3si9n** [comment]
I appreciate the effort, but I don't want sbt to get into some custom resolution beyond Coursier. That's a slippery slope of sbt doing something different from other build tools in Scala, also if we don't coordinate with both publishing and Coursier we could get into a situation where library A's test runs in some classpath, but some other project B depends on library A it won't use BOM properly.

**Comment by bitloi** [comment]
@eed3si9n That makes sense, thank you. Would it be alright if I work on #4536 instead of #4531 in the same branch?

**Comment by eed3si9n** [comment]
Yea, sounds good.

**Comment by bitloi** [comment]
Would you please review the simple changes?

File: main/src/main/scala/sbt/Main.scala [hunk 1]
```diff
@@ -1115,8 +1115,17 @@ object BuiltinCommands {
...
+  /** True if baseDir appears to be inside a scripted test directory (sbt#4536). */
+  private def isScriptedTestDirectory(baseDir: File): Boolean = {
+    val path = baseDir.getAbsolutePath
+    path.contains(java.io.File.separator + "sbt-test" + java.io.File.separator) ||
+    path.contains("/sbt-test/")
+  }
+
+  private def writeSbtVersionUnconditionally(state: State): Unit = {
     val baseDir = state.baseDir
+    if (isScriptedTestDirectory(baseDir)) return // sbt#4536: don't alter scripted test setup
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Main.scala]: Generally we try to avoid `return` statement - https://github.com/sbt/sbt/blob/develop/contributing-docs/03_coding_style.md#returns. Could you turn this into big if-else instead please?

**Review by eed3si9n — CHANGES_REQUESTED** [review]
overall lgtm

File: main/src/main/scala/sbt/Main.scala (hunk 1 above)
Comment (bitloi) [reply main/src/main/scala/sbt/Main.scala]: Done

**Review by eed3si9n — APPROVED** [review]
Thanks @bitloi!
