### PR TITLE
Exit BspClient after server socket is closed

### LINKED ISSUE #5651: BSP server does not respond when connected sbt server is closed
## steps

1. start an sbt shell on a project
2. start a BSP server for the same project (eg via opening it in IntelliJ)
3. the BSP server will connect to the existing shell
4. close the shell

## problem
1. BSP server throws an error:
```
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
at java.base/java.lang.System.arraycopy(Native Method)
at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:129)
at java.base/java.io.PrintStream.write(PrintStream.java:559)
at sbt.internal.client.BspClient.sbt$internal$client$BspClient$$transferTo(BspClient.scala:26)
at sbt.internal.client.BspClient$$anon$1.run(BspClient.scala:34)
```
2. running a request on the server hangs indefinitely with no response.

## expectation

Either:
* BSP server exits, so client can start a fresh process, or
* BSP server responds with error on request, or
* BSP server start its own fresh sbt process

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #5651

### CODE REVIEW

**Comment by adpi2** [comment]
Fixes #5651

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala [hunk 1]
```diff
@@ -18,24 +18,39 @@ import scala.sys.process.Process
...
         override def run(): Unit = transferTo(sbtServer.getInputStream, System.out)
       }
 
-      redirection.start()
-      transferTo(System.in, sbtServer.getOutputStream)
+      val stdToSocket = new Thread {
+        override def run(): Unit = transferTo(System.in, sbtServer.getOutputStream)
+      }
+
+      socketToStd.start()
```
Comment (eatkins) [inline main-command/src/main/scala/sbt/internal/client/BspClient.scala]: I think socketToStd and stdToSocket both look like the should be daemon threads. It maybe doesn't matter but is good practice.

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala [hunk 2]
```diff
@@ -18,24 +18,39 @@ import scala.sys.process.Process
...
     while (true) {
       val size = input.read(buffer)
-      output.write(buffer, 0, size)
-      output.flush()
+      if (size == -1) synchronized {
+        output.close()
+        terminated = true
+        notify()
+      } else {
+        output.write(buffer, 0, size)
```
Comment (eatkins) [inline main-command/src/main/scala/sbt/internal/client/BspClient.scala]: All of the io calls (`input.read`, `output.write` and `output.flush`) could throw an `IOException`. For example, if you `kill -9` the server, I think `input.read` will throw an exception rather than return `-1`. My guess is that you want to exit if that happens so I'd recommend adding a `try` / `catch` block that sets terminated to true and notifies the main thread if an unexpected error occurs.

**Review by eatkins — CHANGES_REQUESTED** [review]

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala (hunk 2 above)
Comment (eatkins) [reply main-command/src/main/scala/sbt/internal/client/BspClient.scala]: (this by the way is why I think scala's ignoring checked exceptions from java was a horrible design decision).

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala (hunk 1 above)
Comment (adpi2) [reply main-command/src/main/scala/sbt/internal/client/BspClient.scala]: Thank you @eatkins for this review. It's the first time I hear about daemon process.

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala (hunk 2 above)
Comment (adpi2) [reply main-command/src/main/scala/sbt/internal/client/BspClient.scala]: From what I have experienced the socket would return `-1` even if the server process is abruptly killed. But that may depends on the implementation which itself depends on the OS and JVM. So I think you are right, it is a lot safer to catch and terminate the process in case of exception.

File: main-command/src/main/scala/sbt/internal/client/BspClient.scala [hunk 3]
```diff
@@ -18,24 +18,45 @@ import scala.sys.process.Process
...
+            if (size == -1) {
+              terminated = true
+            } else {
+              output.write(buffer, 0, size)
+              output.flush()
+            }
+          }
+          input.close()
+          output.close()
+        } finally {
```
Comment (eatkins) [inline main-command/src/main/scala/sbt/internal/client/BspClient.scala:42]: If you don’t catch the exception, it will print a stacktrace. If you don’t care about that, this is fine. I’m not sure where the stacktrace would be logged with the bsp client so it’s up to you to make that call.

Comment (adpi2) [reply main-command/src/main/scala/sbt/internal/client/BspClient.scala:42]: The stacktrace will be printed to `System.err` which is not good because the parent process will try to interpret it as a json-RPC message...

**Comment by adpi2** [comment]
@eatkins do you have any more comment on this PR? If not, could you please validate it?

**Review by eatkins — APPROVED** [review]
LGTM
