### PR TITLE
Avoid ParseKey failing due to homonymous axes

### LINKED ISSUE #3893: ParseKey failures on CI
I've now seen two incidence of `ParseKey` (in mainProj) failing. Once in #3865 8 days ago, now in  #3875.

---

In #3865 it failed with:

```
[info] ! Key parser test.An explicitly specified axis is always parsed to that explicit value: Falsified after 51 passed tests.
[info] > Labels of failing property: 
[info] Key string: 'q / g'
[info] Structure: Env:
[info]     Tasks:
[info]     f (delegates: qq)
[info]     q (delegates: qq)
[info]     g (delegates: qq)
[info]     ka (delegates: qq)
[info]     someNfu (delegates: qq)
[info]     qq (delegates: )
[info] Build mfh:nam#cwhvfd :
[info]     Project q
[info]       Delegates:
[info]         ProjectRef(mfh:nam#cwhvfd,jqqdsp)
[info]       Configurations:
[info]         a
[info]         wz
[info]     Project jqqdsp
[info]       Delegates:
[info]         
[info]       Configurations:
[info]         a
[info]         wz
[info] current: ProjectRef(mfh:nam#cwhvfd,q)
[info] Settings:
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / A / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / A / qq / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / A / someNfu / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / f / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / g / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / ka / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / qq / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / Wz / someNfu / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / f / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "jqqdsp") / qq / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "q") / ka / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] 
[info] 	ProjectRef(uri("mfh:nam#cwhvfd"), "q") / someNfu / <key>
[info] 	   qq,ka,f,q,g,someNfu
[info] All keys:
[info] 	qq, ka, f, q, g, someNfu
[info] Expected: ProjectRef(uri("mfh:nam#cwhvfd"), "q") / q / g
[info] Scope(Select(ProjectRef(mfh:nam#cwhvfd,q)), Zero, Zero, Zero) == Scope(Select(ProjectRef(mfh:nam#cwhvfd,q)), Zero, Select(q), Zero): false
[info] ScopedKey(Scope(Select(ProjectRef(mfh:nam#cwhvfd,q)), Zero, Zero, Zero),g).key == ScopedKey(Scope(Select(ProjectRef(mfh:nam#cwhvfd,q)), Zero, Select(q), Zero),g).key: true
[info] Parsed: Right(ProjectRef(uri("mfh:nam#cwhvfd"), "q") / g)
[info] Mask: ScopeMask(false,false,true,false)
[info] Key: {mfh:nam#cwhvfd} / Wz / q / g
[info] > ARG_0: sbt.ParseKey$StructureKeyMask@626bae4c
```

---

In #3875 it failed with

```
! Key parser test.An unspecified project axis resolves to the current project: Falsified after 75 passed tests.
[info] > Labels of failing property: 
[info] Key string: 'a / m'
[info] Current: ProjectRef(pztl:v,lwSq)
[info] Parsed: Right(ProjectRef(uri("pztl:v"), "a") / m)
[info] Key: ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / a / m
[info] Mask: ScopeMask(false,false,true,false)
[info] Structure: Env:
[info]     Tasks:
[info]     a (delegates: zizv, db)
[info]     zizv (delegates: m, db)
[info]     m (delegates: db)
[info]     db (delegates: )
[info] Build pztl:v :
[info]     Project spgubHtn
[info]       Delegates:
[info]         ProjectRef(pztl:v,qB)
[info]         ProjectRef(pztl:v,lwSq)
[info]       Configurations:
[info]         ol
[info]     Project j
[info]       Delegates:
[info]         ProjectRef(pztl:v,lwSq)
[info]         ProjectRef(pztl:v,qB)
[info]       Configurations:
[info]         ol
[info]     Project gdjE
[info]       Delegates:
[info]         ProjectRef(pztl:v,a)
[info]         ProjectRef(pztl:v,lwSq)
[info]       Configurations:
[info]         ol
[info]     Project a
[info]       Delegates:
[info]         ProjectRef(pztl:v,btQpaK)
[info]         ProjectRef(pztl:v,lwSq)
[info]       Configurations:
[info]         ol
[info]     Project btQpaK
[info]       Delegates:
[info]         ProjectRef(pztl:v,qB)
[info]         ProjectRef(pztl:v,lwSq)
[info]       Configurations:
[info]         ol
[info]     Project qB
[info]       Delegates:
[info]         ProjectRef(pztl:v,lwSq)
[info]       Configurations:
[info]         ol
[info]     Project lwSq
[info]       Delegates:
[info]         
[info]       Configurations:
[info]         ol
[info]   Build rwMsmGul:nrh#xu :
[info]     Project nfCusdu
[info]       Delegates:
[info]         
[info]       Configurations:
[info]         ol
[info] current: ProjectRef(pztl:v,lwSq)
[info] Settings:
[info] 	Global / <key>
[info] 	   m,a,zizv,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / <key>
[info] 	   a,m,zizv,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / Ol / <key>
[info] 	   db,a,m,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / Ol / db / <key>
[info] 	   m,db,zizv,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / Ol / zizv / <key>
[info] 	   zizv,a,db,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / a / <key>
[info] 	   zizv,db,a,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "a") / db / <key>
[info] 	   m,a,db,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / Ol / <key>
[info] 	   zizv,db,m,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / Ol / a / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / Ol / db / <key>
[info] 	   zizv,a,db,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / Ol / m / <key>
[info] 	   zizv,a,db,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / Ol / zizv / <key>
[info] 	   a,zizv,m,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / db / <key>
[info] 	   m,a,db,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / m / <key>
[info] 	   zizv,a,db,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "btQpaK") / zizv / <key>
[info] 	   a,m,zizv,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "gdjE") / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "gdjE") / a / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "gdjE") / m / <key>
[info] 	   zizv,db,a,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "j") / Ol / db / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "j") / Ol / zizv / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "j") / a / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "j") / db / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "j") / m / <key>
[info] 	   m,zizv,db,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / Ol / <key>
[info] 	   zizv,m,a,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / Ol / db / <key>
[info] 	   db,zizv,m,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / Ol / m / <key>
[info] 	   m,zizv,a,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / Ol / zizv / <key>
[info] 	   a,m,db,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / a / <key>
[info] 	   db,zizv,m,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / db / <key>
[info] 	   zizv,db,m,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / m / <key>
[info] 	   db,a,m,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "lwSq") / zizv / <key>
[info] 	   a,zizv,db,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / <key>
[info] 	   m,zizv,db,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / Ol / a / <key>
[info] 	   m,zizv,db,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / Ol / db / <key>
[info] 	   db,a,m,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / Ol / zizv / <key>
[info] 	   a,m,db,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / db / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("pztl:v"), "qB") / zizv / <key>
[info] 	   db,a,m,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "spgubHtn") / Ol / <key>
[info] 	   a,zizv,m,db
[info] 
[info] 	ProjectRef(uri("pztl:v"), "spgubHtn") / Ol / a / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("pztl:v"), "spgubHtn") / Ol / db / <key>
[info] 	   db,m,zizv,a
[info] 
[info] 	ProjectRef(uri("pztl:v"), "spgubHtn") / m / <key>
[info] 	   db,zizv,a,m
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / <key>
[info] 	   db,m,zizv,a
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / <key>
[info] 	   zizv,m,a,db
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / a / <key>
[info] 	   db,zizv,a,m
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / db / <key>
[info] 	   m,a,zizv,db
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / m / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / Ol / zizv / <key>
[info] 	   db,m,a,zizv
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / a / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / db / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / m / <key>
[info] 	   m,db,zizv,a
[info] 
[info] 	ProjectRef(uri("rwMsmGul:nrh#xu"), "nfCusdu") / zizv / <key>
[info] 	   a,zizv,m,db
[info] 
[info] 	Zero / Ol / db / <key>
[info] 	   zizv,a,m,db
[info] 
[info] 	Zero / Ol / m / <key>
[info] 	   db,a,zizv,m
[info] 
[info] 	Zero / a / <key>
[info] 	   a,db,zizv,m
[info] 
[info] 	Zero / db / <key>
[info] 	   db,m,zizv,a
[info] 
[info] 	Zero / m / <key>
[info] 	   a,db,zizv,m
[info] 
[info] 	Zero / zizv / <key>
[info] 	   a,db,m,zizv
[info] All keys:
[info] 	a, m, db, zizv
[info] > ARG_0: sbt.ParseKey$StructureKeyMask@2421d6b0
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #3893

My interest was in:
* properly understanding the root cause,
* the history that led to it occurring,
* why the test code didn't catch it at the time,
* why the output was so incomprehensible (not nicely shrunk down), and finally
* finding a way to stop it from failing

The failure in ParseKey reported in #3893 (which I'm calling "homonymous axes") is actually legitimate:  sbt will display a key in a way that it won't then parse.  I agree that the solution would be to make the build fail to load if that happens, but I didn't go down that road to figuring out how to do that.

### CODE REVIEW

File: main/src/test/scala/ParseKey.scala [hunk 1]
```diff
@@ -350,4 +367,12 @@ object ParseKey extends Properties("Key parser test") {
       case (delegates, key) => Taskk(key, delegates)
     }
   }
+
+  // if both a project and a key share the same name (e.g. "foo")
+  // then a scoped key like `foo/<conf>/foo/name` would render as `foo/name`
+  // which would be interpreted as `foo/Zero/Zero/name`
+  // so we mitigate this by explicitly displaying the configuration axis set to Zero
```
Comment (eed3si9n) [inline main/src/test/scala/ParseKey.scala:374]: +1

**Review by eed3si9n — APPROVED** [review]
