### PR TITLE
Fixes #1439. Fixes metabuild downloading unused Scala 2.10.2

### LINKED ISSUE #1439: Meta build resolves to unused Scala 2.10.2
## steps
1. Use sbt 0.13.5 with the following plugins:

`project/plugins.sbt`:

``` scala
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.1.2")

addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.1.6")

ivyPaths :=  new IvyPaths((baseDirectory in ThisBuild).value, Some((baseDirectory in ThisBuild).value / "ivy-cache"))
```

`build.sbt`:

``` scala
ivyPaths :=  new IvyPaths((baseDirectory in ThisBuild).value / "project", Some((baseDirectory in ThisBuild).value / "project" / "ivy-cache"))
```

Run:

```
$ sbt exit
```
## problem

The meta build resolves to Scala 2.10.2 and downloads it.
## expectation

The meta build uses Scala 2.10.4 (or which ever Scala version the sbt 0.13.x uses)
## notes (workaround posted by @eed3si9n)

Put this in `project/plugins.sbt`:

``` scala
libraryDependencies += "org.scala-lang" % "scala-compiler" % scalaVersion.value
```

Meta build's Compile configuration seems to be unaware of the ultimate Scala version the build uses (2.10.4 for sbt 0.13.5) and uses the Scala version that the plugins used to publish. The above workaround uses Ivy eviction to bump up scala-compiler and scala-library version.
## original report by @fommil (Sbt downloads precompiled incremental compiler interfaces that users never plan to use)

in one of the projects I contribute to http://github.com/ensime/ensime-server and starting with a fresh ivy cache, type `sbt compile` for this scala 2.10.4 project and see several versions of the scala-compiler and sbt itself being downloaded.

Are all dependencies aggressively downloaded before working out what is evicted?

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #1439 

Scala instance is added to the Ivy graph via autoLibraryDependency. For metabuilds, scala-library is scoped under “provided” configuration, which does not seem to evict modules on “compiled” configuration.

This PR turns `overrideScalaVersion` flag to `true` for the metabuilds, so override rules are added for the following modules:
- scala-library
- scala-compiler
- scala-reflect

/review @havocp

### CODE REVIEW

File: ivy/src/main/scala/sbt/IvyScala.scala [hunk 1]
```diff
@@ -47,6 +48,7 @@ private object IvyScala {
   def overrideScalaVersion(module: DefaultModuleDescriptor, version: String) {
     overrideVersion(module, Organization, LibraryID, version)
     overrideVersion(module, Organization, CompilerID, version)
+    overrideVersion(module, Organization, ReflectID, version)
   }
```
Comment (havocp) [inline ivy/src/main/scala/sbt/IvyScala.scala:52]: this change (make overrideScalaVersion apply to scala-reflect also) seems logically distinct from making the metabuild set overrideScalaVersion - this will apply to the regular build too not just the metabuild right? (assuming the regular build sets overrideScalaVersion)

Which is fine, but potentially it could have been a separate commit

File: ivy/src/main/scala/sbt/IvyScala.scala [hunk 2]
```diff
@@ -16,6 +16,7 @@ object ScalaArtifacts {
   val Organization = ScalaOrganization
   val LibraryID = ScalaLibraryID
   val CompilerID = ScalaCompilerID
+  val ReflectID = "scala-reflect"
```
Comment (havocp) [inline ivy/src/main/scala/sbt/IvyScala.scala:19]: this makes me say "why is scala-reflect a string literal and the other two are symbols" - is there a good reason?

Comment (eed3si9n) [inline ivy/src/main/scala/sbt/IvyScala.scala:19]: This area of code predates the current modularization trend that's happening around Scala compiler and standard libraries. The first two come from [ArtifactInfo.java](https://github.com/sbt/sbt/blob/0.13/interface/src/main/java/xsbti/ArtifactInfo.java), which is used to share code between the launcher and sbt itself. I don't think the launcher needs to be aware of the "scala-reflect." Also I'm not sure if touching the interface is going to inadvertently create sbt 0.13.6 launcher dependence.

File: ivy/src/main/scala/sbt/IvyScala.scala (hunk 1 above)
Comment (eed3si9n) [inline ivy/src/main/scala/sbt/IvyScala.scala:52]: Yes. This was more of a housekeeping that I did while debugging. I should've split it in another commit in hindsight.

**Comment by paulp** [comment]
>  For metabuilds, scala-library is scoped under “provided” configuration, which does not seem to evict modules on “compiled” configuration.

Can you explain why it is in the "provided" configuration and not the "scala-tool" configuration? I'm not going to pretend to understand how configurations are supposed to be used, but here's what the [sbt documentation](http://www.scala-sbt.org/0.13/docs/Combined+Pages.html) says:

`sbt still needs access to the compiler and its dependencies in order to run compile,
 console, and other Scala-based tasks. So, the Scala compiler jar and dependencies 
(like scala-reflect.jar and scala-library.jar) are defined and resolved in the scala-tool
configuration (unless scalaHome is defined).`

If that only applies to the build and not to the meta-build, is there some logic at work which would allow one to anticipate that difference?

**Comment by eed3si9n** [comment]
Ivy configurations are just name of graphs that hopefully resolves to some JARs at the end, and names make little sense.

## Compile

`Compile` is the main graph that's used for the proper build's projects as well as metabuild's projects (plugins). Because scala-library is part of normal `Compile`, for proper builds, eviction _by design_ bumps up your scala-library version above what's specified by `scalaVersion`.

## Provided

For metabuilds, we don't want the Ivy graph's resolution to include scala-library, because they are provided by sbt itself. But we still need it during the compilation of the sbt plugins, so `Provided` fits the bill. 

## ScalaTool

`ScalaTool` is a private graph used by sbt itself to download Scala compiler JAR off the Internet. Unless your local instance is provided, this is what's used by `compile` task, and `scalaVersion`, as far as I know, won't get bumped. Should `scalaVersion` be controlling both the compiler and the standard library's version? I'm not really sure.

**Comment by paulp** [comment]
> Should scalaVersion be controlling both the compiler and the standard library's version? I'm not really sure.

Though I've no doubt someone can dream up a reason for those version dials to spin independently, there is no way a normal person will benefit from having mismatched library and compiler jars, especially unknowingly.

The configuration names may have no inherent meaning but there are fundamental aspects of sbt's behavior which can only be influenced through these configurations, so it seems like a good place to superimpose some order. Configuration.scala defines a whole raft of configurations, has zero meaningful comments, and then on top of that, the codebase is littered with places where the Configuration instances aren't even used and a nice raw String is presented instead.

The fact that the names are uses are completely arbitrary means they have to be defined and handled with utmost care, but so far the opposite discipline seems to have held.
