### PR TITLE
[2.x] fix: Handle paths with parentheses in sbt.bat on Windows

### LINKED ISSUE #8644: Windows: sbt.bat fails when project path contains parentheses
## Description

SBT fails to run on Windows when the project directory path contains parentheses `()`. The Windows batch launcher (`sbt.bat`) does not properly escape or quote paths with special characters, causing CMD to interpret parentheses as command grouping syntax.

## Steps to Reproduce

1. Create a Windows user account with parentheses in the username (e.g., `Anshuman(work)`)
2. Create or clone an SBT project in a path containing parentheses:
   ```
   C:\Users\Anshuman(work)\Desktop\myproject
   ```
3. Open CMD or PowerShell
4. Navigate to the project directory
5. Run any SBT command:
   ```
   sbt compile
   ```

## Expected Behavior

SBT should execute the command successfully, handling the parentheses in the path correctly.

## Actual Behavior

**In CMD:**
```
) was unexpected at this time.
```

**In PowerShell (calling sbt.bat):**
```
) was unexpected at this time.
```

The error occurs because Windows CMD interprets `(` and `)` as special syntax for command grouping, and the SBT launcher script doesn't properly quote the working directory path.

## Environment

- **OS:** Windows 11
- **SBT Version:** 1.11.7 (likely affects all versions)
- **Java Version:** OpenJDK 11.0.29
- **Shell:** Both CMD and PowerShell (when using sbt.bat)
- **Path with issue:** Any path containing `(` or `)` characters

### PR DESCRIPTION
**Pull request by Eruis2579**
## Problem

Windows CMD interprets parentheses as special syntax for command grouping. When the project directory path contains parentheses (e.g., in username like `C:\\Users\\Anshuman(work)\\Desktop\\myproject`), the batch script fails with `) was unexpected at this time.` error.

## Solution

This fix stores the current directory in a variable using delayed expansion (`!CURRENT_DIR!`) instead of using `%CD%` directly, which properly handles paths containing parentheses and other special characters.

## Changes

- Added `set "CURRENT_DIR=%CD%"` to store the current directory in a variable
- Changed `"%CD%"` to `"!CURRENT_DIR!"` in the error message to use delayed expansion
- Added test script `test-parentheses-path.bat` to verify the fix works correctly

## Testing

A test script has been added (`launcher-package/citest/test-parentheses-path.bat`) that:
1. Creates a test directory with parentheses in the name
2. Runs sbt.bat from that directory
3. Verifies error messages display correctly without parsing errors

This fix ensures that paths with parentheses are properly handled when displayed in error messages. The delayed expansion mechanism in Windows batch files correctly processes special characters.

Fixes #8644

### CODE REVIEW

**Comment by eed3si9n** [comment]
Hi @Eruis2579, thanks for the contribution!

Please follow https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md and:
1. include tests for the change
2. read our Gen-AI assisted contributions guideline (please declare usage in the PR description, if you used it)
3. sign Scala CLA https://contribute.akka.io/contribute/cla/scala

**Comment by Eruis2579** [comment]
> Hi @Eruis2579, thanks for the contribution!
> 
> Please follow https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md and:
> 
> 1. include tests for the change
> 2. read our Gen-AI assisted contributions guideline (please declare usage in the PR description, if you used it)
> 3. sign Scala CLA https://contribute.akka.io/contribute/cla/scala

Hi, @eed3si9n , Thank you for your review
I have added tests for the change and signed Scala CLA.
Please check again.

**Comment by eed3si9n** [comment]
Could you write the test using Scala if possible? Here's an example - https://github.com/sbt/sbt/blob/f05a96aceb487f9f765bd13182a8a6f432f37403/launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala#L105-L115

**Comment by Eruis2579** [comment]
Hi, @eed3si9n 
I added the test using Scala. Please test it.
Thanks for your review.

File: launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala [hunk 1]
```diff
@@ -181,4 +181,56 @@ object ExtendedRunnerTest extends BasicTestSuite:
...
+
+  // Test for issue #8644: sbt.bat fails when project path contains parentheses
+  // https://github.com/sbt/sbt/issues/8644
+  test("sbt.bat handles paths with parentheses") {
+    if (!isWindows) {
+      // This test is Windows-specific, skip on other platforms
+      ()
+    } else {
+      // Create a temporary directory with parentheses in the name
+      val baseDir = IO.createTemporaryDirectory
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/ExtendedRunnerTest.scala]: minor nit.

Could you use "loan" pattern, like:

```scala
    IO.withTemporaryDirectory: baseDir =>
      val testDir = new File(baseDir, "test(parentheses)")
```

that will automatically delete the `baseDir` even if something throws an exception in the middle.

**Review by eed3si9n — APPROVED** [review]
Overall looking good! Thanks!

**Comment by Eruis2579** [comment]
Hi, @eed3si9n 
Can you merge my PR?
thank you.

**Comment by eed3si9n** [comment]
@Eruis2579 Landed. Would you like to double dip on this by cherry picking the commit on against 1.12.x branch? I've created an issue https://github.com/sbt/sbt/issues/8658
