### PR TITLE
[2.x] fix: handle -sbt-dir with spaces from .sbtopts

### LINKED ISSUE #7197: Sbt options are treated differently
When I invoke in terminal 
`sbt -sbt-dir "/Users/a' dog" --verbose`
the output shows that this option is mapped to `"-Dsbt.global.base=/Users/a' dog"` 
But later when I will move this option from terminal to the `.sbtopts` file and invoke `sbt --verbose` the output shows that it is mapped to `-Dsbt.global.base=/Users/a'`

Whether this difference has some hidden purpose ? It introduces additional inconsistency 

SBT: sbt1.8.2
OS: macOs 12.13.1

### PR DESCRIPTION
**Pull request by Eruis2579**
fixes #7197

## Fix

Handle `-sbt-dir` values with spaces and quotes when they come from `.sbtopts`, so they behave the same as when passed on the command line.

### Problem

When you pass `-sbt-dir "/Users/a' dog"` on the command line, the launcher correctly produces:

`-Dsbt.global.base=/Users/a' dog`

But when you put the same option into `.sbtopts`, the launcher previously split the line on spaces without respecting quotes, so the resulting `-Dsbt.global.base` was truncated (for example, `-Dsbt.global.base=/Users/a'`). This made `.sbtopts` behavior inconsistent with CLI behavior and broke setups where the global sbt directory path contains spaces and an embedded quote.

### File changed

- `sbt`
  - Added a quote-aware `parseLineIntoWords()` helper and `appendSbtoptsFromFile()` to read `.sbtopts` files and populate `sbt_file_opts` without breaking paths that contain spaces and quotes.
  - Switched sbtopts loading from `sbt_file_opts+=($(loadConfigFile ...))` to using `appendSbtoptsFromFile` for machine, dist, and project `.sbtopts`, keeping precedence the same but fixing parsing.

- `launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala`
  - Added an integration test `"sbt -sbt-dir with space and quote in .sbtopts"` that:
    - Writes project `.sbtopts` with `-sbt-dir "/Users/a' dog"`.
    - Runs the launcher with `-d -v`.
    - Asserts that the final command line contains a `-Dsbt.global.base=...` whose value includes the full `/Users/a' dog` path (space and quote preserved).

### Test

./sbt "launcherPackageIntegrationTest/testOnly example.test.RunnerScriptTest"

### CODE REVIEW

**Comment by Eruis2579** [comment]
Hi, @eed3si9n , Please review my PR

File: launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala [hunk 1]
```diff
@@ -252,6 +252,31 @@ abstract class RunnerScriptTest extends verify.BasicTestSuite with ShellScriptUt
         s"sbtopts options should appear before CLI memory settings. g1Index=$g1Index, xmxCliIndex=$xmxCliIndex"
       )
 
+  // Test for issue #7197: -sbt-dir with spaces (and quotes) in .sbtopts
+  testOutput(
+    "sbt -sbt-dir with space and quote in .sbtopts",
+    sbtOptsFileContents = """-sbt-dir "/Users/a' dog"""",
+  )("-d", "-v"): (out: List[String]) =>
+    if (isWindows) cancel("Test not supported on windows")
```
Comment (eed3si9n) [inline launcher-package/integration-test/src/test/scala/RunnerScriptTest.scala]: Hi, thanks for the contribution! Please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually
2. Include tests for the change
3. Follow our AI assisted contributions guideline (please disclose AI usages in the PR description, if any)
4. Multiple contributors might work on this issue in parallel
5. Generally we recommend getting CI to pass on a forked repo before sending a pull request (pull requests that do not pass tests will be closed after a few days)

Note that there was a similar pull request you sent https://github.com/sbt/sbt/pull/8730, but unfortunately, I had to revert it in https://github.com/sbt/sbt/pull/8797 because it seems to have caused https://github.com/sbt/sbt/issues/8767. Instead of isWindows cancel, could you pass to `testOutput(...)`, which should now test this on Git Bash on Windows (https://github.com/sbt/sbt/pull/8779)

```scala
    windowsSupport = false,
```

**Review by eed3si9n — CHANGES_REQUESTED** [review]

**Review by eed3si9n — APPROVED** [review]
Thanks!
