### PR TITLE
[2.x] fix: Restores Scala 2 reflect/compiler unification

### LINKED ISSUE #8689: sbt 1.12.1 brings in jline classes targetting java 22
## steps

Sbt version upgraded from 1.12.0 to 1.12.1. Targetted java version is 21.

## problem

On running acceptance tests,

```
An exception or error caused a run to abort: org/jline/terminal/impl/ffm/CLibrary$termios has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
  java.lang.UnsupportedClassVersionError: org/jline/terminal/impl/ffm/CLibrary$termios has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
```

## expectation

sbt 1.12.1 and 1.12.2 should inter-work with java 21. 

## notes

Looking at an excerpt of the dependency tree, with sbt 1.12.0:

```
[info]   | +-eu.timepit:refined_2.13:0.11.3 [S]
[info]   |   +-com.chuusai:shapeless_2.13:2.3.12 (evicted by: 2.3.13)
[info]   |   +-com.chuusai:shapeless_2.13:2.3.13 [S]
[info]   |   +-org.scala-lang:scala-compiler:2.13.15 (evicted by: 2.13.18)
[info]   |   +-org.scala-lang:scala-compiler:2.13.18 [S]
[info]   |   | +-io.github.java-diff-utils:java-diff-utils:4.16
[info]   |   | +-org.jline:jline:3.29.0
```

With sbt 1.12.1:

```
[info]   | +-eu.timepit:refined_2.13:0.11.3 [S]
[info]   |   +-com.chuusai:shapeless_2.13:2.3.12 (evicted by: 2.3.13)
[info]   |   +-com.chuusai:shapeless_2.13:2.3.13 [S]
[info]   |   +-org.scala-lang:scala-compiler:2.13.15 [S]
[info]   |   | +-io.github.java-diff-utils:java-diff-utils:4.12
[info]   |   | +-net.java.dev.jna:jna:5.14.0
[info]   |   | +-org.jline:jline:3.26.3
```

It appears that picking up the older version of jline is causing the problem, see the [related jline issue](https://github.com/jline/jline3/issues/1556).

### PR DESCRIPTION
**Pull request by calm329**
## Fix Scala 2 artifact version unification

Fixes #8689

### What was wrong

Commit 92b0564dc (fix for #8632) changed `csrSameVersions` so that Scala 2.13+ only aligned `scala-library` and `scala3-library`. This removed `scala-compiler` and `scala-reflect` from version
unification, so transitive dependencies pulling in an older `scala-compiler` (e.g. 2.13.15 via `refined_2.13`) were no longer evicted to match `scalaVersion` (e.g. 2.13.18). The older `scala-compiler`
brought in jline jars targeting Java 22, breaking builds on older JDKs.

### What this PR does

1. **Restore full `csrSameVersions` for Scala 2.x**: All Scala 2 artifacts (`scala-library`, `scala-compiler`, `scala-reflect`, `scala-actors`, `scalap`) are aligned again, regardless of minor
version. Scala 3.x keeps the narrower `Scala3_8Artifacts` set to avoid aligning artifacts that don't exist across major boundaries.

2. **Exclude `scala-library` in Scala 2→3.8+ sandwich deps**: In `projectDependenciesTask`, when a Scala 2 project depends on a Scala 3.8+ project, `scala-library` is excluded from the inter-project
dependency. This prevents `scala-library:3.x` from entering the Scala 2 resolution graph and triggering a cross-major-version bump via `csrSameVersions`. This preserves the fix for #8632.

3. **Restore `stdlib-unfreeze` test coverage**: `checkLibs` now verifies both `scala-library` and `scala-reflect` alignment. The negative assertion (`-> b/checkLibs` when `csrSameVersions := Nil`) is
restored.

### Testing

- `mainProj/compile` passes.
- Scripted: `dependency-management/stdlib-unfreeze`, `dependency-management/stdlib-unfreeze-warn`, `dependency-management/stdlib-unfreeze-update`, `dependency-management/stdlib-3.8`.

### CODE REVIEW

**Comment by calm329** [comment]
@eed3si9n Could you please review this pr?

File: main/src/main/scala/sbt/Defaults.scala [hunk 1]
```diff
@@ -4226,10 +4230,17 @@ object Classpaths {
...
                 .withCrossVersion(CrossVersion.constant(b.prefix + depSBV))
                 .withConfigurations(dep.configuration)
                 .withExplicitArtifacts(Vector.empty)
+              // When Scala 2 depends on Scala 3.8+, exclude scala-library to prevent
+              // scala-library:3.x from bumping Scala 2 artifacts via csrSameVersions.
+              // See https://github.com/sbt/sbt/issues/8632
+              val depSV = (dep.project / scalaVersion).get(data)
+              if sbv.startsWith("2.") && depSV.exists(ScalaArtifacts.isScala3_8Plus) then
+                base.exclude(ScalaArtifacts.Organization, ScalaArtifacts.LibraryID)
+              else base
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala]: @calm329  Thanks for the contribution! https://github.com/sbt/sbt/issues/8689#issuecomment-3861020257 is actually a developing issue, which I started larger discussion with the Scala 3 compiler team etc.

As I noted in the summary there, Scala 3.8 no longer supports being included into Scala 2.13 classpath, so at this point it's actually better to _not_ accommodate it, and let it fail, in part so we can prevent mysterious errors down the line when Scala 2.13 macros break because it can't find scala-library built using 2.13.

**Review by eed3si9n — CHANGES_REQUESTED** [review]

**Comment by eed3si9n** [comment]
I think +1 on reverting https://github.com/sbt/sbt/pull/8632, and then we can follow up with potentially detecting scala-reflect not found whose version >= 3.0 and display a custom error message.

File: main/src/main/scala/sbt/Defaults.scala [hunk 2]
```diff
@@ -3150,16 +3150,20 @@ object Classpaths {
...
           ScalaArtifacts.Artifacts
             .map(a => InclExclRule(scalaOrganization.value, a))
             .toSet :: Nil
-        // Due to the Scala 2.13-3.x sandwich, the absence of scala-reflect
-        // that corresponds with scala-library 3.8.x propagates to 2.13 builds as well.
-        case _ =>
+        // Scala 3.x should only align library artifacts to avoid issues with
+        // artifacts that don't exist across major version boundaries (e.g. scala-reflect for 3.8+)
+        // See https://github.com/sbt/sbt/issues/8224
+        case Some((3, _)) =>
```
Comment (eed3si9n) [inline main/src/main/scala/sbt/Defaults.scala:3166]: Scala 3.0 through 3.7 uses the standard library from Scala 2.13 universe, so I think we should continue to enforce `ScalaArtifacts.Artifacts` to line up.

**Comment by SethTisue** [comment]
fyi @lrytz

File: main/src/main/scala/sbt/Defaults.scala (hunk 2 above)
Comment (calm329) [reply main/src/main/scala/sbt/Defaults.scala:3166]: fixed it

**Comment by calm329** [comment]
@eed3si9n Could you re-run the failed CI checks? I don't think they're related to my change

**Comment by eed3si9n** [comment]
I have but looks like we're hitting the not found issue:

```bash
[info] [warn] 	Note: Unresolved dependencies path:
[info] [error] sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-reflect:3.8.1
[info] [error]   Not found
[info] [error]   Not found
[info] [error]   not found: /home/runner/.ivy2/local/org.scala-lang/scala-reflect/3.8.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/3.8.1/scala-reflect-3.8.1.pom
```

**Comment by calm329** [comment]
Now all checks have passed

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by ludwiggj** [comment]
Hi, apologies for a possibly stupid question, but I can see this is a backport candidate, which should mean that sbt 1.12.1 and 1.12.2 will be patched with this fix, and that the changes will then be automatically picked up in my code, correct?

My question is how will I know when this has happened? Will something be added to the https://github.com/sbt/sbt/releases page? I'm asking as once I know the backport has been published I can remove the temporary workaround I have in place whilst using the current versions of 1.12.1 and 1.12.2. Thanks!

**Comment by mzuehlke** [comment]
A backport would appear in a future 1.12.x release (not 1.11.x)
and be include in the release note of that future release.

You can either rely on system like Dependabot or Scala Steward to create pull request for new releases
or subscribe in Github to new releases of a project: https://github.blog/changelog/2018-11-26-watch-releases/

**Comment by eed3si9n** [comment]
+1 to what @mzuehlke said. I also usually make announcement on Reddit r/scala, [Mastodon](https://floss.social/@scala_sbt), [Bluesky](https://bsky.app/profile/scala-sbt.org), and on Scala Discord sbt channel as well.

**Comment by ludwiggj** [comment]
Thank you. Just so I'm clear, when that 1.12.x release is made, and announced, I can either move to that new release, or stay on the 1.12.1 release and I will automatically pick up the new backported version of 1.12.1 with this fix in it?

**Comment by SethTisue** [comment]
@ludwiggj version numbers (not just for sbt, but in general in software) are immutable; 1.12.1 and 1.12.2 will remain exactly as they are, from now until the end of time

you need to wait for 1.12.3 to be released

it's possible you're confused about what "1.12.x" means? it's just a shorthand for referring to the entire series 1.12.0, 1.12.1, 1.12.2, 1.12.3, ...

**Comment by ludwiggj** [comment]
Hi Seth, thanks. I understand what 1.12.x refers to. I think I was just confused but the use of the "backport candidate" label in this fix. What you're saying makes complete sense. So I'll move to 1.12.3 when it becomes available, and I guess 1.12.1 and 1.12.2 will always have this issue.

**Comment by SethTisue** [comment]
:+1:  (and fyi, in this context, "backport candidate" refers to backporting from sbt 2.x to sbt 1.x)

**Comment by eed3si9n** [comment]
[sbt 1.12.3](https://eed3si9n.com/sbt-1.12.3) is released.
