### PR TITLE
Fixes #1530. Fixes NPE by using IO.listFiles

### LINKED ISSUE #1530: NPE  in FileExamples
If I start sbt in /tmp and then hit tab, it goes boom. Doesn't happen if it has a char to work with.

```
/tmp# java -jar ~/.sbt/launchers/0.13.5/sbt-launch.jar
[info] Loading global plugins from /Users/paulp/.sbt/0.13/plugins
[info] Set current project to tmp (in build file:/private/tmp/)
> java.lang.NullPointerException
    at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
    at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
    at scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:91)
    at scala.collection.mutable.ArrayOps$ofRef.iterator(ArrayOps.scala:108)
    at scala.collection.IterableLike$class.toStream(IterableLike.scala:284)
    at scala.collection.mutable.ArrayOps$ofRef.toStream(ArrayOps.scala:108)
    at sbt.complete.FileExamples.files(ExampleSource.scala:54)
    at sbt.complete.FileExamples$$anonfun$files$1$$anonfun$apply$2.apply(ExampleSource.scala:57)
    at sbt.complete.FileExamples$$anonfun$files$1$$anonfun$apply$2.apply(ExampleSource.scala:57)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:450)
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #1530.

### CODE REVIEW

File: util/complete/src/main/scala/sbt/complete/ExampleSource.scala [hunk 1]
```diff
@@ -48,9 +48,9 @@ class FileExamples(base: File, prefix: String = "") extends ExampleSource {
   override def withAddedPrefix(addedPrefix: String): FileExamples = new FileExamples(base, prefix + addedPrefix)
 
   protected def files(directory: File): Stream[String] = {
-    val childPaths = directory.listFiles().toStream
-    val prefixedDirectChildPaths = childPaths.map(relativize(base, _).get).filter(_ startsWith prefix)
-    val dirsToRecurseInto = childPaths.filter(_.isDirectory).map(relativize(base, _).get).filter(dirStartsWithPrefix)
+    val childPaths = IO.listFiles(directory).toStream
```
Comment (jsuereth) [inline util/complete/src/main/scala/sbt/complete/ExampleSource.scala:51]: Ah, this has caught me many a time too... fun

**Comment by jsuereth** [comment]
LGTM
