### PR TITLE
Fixes #1711 and #1704. Cached resolution fixes

### LINKED ISSUE #1711: [0.13.7-RC2] cached resolution pulls in % "test" dependencies from other subproj
From: https://groups.google.com/forum/#!folder/Scala/sbt-dev/k4XZiKQjVHA

There seems to be one issue: it generates a different dependency tree for (at least) one of my modules. Noticeable because I now see deprecation warnings from the new version of the library which isn't supposed to be on my classpath and isn't with 0.13.6. Here is some data for said module, let's call it module A.
https://gist.github.com/japgolly/149ad9a9491a3515abca

Three problems are evident here.
1. I'm explicitly declaring 1.11.3 of ScalaCheck in my build but 1.11.4 is used.
2. This module dependsOn module B. Module B uses utest as a test dependency. I'm now see utest.jar on module A's test classpath.
3. Way more specs2 jars on the classpath. I'm explicitly only depending on -core and -scalacheck.

(By the way, I can't run dependencyTree for comparison because it doesn't work on 0.13.6 for some reason. Keeps harping on about blah-compile.xml not found.)

### PR DESCRIPTION
**Pull request by eed3si9n**
## fix for #1711

Cached resolution flattens external dependencies coming from subproject dependencies.
That process needs to ignore non-compile configurations, otherwise I'd end up with test dependencies from subprojects.
## fix for #1704

Exclude rules at the project level (using `ivyXML`) are now ported over to artificial graph so it's respected.

### CODE REVIEW

File: ivy/src/main/scala/sbt/ivyint/CachedResolutionResolveEngine.scala [hunk 1]
```diff
@@ -54,8 +54,10 @@ private[sbt] class CachedResolutionResolveCache() {
       def expandInternalDeps(dep: DependencyDescriptor): Vector[DependencyDescriptor] =
         prOpt map {
           _.getModuleDescriptor(dep.getDependencyRevisionId) match {
-            case Some(internal) => directDependencies(internal) flatMap expandInternalDeps
-            case _              => Vector(dep)
+            case Some(internal) => directDependencies(internal) filter { dd =>
+              !dd.getDependencyConfigurations("compile").isEmpty
```
Comment (jsuereth) [inline ivy/src/main/scala/sbt/ivyint/CachedResolutionResolveEngine.scala]: Why is this specific to compile?

**Comment by jsuereth** [comment]
LGTM
